In [1]:
import pandas as pd
df = pd.read_csv("../abstract_metadata_with_ideal_spans_correct_no_spans_with_min4chars_df_en_cz_final_with_selected_8_docs.tsv", sep = '\t')

In [3]:
df.head(8)

,hal_id,translation_id,sentence_indices,num_sentences,total_characters,source,total_spans,total_span_chars,span_char_ratio_pct
0,3,3,"[0, 1, 2, 3, 4, 5, 6, 7]",8,1785,Using data and artificial intelligence to try ...,42,600,33.61
1,7,7,"[24, 25, 26, 27, 28, 29, 30, 31]",8,1625,LNG investments hit record in 2019 & the bigge...,29,401,24.68
2,5,5,"[8, 9, 10, 11, 12, 13, 14, 15]",8,1575,Stem cells of 56 child cancer patients lost at...,29,431,27.37
3,13,13,"[32, 33, 34, 35, 36, 37, 38, 39]",8,1525,Jonathan Van Ness Just Hung Out With Nancy Pel...,34,551,36.13
4,18,18,"[48, 49, 50, 51, 52, 53, 54, 55]",8,1523,India's monsoon season has overrun by almost a...,40,680,44.65
5,17,17,"[40, 41, 42, 43, 44, 45, 46, 47]",8,1472,"""China has always been dedicated to resolving ...",36,664,45.11
6,6,6,"[16, 17, 18, 19, 20, 21, 22, 23]",8,1367,Three Scottish students named among Europe's b...,30,574,41.99
7,19,19,"[56, 57, 58, 59, 60, 61, 62, 63]",8,1356,"US sends troops, air defense systems to Saudi ...",35,457,33.70

In [4]:
first_4_text_list = (5,13, 18,17)

In [5]:
filtered_df_first_4 = df[df['hal_id'].isin(first_4_text_list)]
filtered_df_first_4

,hal_id,translation_id,sentence_indices,num_sentences,total_characters,source,total_spans,total_span_chars,span_char_ratio_pct
2,5,5,"[8, 9, 10, 11, 12, 13, 14, 15]",8,1575,Stem cells of 56 child cancer patients lost at...,29,431,27.37
3,13,13,"[32, 33, 34, 35, 36, 37, 38, 39]",8,1525,Jonathan Van Ness Just Hung Out With Nancy Pel...,34,551,36.13
4,18,18,"[48, 49, 50, 51, 52, 53, 54, 55]",8,1523,India's monsoon season has overrun by almost a...,40,680,44.65
5,17,17,"[40, 41, 42, 43, 44, 45, 46, 47]",8,1472,"""China has always been dedicated to resolving ...",36,664,45.11

In [8]:
import pandas as pd
path_csv = "../postedition_aligned_with_tokenized_offsets_df_en_cz_final_with_selected_8_docs.csv"
df_en_cz = pd.read_csv(path_csv)

**Get sentence length for each abstract**

In [9]:
def sentence_length_abstract(translations):
    sentences_length_of_abstract = []
    for idx, value in translations.items():
        sentences_length_of_abstract.append(len(value))
    return sentences_length_of_abstract

In [10]:
def get_sentences_len(first_4_text_list,df_en_cz, source_or_translation):
    import ast
    sentences_length_of_all_abstract = []
    
    if source_or_translation == "source":
        column_name = 'source'
        which_len = "document_length_source"
    else:
        column_name = 'translation'
        which_len = "document_length_translation"
    print(column_name)
    print(which_len)
    for abstract_id in first_4_text_list:
        row = filtered_df_first_4[filtered_df_first_4['translation_id'] == abstract_id]
        indices = ast.literal_eval(row["sentence_indices"].iloc[0])
        first_index = indices[0]
        last_index = indices[-1]
        print(abstract_id, first_index, last_index)

        sentences_length_of_each_abstract = sentence_length_abstract(df_en_cz.iloc[first_index:last_index+1][f"{column_name}"])
        sentences_length_of_all_abstract.append({
            "translation_id":abstract_id,
            "translation_starting_index": first_index,
            "translation_ending_index": last_index,
            f"{which_len}":sentences_length_of_each_abstract
        })
    return sentences_length_of_all_abstract

In [11]:
translation_sentences_length_of_all_abstract = get_sentences_len(first_4_text_list,df_en_cz, "translation")

translation_sentences_length_of_all_abstract[2]

translation
document_length_translation
5 8 15
13 32 39
18 48 55
17 40 47

{'translation_id': 18,
 'translation_starting_index': 48,
 'translation_ending_index': 55,
 'document_length_translation': [145, 288, 210, 112, 171, 105, 239, 253]}

In [13]:
print(sum(translation_sentences_length_of_all_abstract[2]["document_length_translation"]))

1523

**save the translation sentence lengths for each document**

In [ ]:
import json

with open("outputs/translation_sentences_length_all_4_xcomet_docs_en_cz.json", "w", encoding="utf-8") as f:
    json.dump(translation_sentences_length_of_all_abstract, f, ensure_ascii=False, indent=4)

# create updated annotaion  for text19823

In [369]:
import pandas as pd
path_csv = "/home/arafat/vscode/NN/postedition_aligned_with_tokenized_offsets_translator.csv"
df_translators = pd.read_csv(path_csv)

In [370]:
filtered_df_2.iloc[0]['sentence_indices']

'[506, 507, 508, 509, 510, 511, 512, 513, 514, 515]'

In [371]:
import json
xcomet_spans_translator_path = "/home/arafat/vscode/NN/all_entries_with_opcodes_translator.json"

with open(xcomet_spans_translator_path, 'r', encoding='utf-8') as f:
    xcomet_spans_translator = json.load(f)

In [372]:
xcomet_spans_translator[506]

{'index': 507,
 'source': 'Study on Acoustic Model Personalization in a Context of Collaborative Learning Constrained by Privacy Preservation',
 'translation': "Étude sur la personnalisation du modèle acoustique dans un contexte d'apprentissage collaboratif contraint par la préservation de la vie privée",
 'postedition': "Étude sur la personnalisation du modèle acoustique dans un contexte d'apprentissage collaboratif contraint par la protection de la vie privée",
 'relevant_words': ['préservation'],
 'difflib operations': [['equal', 0, 15, 0, 15],
  ['replace', 15, 16, 15, 16],
  ['equal', 16, 20, 16, 20]],
 'spans_each_mt': []}

In [165]:
xcomet_spans_translator[515]

{'index': 516,
 'source': 'Our approach applied to HMM/TDNN acoustic models improves quickly and significantly the ASR performance in terms of WER (for instance in one of our two evaluation datasets, from 14.84% to 13.45% with less than 5 min of speech per speaker).',
 'translation': "Notre approche appliquée aux modèles acoustiques HMM/TDNN améliore rapidement et significativement la performance ASR en termes de WER (par exemple, dans l'un de nos deux ensembles de données d'évaluation, de 14,84% à 13,45% avec moins de 5 minutes de discours par locuteur).",
 'postedition': "Notre approche appliquée aux modèles acoustiques HMM/TDNN améliore rapidement et significativement la performance de RAP en termes de taux d'erreur mot (par exemple, dans l'un de nos deux ensembles de données d'évaluation, de 14,84% à 13,45% avec moins de 5 minutes de discours par locuteur).",
 'relevant_words': ['ASR', 'WER'],
 'difflib operations': [['equal', 0, 13, 0, 13],
  ['replace', 13, 14, 13, 15],
  ['equal', 14, 17, 15, 18],
  ['replace', 17, 18, 18, 21],
  ['equal', 18, 42, 21, 45]],
 'spans_each_mt': [{'text': ['WER'],
   'confidence': 0.4459373652935028,
   'severity': 'minor',
   'start': 130,
   'end': 134,
   'check severity': ['minor']},
  {'text': ['de', 'discours'],
   'confidence': 0.40749210119247437,
   'severity': 'minor',
   'start': 248,
   'end': 260,
   'check severity': ['minor', 'minor']},
  {'text': ['locuteur).'],
   'confidence': 0.43727463483810425,
   'severity': 'minor',
   'start': 264,
   'end': 275,
   'check severity': ['minor', 'minor', 'minor']}]}

In [373]:
def sentence_length_abstract(translations):
    sentences_length_of_abstract = []
    for idx, value in translations.items():
        sentences_length_of_abstract.append(len(value))
    return sentences_length_of_abstract

In [374]:
sentences_length_of_abstract = sentence_length_abstract(df_translators.iloc[506:516]['translation'])
sentences_length_of_abstract

[143, 261, 270, 124, 145, 107, 124, 119, 243, 275]

In [168]:
import ast

In [375]:
spans = xcomet_spans_translator[506:516]
spans

[{'index': 507,
  'source': 'Study on Acoustic Model Personalization in a Context of Collaborative Learning Constrained by Privacy Preservation',
  'translation': "Étude sur la personnalisation du modèle acoustique dans un contexte d'apprentissage collaboratif contraint par la préservation de la vie privée",
  'postedition': "Étude sur la personnalisation du modèle acoustique dans un contexte d'apprentissage collaboratif contraint par la protection de la vie privée",
  'relevant_words': ['préservation'],
  'difflib operations': [['equal', 0, 15, 0, 15],
   ['replace', 15, 16, 15, 16],
   ['equal', 16, 20, 16, 20]],
  'spans_each_mt': []},
 {'index': 508,
  'source': 'This paper investigates different approaches in order to improve the performance of a speech recognition system for a given speaker by using no more than 5 min of speech from this speaker, and without exchanging data from other users/speakers.',
  'translation': "Cet article étudie différentes approches afin d'améliorer les performances d'un système de reconnaissance vocale pour un locuteur donné en utilisant au maximum 5 minutes de parole de ce locuteur, et sans échanger de données avec d'autres utilisateurs/locuteurs.",
  'postedition': "Cet article étudie différentes approches afin d'améliorer les performances d'un système de reconnaissance vocale pour un locuteur donné en utilisant au maximum 5 minutes de parole de ce locuteur, et sans échanger de données avec d'autres utilisateurs/locuteurs.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 37, 0, 37]],
  'spans_each_mt': [{'text': ['de', 'parole'],
    'confidence': 0.41538649797439575,
    'severity': 'minor',
    'start': 169,
    'end': 179,
    'check severity': ['minor', 'minor']},
   {'text': ['utilisateurs/locuteurs.'],
    'confidence': 0.40745866298675537,
    'severity': 'major',
    'start': 237,
    'end': 261,
    'check severity': ['minor', 'major', 'major', 'major']}]},
 {'index': 509,
  'source': 'Inspired by the federated learning paradigm, we consider speakers that have access to a personalized database of their own speech, learn an acoustic model and collaborate with other speakers in a network to improve their model.',
  'translation': "Inspirés par le paradigme de l'apprentissage fédéré, nous considérons des locuteurs qui ont accès à une base de données personnalisée de leur propre parole, apprennent un modèle acoustique et collaborent avec d'autres locuteurs dans un réseau pour améliorer leur modèle.",
  'postedition': "Inspirés par le paradigme de l'apprentissage fédéré, nous considérons des locuteurs qui ont accès à une base de données personnalisée de leur propre parole, apprennent un modèle acoustique et collaborent avec d'autres locuteurs dans un réseau pour améliorer leur modèle.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 40, 0, 40]],
  'spans_each_mt': [{'text': ['fédéré,'],
    'confidence': 0.3630404472351074,
    'severity': 'minor',
    'start': 44,
    'end': 52,
    'check severity': ['minor', 'minor']},
   {'text': ['considérons', 'des', 'locuteurs'],
    'confidence': 0.4282993674278259,
    'severity': 'major',
    'start': 57,
    'end': 83,
    'check severity': ['major', 'major', 'major', 'minor', 'major', 'major']},
   {'text': ['parole,'],
    'confidence': 0.46013161540031433,
    'severity': 'major',
    'start': 148,
    'end': 156,
    'check severity': ['major']},
   {'text': ['locuteurs'],
    'confidence': 0.3757043778896332,
    'severity': 'minor',
    'start': 217,
    'end': 227,
    'check severity': ['minor']}]},
 {'index': 510,
  'source': 'Several local personalizations are explored depending on how aggregation mechanisms are performed.',
  'translation': "Plusieurs personnalisations locales sont explorées en fonction de la manière dont les mécanismes d'agrégation sont exécutés.",
  'postedition': "Plusieurs personnalisations locales sont explorées en fonction de la manière dont les mécanismes d'agrégation sont exécutés.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 16, 0, 16]],
  'spans_each_mt': [{'text': ['personnalisations'],
    'confidence': 0.4520009458065033,
    'severity': 'minor',
    'start': 9,
    'end': 27,
    'check severity': ['minor', 'minor', 'minor']}]},
 {'index': 511,
  'source': "We study the impact of selecting, in an adaptive way, a subset of speakers's models based on a notion of similarity.",
  'translation': "Nous étudions l'impact de la sélection, de manière adaptative, d'un sous-ensemble de modèles de locuteurs sur la base d'une notion de similarité.",
  'postedition': "Nous étudions l'impact de la sélection, de manière adaptative, d'un sous-ensemble de modèles de locuteurs sur la base d'une notion de similarité.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 22, 0, 22]],
  'spans_each_mt': [{'text': ['modèles', 'de', 'locuteurs'],
    'confidence': 0.4452976882457733,
    'severity': 'minor',
    'start': 84,
    'end': 105,
    'check severity': ['minor', 'minor', 'minor', 'minor', 'minor']}]},
 {'index': 512,
  'source': 'We also investigate the effect of weighted averaging of fine-tuned and global models.',
  'translation': "Nous étudions également l'effet de la moyenne pondérée des modèles globaux et des modèles finement ajustés.",
  'postedition': "Nous étudions également l'effet de la moyenne pondérée des modèles globaux et des modèles finement ajustés.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 16, 0, 16]],
  'spans_each_mt': []},
 {'index': 513,
  'source': 'In our approach, only neural acoustic model parameters are exchanged and no audio data is exchanged.',
  'translation': "Dans notre approche, seuls les paramètres du modèle acoustique neuronal sont échangés et aucune donnée audio n'est échangée.",
  'postedition': "Dans notre approche, seuls les paramètres du modèle acoustique neuronal sont échangés et aucune donnée audio n'est échangée.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 18, 0, 18]],
  'spans_each_mt': []},
 {'index': 514,
  'source': 'By avoiding communicating their personal data, the proposed approach tends to preserve the privacy of speakers.',
  'translation': "En évitant de communiquer leurs données personnelles, l'approche proposée tend à préserver la vie privée des locuteurs.",
  'postedition': "En évitant de communiquer leurs données personnelles, l'approche proposée tend à protéger la vie privée des locuteurs.",
  'relevant_words': ['préserver'],
  'difflib operations': [['equal', 0, 11, 0, 11],
   ['replace', 11, 12, 11, 12],
   ['equal', 12, 17, 12, 17]],
  'spans_each_mt': [{'text': ['locuteurs.'],
    'confidence': 0.465664803981781,
    'severity': 'minor',
    'start': 108,
    'end': 119,
    'check severity': ['minor', 'minor']}]},
 {'index': 515,
  'source': 'Experiments conducted on the TEDLIUM 3 dataset show that the best improvement is given by averaging a subset of different acoustic models fine-tuned on several user datasets.',
  'translation': "Les expériences menées sur l'ensemble de données TEDLIUM 3 montrent que la meilleure amélioration est obtenue en faisant la moyenne d'un sous-ensemble de différents modèles acoustiques affinés sur plusieurs ensembles de données d'utilisateurs.",
  'postedition': "Les expériences menées sur l'ensemble de données TEDLIUM 3 montrent que la meilleure amélioration est obtenue en faisant la moyenne d'un sous-ensemble de différents modèles acoustiques affinés sur plusieurs ensembles de données d'utilisateurs.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 33, 0, 33]],
  'spans_each_mt': [{'text': ['affinés'],
    'confidence': 0.39296916127204895,
    'severity': 'minor',
    'start': 184,
    'end': 192,
    'check severity': ['minor']}]},
 {'index': 516,
  'source': 'Our approach applied to HMM/TDNN acoustic models improves quickly and significantly the ASR performance in terms of WER (for instance in one of our two evaluation datasets, from 14.84% to 13.45% with less than 5 min of speech per speaker).',
  'translation': "Notre approche appliquée aux modèles acoustiques HMM/TDNN améliore rapidement et significativement la performance ASR en termes de WER (par exemple, dans l'un de nos deux ensembles de données d'évaluation, de 14,84% à 13,45% avec moins de 5 minutes de discours par locuteur).",
  'postedition': "Notre approche appliquée aux modèles acoustiques HMM/TDNN améliore rapidement et significativement la performance de RAP en termes de taux d'erreur mot (par exemple, dans l'un de nos deux ensembles de données d'évaluation, de 14,84% à 13,45% avec moins de 5 minutes de discours par locuteur).",
  'relevant_words': ['ASR', 'WER'],
  'difflib operations': [['equal', 0, 13, 0, 13],
   ['replace', 13, 14, 13, 15],
   ['equal', 14, 17, 15, 18],
   ['replace', 17, 18, 18, 21],
   ['equal', 18, 42, 21, 45]],
  'spans_each_mt': [{'text': ['WER'],
    'confidence': 0.4459373652935028,
    'severity': 'minor',
    'start': 130,
    'end': 134,
    'check severity': ['minor']},
   {'text': ['de', 'discours'],
    'confidence': 0.40749210119247437,
    'severity': 'minor',
    'start': 248,
    'end': 260,
    'check severity': ['minor', 'minor']},
   {'text': ['locuteur).'],
    'confidence': 0.43727463483810425,
    'severity': 'minor',
    'start': 264,
    'end': 275,
    'check severity': ['minor', 'minor', 'minor']}]}]

In [376]:
spans_with_new_starts_ends_19823 = []
previous_sentence_length = 2

In [377]:
spans_with_new_starts_ends_19823

[]

In [378]:
spans_19823 = []
for span in spans:
    print(span)
    xcomet_span = span['spans_each_mt'] if 'spans_each_mt' in span else None
    if xcomet_span:
        span_list = []
        for index, each_span in enumerate(xcomet_span):
            span_list.append({
                'text': each_span['text'],
                'start': each_span['start'],
                'end': each_span['end'],
                'severity': each_span['severity'],
                'confidence': each_span['confidence']

            })
        spans_19823.append(span_list)
    else:
        spans_19823.append([])

{'index': 507, 'source': 'Study on Acoustic Model Personalization in a Context of Collaborative Learning Constrained by Privacy Preservation', 'translation': "Étude sur la personnalisation du modèle acoustique dans un contexte d'apprentissage collaboratif contraint par la préservation de la vie privée", 'postedition': "Étude sur la personnalisation du modèle acoustique dans un contexte d'apprentissage collaboratif contraint par la protection de la vie privée", 'relevant_words': ['préservation'], 'difflib operations': [['equal', 0, 15, 0, 15], ['replace', 15, 16, 15, 16], ['equal', 16, 20, 16, 20]], 'spans_each_mt': []}
{'index': 508, 'source': 'This paper investigates different approaches in order to improve the performance of a speech recognition system for a given speaker by using no more than 5 min of speech from this speaker, and without exchanging data from other users/speakers.', 'translation': "Cet article étudie différentes approches afin d'améliorer les performances d'un système de reconnaissance vocale pour un locuteur donné en utilisant au maximum 5 minutes de parole de ce locuteur, et sans échanger de données avec d'autres utilisateurs/locuteurs.", 'postedition': "Cet article étudie différentes approches afin d'améliorer les performances d'un système de reconnaissance vocale pour un locuteur donné en utilisant au maximum 5 minutes de parole de ce locuteur, et sans échanger de données avec d'autres utilisateurs/locuteurs.", 'relevant_words': [], 'difflib operations': [['equal', 0, 37, 0, 37]], 'spans_each_mt': [{'text': ['de', 'parole'], 'confidence': 0.41538649797439575, 'severity': 'minor', 'start': 169, 'end': 179, 'check severity': ['minor', 'minor']}, {'text': ['utilisateurs/locuteurs.'], 'confidence': 0.40745866298675537, 'severity': 'major', 'start': 237, 'end': 261, 'check severity': ['minor', 'major', 'major', 'major']}]}
{'index': 509, 'source': 'Inspired by the federated learning paradigm, we consider speakers that have access to a personalized database of their own speech, learn an acoustic model and collaborate with other speakers in a network to improve their model.', 'translation': "Inspirés par le paradigme de l'apprentissage fédéré, nous considérons des locuteurs qui ont accès à une base de données personnalisée de leur propre parole, apprennent un modèle acoustique et collaborent avec d'autres locuteurs dans un réseau pour améliorer leur modèle.", 'postedition': "Inspirés par le paradigme de l'apprentissage fédéré, nous considérons des locuteurs qui ont accès à une base de données personnalisée de leur propre parole, apprennent un modèle acoustique et collaborent avec d'autres locuteurs dans un réseau pour améliorer leur modèle.", 'relevant_words': [], 'difflib operations': [['equal', 0, 40, 0, 40]], 'spans_each_mt': [{'text': ['fédéré,'], 'confidence': 0.3630404472351074, 'severity': 'minor', 'start': 44, 'end': 52, 'check severity': ['minor', 'minor']}, {'text': ['considérons', 'des', 'locuteurs'], 'confidence': 0.4282993674278259, 'severity': 'major', 'start': 57, 'end': 83, 'check severity': ['major', 'major', 'major', 'minor', 'major', 'major']}, {'text': ['parole,'], 'confidence': 0.46013161540031433, 'severity': 'major', 'start': 148, 'end': 156, 'check severity': ['major']}, {'text': ['locuteurs'], 'confidence': 0.3757043778896332, 'severity': 'minor', 'start': 217, 'end': 227, 'check severity': ['minor']}]}
{'index': 510, 'source': 'Several local personalizations are explored depending on how aggregation mechanisms are performed.', 'translation': "Plusieurs personnalisations locales sont explorées en fonction de la manière dont les mécanismes d'agrégation sont exécutés.", 'postedition': "Plusieurs personnalisations locales sont explorées en fonction de la manière dont les mécanismes d'agrégation sont exécutés.", 'relevant_words': [], 'difflib operations': [['equal', 0, 16, 0, 16]], 'spans_each_mt': [{'text': ['personnalisations'], 'confidence': 0.4520009458065033, 'severity': 'minor', 'start': 9, 'end': 27, 'check severity': ['minor', 'minor', 'minor']}]}
{'index': 511, 'source': "We study the impact of selecting, in an adaptive way, a subset of speakers's models based on a notion of similarity.", 'translation': "Nous étudions l'impact de la sélection, de manière adaptative, d'un sous-ensemble de modèles de locuteurs sur la base d'une notion de similarité.", 'postedition': "Nous étudions l'impact de la sélection, de manière adaptative, d'un sous-ensemble de modèles de locuteurs sur la base d'une notion de similarité.", 'relevant_words': [], 'difflib operations': [['equal', 0, 22, 0, 22]], 'spans_each_mt': [{'text': ['modèles', 'de', 'locuteurs'], 'confidence': 0.4452976882457733, 'severity': 'minor', 'start': 84, 'end': 105, 'check severity': ['minor', 'minor', 'minor', 'minor', 'minor']}]}
{'index': 512, 'source': 'We also investigate the effect of weighted averaging of fine-tuned and global models.', 'translation': "Nous étudions également l'effet de la moyenne pondérée des modèles globaux et des modèles finement ajustés.", 'postedition': "Nous étudions également l'effet de la moyenne pondérée des modèles globaux et des modèles finement ajustés.", 'relevant_words': [], 'difflib operations': [['equal', 0, 16, 0, 16]], 'spans_each_mt': []}
{'index': 513, 'source': 'In our approach, only neural acoustic model parameters are exchanged and no audio data is exchanged.', 'translation': "Dans notre approche, seuls les paramètres du modèle acoustique neuronal sont échangés et aucune donnée audio n'est échangée.", 'postedition': "Dans notre approche, seuls les paramètres du modèle acoustique neuronal sont échangés et aucune donnée audio n'est échangée.", 'relevant_words': [], 'difflib operations': [['equal', 0, 18, 0, 18]], 'spans_each_mt': []}
{'index': 514, 'source': 'By avoiding communicating their personal data, the proposed approach tends to preserve the privacy of speakers.', 'translation': "En évitant de communiquer leurs données personnelles, l'approche proposée tend à préserver la vie privée des locuteurs.", 'postedition': "En évitant de communiquer leurs données personnelles, l'approche proposée tend à protéger la vie privée des locuteurs.", 'relevant_words': ['préserver'], 'difflib operations': [['equal', 0, 11, 0, 11], ['replace', 11, 12, 11, 12], ['equal', 12, 17, 12, 17]], 'spans_each_mt': [{'text': ['locuteurs.'], 'confidence': 0.465664803981781, 'severity': 'minor', 'start': 108, 'end': 119, 'check severity': ['minor', 'minor']}]}
{'index': 515, 'source': 'Experiments conducted on the TEDLIUM 3 dataset show that the best improvement is given by averaging a subset of different acoustic models fine-tuned on several user datasets.', 'translation': "Les expériences menées sur l'ensemble de données TEDLIUM 3 montrent que la meilleure amélioration est obtenue en faisant la moyenne d'un sous-ensemble de différents modèles acoustiques affinés sur plusieurs ensembles de données d'utilisateurs.", 'postedition': "Les expériences menées sur l'ensemble de données TEDLIUM 3 montrent que la meilleure amélioration est obtenue en faisant la moyenne d'un sous-ensemble de différents modèles acoustiques affinés sur plusieurs ensembles de données d'utilisateurs.", 'relevant_words': [], 'difflib operations': [['equal', 0, 33, 0, 33]], 'spans_each_mt': [{'text': ['affinés'], 'confidence': 0.39296916127204895, 'severity': 'minor', 'start': 184, 'end': 192, 'check severity': ['minor']}]}
{'index': 516, 'source': 'Our approach applied to HMM/TDNN acoustic models improves quickly and significantly the ASR performance in terms of WER (for instance in one of our two evaluation datasets, from 14.84% to 13.45% with less than 5 min of speech per speaker).', 'translation': "Notre approche appliquée aux modèles acoustiques HMM/TDNN améliore rapidement et significativement la performance ASR en termes de WER (par exemple, dans l'un de nos deux ensembles de données d'évaluation, de 14,84% à 13,45% avec moins de 5 minutes de discours par locuteur).", 'postedition': "Notre approche appliquée aux modèles acoustiques HMM/TDNN améliore rapidement et significativement la performance de RAP en termes de taux d'erreur mot (par exemple, dans l'un de nos deux ensembles de données d'évaluation, de 14,84% à 13,45% avec moins de 5 minutes de discours par locuteur).", 'relevant_words': ['ASR', 'WER'], 'difflib operations': [['equal', 0, 13, 0, 13], ['replace', 13, 14, 13, 15], ['equal', 14, 17, 15, 18], ['replace', 17, 18, 18, 21], ['equal', 18, 42, 21, 45]], 'spans_each_mt': [{'text': ['WER'], 'confidence': 0.4459373652935028, 'severity': 'minor', 'start': 130, 'end': 134, 'check severity': ['minor']}, {'text': ['de', 'discours'], 'confidence': 0.40749210119247437, 'severity': 'minor', 'start': 248, 'end': 260, 'check severity': ['minor', 'minor']}, {'text': ['locuteur).'], 'confidence': 0.43727463483810425, 'severity': 'minor', 'start': 264, 'end': 275, 'check severity': ['minor', 'minor', 'minor']}]}

In [379]:
spans_19823

[[],
 [{'text': ['de', 'parole'],
   'start': 169,
   'end': 179,
   'severity': 'minor',
   'confidence': 0.41538649797439575},
  {'text': ['utilisateurs/locuteurs.'],
   'start': 237,
   'end': 261,
   'severity': 'major',
   'confidence': 0.40745866298675537}],
 [{'text': ['fédéré,'],
   'start': 44,
   'end': 52,
   'severity': 'minor',
   'confidence': 0.3630404472351074},
  {'text': ['considérons', 'des', 'locuteurs'],
   'start': 57,
   'end': 83,
   'severity': 'major',
   'confidence': 0.4282993674278259},
  {'text': ['parole,'],
   'start': 148,
   'end': 156,
   'severity': 'major',
   'confidence': 0.46013161540031433},
  {'text': ['locuteurs'],
   'start': 217,
   'end': 227,
   'severity': 'minor',
   'confidence': 0.3757043778896332}],
 [{'text': ['personnalisations'],
   'start': 9,
   'end': 27,
   'severity': 'minor',
   'confidence': 0.4520009458065033}],
 [{'text': ['modèles', 'de', 'locuteurs'],
   'start': 84,
   'end': 105,
   'severity': 'minor',
   'confidence': 0.4452976882457733}],
 [],
 [],
 [{'text': ['locuteurs.'],
   'start': 108,
   'end': 119,
   'severity': 'minor',
   'confidence': 0.465664803981781}],
 [{'text': ['affinés'],
   'start': 184,
   'end': 192,
   'severity': 'minor',
   'confidence': 0.39296916127204895}],
 [{'text': ['WER'],
   'start': 130,
   'end': 134,
   'severity': 'minor',
   'confidence': 0.4459373652935028},
  {'text': ['de', 'discours'],
   'start': 248,
   'end': 260,
   'severity': 'minor',
   'confidence': 0.40749210119247437},
  {'text': ['locuteur).'],
   'start': 264,
   'end': 275,
   'severity': 'minor',
   'confidence': 0.43727463483810425}]]

In [380]:
for index, spans in enumerate(spans_19823):
    if index == 0:
        spans_title = []
        for span in spans:
            if span['start'] == 0:
                start = 0
            else:
                start = span['start'] + 1
            spans_title.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'],
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_19823.append(spans_title)

    # elif index == 1:
    #     #sentences
    #     spans_each_sentence = []
    #     for span in spans:
    #         spans_each_sentence.append({
    #                             'text': span['text'],
    #                             'startnew': span['start'] + 1 +2,
    #                             'endnew': span['end']
                                
    #                             })

    #     spans_with_new_starts_ends.append(spans_each_sentence)
    elif index == 1:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1]
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        
        for ind,span in enumerate(spans):
            print("index in index 1: ", ind)
            print("spans in index 1: ", span)
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
           
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })
        spans_with_new_starts_ends_19823.append(spans_each_sentence)

    else:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1] + 1
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        for ind,span in enumerate(spans):
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_19823.append(spans_each_sentence)

spans_with_new_starts_ends_19823

index is:  1  and previous sentence lenght:  145
index in index 1:  0
spans in index 1:  {'text': ['de', 'parole'], 'start': 169, 'end': 179, 'severity': 'minor', 'confidence': 0.41538649797439575}
index in index 1:  1
spans in index 1:  {'text': ['utilisateurs/locuteurs.'], 'start': 237, 'end': 261, 'severity': 'major', 'confidence': 0.40745866298675537}
index is:  2  and previous sentence lenght:  407
index is:  3  and previous sentence lenght:  678
index is:  4  and previous sentence lenght:  803
index is:  5  and previous sentence lenght:  949
index is:  6  and previous sentence lenght:  1057
index is:  7  and previous sentence lenght:  1182
index is:  8  and previous sentence lenght:  1302
index is:  9  and previous sentence lenght:  1546

[[],
 [{'text': ['de', 'parole'],
   'startnew': 315,
   'endnew': 324,
   'severity': 'minor',
   'confidence': 0.41538649797439575},
  {'text': ['utilisateurs/locuteurs.'],
   'startnew': 383,
   'endnew': 406,
   'severity': 'major',
   'confidence': 0.40745866298675537}],
 [{'text': ['fédéré,'],
   'startnew': 452,
   'endnew': 459,
   'severity': 'minor',
   'confidence': 0.3630404472351074},
  {'text': ['considérons', 'des', 'locuteurs'],
   'startnew': 465,
   'endnew': 490,
   'severity': 'major',
   'confidence': 0.4282993674278259},
  {'text': ['parole,'],
   'startnew': 556,
   'endnew': 563,
   'severity': 'major',
   'confidence': 0.46013161540031433},
  {'text': ['locuteurs'],
   'startnew': 625,
   'endnew': 634,
   'severity': 'minor',
   'confidence': 0.3757043778896332}],
 [{'text': ['personnalisations'],
   'startnew': 688,
   'endnew': 705,
   'severity': 'minor',
   'confidence': 0.4520009458065033}],
 [{'text': ['modèles', 'de', 'locuteurs'],
   'startnew': 888,
   'endnew': 908,
   'severity': 'minor',
   'confidence': 0.4452976882457733}],
 [],
 [],
 [{'text': ['locuteurs.'],
   'startnew': 1291,
   'endnew': 1301,
   'severity': 'minor',
   'confidence': 0.465664803981781}],
 [{'text': ['affinés'],
   'startnew': 1487,
   'endnew': 1494,
   'severity': 'minor',
   'confidence': 0.39296916127204895}],
 [{'text': ['WER'],
   'startnew': 1677,
   'endnew': 1680,
   'severity': 'minor',
   'confidence': 0.4459373652935028},
  {'text': ['de', 'discours'],
   'startnew': 1795,
   'endnew': 1806,
   'severity': 'minor',
   'confidence': 0.40749210119247437},
  {'text': ['locuteur).'],
   'startnew': 1811,
   'endnew': 1821,
   'severity': 'minor',
   'confidence': 0.43727463483810425}]]

In [381]:
text19823[1795:1806]

'de discours'

In [382]:
result_19823 = [
    (d['startnew'], d['endnew'], idx + 1, d['severity'], round(d['confidence'], 3))
    for idx, inner_list in enumerate(spans_with_new_starts_ends_19823)
    for d in inner_list
]
result_19823

[(315, 324, 2, 'minor', 0.415),
 (383, 406, 2, 'major', 0.407),
 (452, 459, 3, 'minor', 0.363),
 (465, 490, 3, 'major', 0.428),
 (556, 563, 3, 'major', 0.46),
 (625, 634, 3, 'minor', 0.376),
 (688, 705, 4, 'minor', 0.452),
 (888, 908, 5, 'minor', 0.445),
 (1291, 1301, 8, 'minor', 0.466),
 (1487, 1494, 9, 'minor', 0.393),
 (1677, 1680, 10, 'minor', 0.446),
 (1795, 1806, 10, 'minor', 0.407),
 (1811, 1821, 10, 'minor', 0.437)]

In [385]:
len(result_19823)

13

## for text text882

In [384]:
filtered_df_2.iloc[1]['sentence_indices']

'[1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060]'

In [386]:
def sentence_length_abstract(translations):
    sentences_length_of_abstract = []
    for idx, value in translations.items():
        sentences_length_of_abstract.append(len(value))
    return sentences_length_of_abstract
sentences_length_of_abstract = sentence_length_abstract(df_translators.iloc[1053:1061]['translation'])
sentences_length_of_abstract

[177, 333, 214, 149, 188, 85, 174, 233]

In [387]:
spans = xcomet_spans_translator[1053:1061]
spans

[{'index': 1054,
  'source': 'Between History and Natural Language Processing: Study, Enrichment and Online Publication of French Parliamentary Debates of the Early Third Republic (1881-1899)',
  'translation': 'Entre histoire et traitement du langage naturel: Étude, enrichissement et publication en ligne des débats parlementaires français du début de la Troisième République (1881-1899)',
  'postedition': 'Entre histoire et traitement automatique des langues : Étude, enrichissement et publication en ligne des débats parlementaires français du début de la Troisième République (1881-1899)',
  'relevant_words': ['du', 'langage', 'naturel:'],
  'difflib operations': [['equal', 0, 4, 0, 4],
   ['replace', 4, 7, 4, 8],
   ['equal', 7, 24, 8, 25]],
  'spans_each_mt': [{'text': ['traitement', 'du'],
    'confidence': 0.4411212205886841,
    'severity': 'minor',
    'start': 17,
    'end': 31,
    'check severity': ['minor', 'minor']},
   {'text': ['naturel:'],
    'confidence': 0.43487218022346497,
    'severity': 'minor',
    'start': 39,
    'end': 48,
    'check severity': ['minor']}]},
 {'index': 1055,
  'source': "We present the AGODA (Analyse sémantique et Graphes relationnels pour l'Ouverture des Débats à l'Assemblée nationale) project, which aims to create a platform for consulting and exploring digitised French parliamentary debates (1881-1940) available in the digital library of the National Library of France.",
  'translation': 'Nous présentons le projet AGODA (Analyse sémantique et Graphes relationnels pour l’Ouverture des Débats à l’Assemblée nationale), qui vise à créer une plateforme de consultation et d’exploration des débats parlementaires français numérisés (1881-1940) disponible dans la bibliothèque numérique de la Bibliothèque nationale de France.',
  'postedition': 'Nous présentons le projet AGODA (Analyse sémantique et Graphes relationnels pour l’Ouverture des Débats à l’Assemblée nationale), qui vise à créer une plateforme de consultation et d’exploration des débats parlementaires français numérisés (1881-1940) disponible dans la bibliothèque numérique de la Bibliothèque Nationale de France.',
  'relevant_words': ['nationale'],
  'difflib operations': [['equal', 0, 41, 0, 41],
   ['replace', 41, 42, 41, 42],
   ['equal', 42, 44, 42, 44]],
  'spans_each_mt': [{'text': ['Graphes'],
    'confidence': 0.4058500826358795,
    'severity': 'minor',
    'start': 54,
    'end': 62,
    'check severity': ['minor']},
   {'text': ['l’Ouverture', 'des', 'Débats'],
    'confidence': 0.40631169080734253,
    'severity': 'minor',
    'start': 80,
    'end': 103,
    'check severity': ['minor',
     'minor',
     'minor',
     'minor',
     'minor',
     'minor']}]},
 {'index': 1056,
  'source': 'This project brings together historians and NLP specialists: parliamentary debates are indeed an essential source for French history of the contemporary period, but also for linguistics.',
  'translation': 'Ce projet rassemble des historiens et des spécialistes de la PNL: les débats parlementaires sont en effet une source essentielle pour l’histoire française de l’époque contemporaine, mais aussi pour la linguistique.',
  'postedition': 'Ce projet rassemble des historiens et des spécialistes du TAL : les débats parlementaires sont en effet une source essentielle pour l’histoire française de l’époque contemporaine, mais aussi pour la linguistique.',
  'relevant_words': ['de', 'la', 'PNL:'],
  'difflib operations': [['equal', 0, 8, 0, 8],
   ['replace', 8, 11, 8, 11],
   ['equal', 11, 31, 11, 31]],
  'spans_each_mt': [{'text': ['de', 'la', 'PNL:'],
    'confidence': 0.40684041380882263,
    'severity': 'minor',
    'start': 54,
    'end': 65,
    'check severity': ['minor', 'minor', 'minor']}]},
 {'index': 1057,
  'source': 'This project therefore aims to produce a corpus of texts that can be easily exploited with computational methods, and that respect the TEI standard.',
  'translation': 'Ce projet vise donc à produire un corpus de textes qui peuvent être facilement exploités avec des méthodes de calcul, et qui respectent la norme TEI.',
  'postedition': 'Ce projet vise donc à produire un corpus de textes qui peuvent être facilement exploités avec des méthodes de calcul, et qui respectent la norme TEI.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 26, 0, 26]],
  'spans_each_mt': []},
 {'index': 1058,
  'source': 'Ancient parliamentary debates are also an excellent case study for the development and application of tools for publishing and exploring large historical corpora.',
  'translation': 'Les débats parlementaires anciens constituent également une excellente étude de cas pour le développement et l’application d’outils d’édition et d’exploration de grands corpus historiques.',
  'postedition': 'Les débats parlementaires anciens constituent également une excellente étude de cas pour le développement et l’application d’outils d’édition et d’exploration de grands corpus historiques.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 24, 0, 24]],
  'spans_each_mt': []},
 {'index': 1059,
  'source': 'In this paper, we present the steps necessary to produce such a corpus.',
  'translation': 'Dans cet article, nous présentons les étapes nécessaires pour produire un tel corpus.',
  'postedition': 'Dans cet article, nous présentons les étapes nécessaires pour produire un tel corpus.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 13, 0, 13]],
  'spans_each_mt': [{'text': ['corpus.'],
    'confidence': 0.41196292638778687,
    'severity': 'minor',
    'start': 77,
    'end': 85,
    'check severity': ['minor']}]},
 {'index': 1060,
  'source': 'We detail the processing and publication chain of these documents, in particular by mentioning the problems linked to the extraction of texts from digitised images.',
  'translation': 'Nous détaillons la chaîne de traitement et de publication de ces documents, notamment en mentionnant les problèmes liés à l’extraction de textes à partir d’images numérisées.',
  'postedition': 'Nous détaillons la chaîne de traitement et de publication de ces documents, notamment en mentionnant les problèmes liés à l’extraction de textes à partir d’images numérisées.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 26, 0, 26]],
  'spans_each_mt': []},
 {'index': 1061,
  'source': 'We also introduce the first analyses that we have carried out on this corpus with "bag-of-words" techniques not too sensitive to OCR quality (namely topic modelling and word embedding).',
  'translation': 'Nous introduisons également les premières analyses que nous avons effectuées sur ce corpus avec des techniques de «bag-of-words» pas trop sensibles à la qualité de l’OCR (à savoir la modélisation des sujets et l’intégration de mots).',
  'postedition': 'Nous introduisons également les premières analyses que nous avons effectuées sur ce corpus avec des techniques de « sac-de-mots » pas trop sensibles à la qualité de l’OCR (à savoir la modélisation des sujets et le plongement lexical).',
  'relevant_words': ['«bag-of-words»', 'l’intégration', 'de', 'mots).'],
  'difflib operations': [['equal', 0, 17, 0, 17],
   ['replace', 17, 18, 17, 20],
   ['equal', 18, 33, 20, 35],
   ['replace', 33, 36, 35, 38]],
  'spans_each_mt': [{'text': ['de', '«bag-of-words»', 'pas'],
    'confidence': 0.4402514100074768,
    'severity': 'minor',
    'start': 110,
    'end': 132,
    'check severity': ['minor',
     'minor',
     'minor',
     'minor',
     'minor',
     'minor',
     'minor',
     'minor']},
   {'text': ['de', 'l’OCR'],
    'confidence': 0.40234220027923584,
    'severity': 'minor',
    'start': 160,
    'end': 169,
    'check severity': ['minor', 'minor']},
   {'text': ['des', 'sujets'],
    'confidence': 0.4374266564846039,
    'severity': 'minor',
    'start': 195,
    'end': 206,
    'check severity': ['minor', 'minor']},
   {'text': ['l’intégration'],
    'confidence': 0.42315059900283813,
    'severity': 'minor',
    'start': 209,
    'end': 223,
    'check severity': ['minor']},
   {'text': ['mots).'],
    'confidence': 0.3855477571487427,
    'severity': 'minor',
    'start': 226,
    'end': 233,
    'check severity': ['minor']}]}]

In [388]:
second_sentene = spans[1]['translation']
len(second_sentene)

333

In [389]:
second_sentene[313:322]

'nationale'

In [390]:
spans_with_new_starts_ends_882 = []
previous_sentence_length = 2

In [391]:
spans_882 = []
for span in spans:
    #print(span)
    xcomet_span = span['spans_each_mt'] if 'spans_each_mt' in span else None
    if xcomet_span:
        span_list = []
        for index, each_span in enumerate(xcomet_span):
            span_list.append({
                'text': each_span['text'],
                'start': each_span['start'],
                'end': each_span['end'],
                'severity': each_span['severity'],
                'confidence': each_span['confidence']

            })
        spans_882.append(span_list)
    else:
        spans_882.append([])

In [392]:
spans_882

[[{'text': ['traitement', 'du'],
   'start': 17,
   'end': 31,
   'severity': 'minor',
   'confidence': 0.4411212205886841},
  {'text': ['naturel:'],
   'start': 39,
   'end': 48,
   'severity': 'minor',
   'confidence': 0.43487218022346497}],
 [{'text': ['Graphes'],
   'start': 54,
   'end': 62,
   'severity': 'minor',
   'confidence': 0.4058500826358795},
  {'text': ['l’Ouverture', 'des', 'Débats'],
   'start': 80,
   'end': 103,
   'severity': 'minor',
   'confidence': 0.40631169080734253}],
 [{'text': ['de', 'la', 'PNL:'],
   'start': 54,
   'end': 65,
   'severity': 'minor',
   'confidence': 0.40684041380882263}],
 [],
 [],
 [{'text': ['corpus.'],
   'start': 77,
   'end': 85,
   'severity': 'minor',
   'confidence': 0.41196292638778687}],
 [],
 [{'text': ['de', '«bag-of-words»', 'pas'],
   'start': 110,
   'end': 132,
   'severity': 'minor',
   'confidence': 0.4402514100074768},
  {'text': ['de', 'l’OCR'],
   'start': 160,
   'end': 169,
   'severity': 'minor',
   'confidence': 0.40234220027923584},
  {'text': ['des', 'sujets'],
   'start': 195,
   'end': 206,
   'severity': 'minor',
   'confidence': 0.4374266564846039},
  {'text': ['l’intégration'],
   'start': 209,
   'end': 223,
   'severity': 'minor',
   'confidence': 0.42315059900283813},
  {'text': ['mots).'],
   'start': 226,
   'end': 233,
   'severity': 'minor',
   'confidence': 0.3855477571487427}]]

In [393]:
for index, spans in enumerate(spans_882):
    if index == 0:
        spans_title = []
        for span in spans:
            if span['start'] == 0:
                start = 0
            else:
                start = span['start'] + 1
            spans_title.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'],
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_882.append(spans_title)

    # elif index == 1:
    #     #sentences
    #     spans_each_sentence = []
    #     for span in spans:
    #         spans_each_sentence.append({
    #                             'text': span['text'],
    #                             'startnew': span['start'] + 1 +2,
    #                             'endnew': span['end']
                                
    #                             })

    #     spans_with_new_starts_ends.append(spans_each_sentence)
    elif index == 1:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1]
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        
        for ind,span in enumerate(spans):
            print("index in index 1: ", ind)
            print("spans in index 1: ", span)
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
           
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })
        spans_with_new_starts_ends_882.append(spans_each_sentence)

    else:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1] + 1
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        for ind,span in enumerate(spans):
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_882.append(spans_each_sentence)

spans_with_new_starts_ends_882

index is:  1  and previous sentence lenght:  179
index in index 1:  0
spans in index 1:  {'text': ['Graphes'], 'start': 54, 'end': 62, 'severity': 'minor', 'confidence': 0.4058500826358795}
index in index 1:  1
spans in index 1:  {'text': ['l’Ouverture', 'des', 'Débats'], 'start': 80, 'end': 103, 'severity': 'minor', 'confidence': 0.40631169080734253}
index is:  2  and previous sentence lenght:  513
index is:  3  and previous sentence lenght:  728
index is:  4  and previous sentence lenght:  878
index is:  5  and previous sentence lenght:  1067
index is:  6  and previous sentence lenght:  1153
index is:  7  and previous sentence lenght:  1328

[[{'text': ['traitement', 'du'],
   'startnew': 18,
   'endnew': 31,
   'severity': 'minor',
   'confidence': 0.4411212205886841},
  {'text': ['naturel:'],
   'startnew': 40,
   'endnew': 48,
   'severity': 'minor',
   'confidence': 0.43487218022346497}],
 [{'text': ['Graphes'],
   'startnew': 234,
   'endnew': 241,
   'severity': 'minor',
   'confidence': 0.4058500826358795},
  {'text': ['l’Ouverture', 'des', 'Débats'],
   'startnew': 260,
   'endnew': 282,
   'severity': 'minor',
   'confidence': 0.40631169080734253}],
 [{'text': ['de', 'la', 'PNL:'],
   'startnew': 568,
   'endnew': 578,
   'severity': 'minor',
   'confidence': 0.40684041380882263}],
 [],
 [],
 [{'text': ['corpus.'],
   'startnew': 1145,
   'endnew': 1152,
   'severity': 'minor',
   'confidence': 0.41196292638778687}],
 [],
 [{'text': ['de', '«bag-of-words»', 'pas'],
   'startnew': 1439,
   'endnew': 1460,
   'severity': 'minor',
   'confidence': 0.4402514100074768},
  {'text': ['de', 'l’OCR'],
   'startnew': 1489,
   'endnew': 1497,
   'severity': 'minor',
   'confidence': 0.40234220027923584},
  {'text': ['des', 'sujets'],
   'startnew': 1524,
   'endnew': 1534,
   'severity': 'minor',
   'confidence': 0.4374266564846039},
  {'text': ['l’intégration'],
   'startnew': 1538,
   'endnew': 1551,
   'severity': 'minor',
   'confidence': 0.42315059900283813},
  {'text': ['mots).'],
   'startnew': 1555,
   'endnew': 1561,
   'severity': 'minor',
   'confidence': 0.3855477571487427}]]

In [394]:
result_882 = [
    (d['startnew'], d['endnew'], idx + 1, d['severity'], round(d['confidence'], 3))
    for idx, inner_list in enumerate(spans_with_new_starts_ends_882)
    for d in inner_list
]
result_882

[(18, 31, 1, 'minor', 0.441),
 (40, 48, 1, 'minor', 0.435),
 (234, 241, 2, 'minor', 0.406),
 (260, 282, 2, 'minor', 0.406),
 (568, 578, 3, 'minor', 0.407),
 (1145, 1152, 6, 'minor', 0.412),
 (1439, 1460, 8, 'minor', 0.44),
 (1489, 1497, 8, 'minor', 0.402),
 (1524, 1534, 8, 'minor', 0.437),
 (1538, 1551, 8, 'minor', 0.423),
 (1555, 1561, 8, 'minor', 0.386)]

In [395]:
result_882.insert(4, (492,501,2,"major",0.46))
result_882

[(18, 31, 1, 'minor', 0.441),
 (40, 48, 1, 'minor', 0.435),
 (234, 241, 2, 'minor', 0.406),
 (260, 282, 2, 'minor', 0.406),
 (492, 501, 2, 'major', 0.46),
 (568, 578, 3, 'minor', 0.407),
 (1145, 1152, 6, 'minor', 0.412),
 (1439, 1460, 8, 'minor', 0.44),
 (1489, 1497, 8, 'minor', 0.402),
 (1524, 1534, 8, 'minor', 0.437),
 (1538, 1551, 8, 'minor', 0.423),
 (1555, 1561, 8, 'minor', 0.386)]

In [396]:
len(result_882)

12

In [397]:
text882[18:31]

'traitement du'

In [398]:
text882[492:501]

'nationale'

In [399]:
text882[40:48]

'naturel:'

In [400]:
text882[234:241]

'Graphes'

In [401]:
len(result_882)

12

In [402]:
text882[1555:1561]

'mots).'

## text19057

In [403]:
filtered_df_2.iloc[2]['sentence_indices']

'[1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643]'

In [404]:
sentences_length_of_abstract = sentence_length_abstract(df_translators.iloc[1635:1644]['translation'])
sentences_length_of_abstract

[120, 132, 124, 198, 254, 156, 106, 196, 255]

In [405]:
text19057

"Amélioration de l'extraction d'information sur des documents commerciaux avec des tâches de pré-entraînement spécifiques\n\nLes modèles de langage basés sur des transformateurs sont largement utilisés dans les tâches liées au traitement du langage naturel. Grâce à leur pré-entraînement, ils ont été adaptés avec succès à l'extraction d'informations dans les documents commerciaux. Cependant, la plupart des tâches de pré-entraînement proposées dans la littérature pour les documents commerciaux sont trop génériques et ne permettent pas d'apprendre des structures plus complexes. Dans cet article, nous utilisons LayoutLM, un modèle de langage pré-entraîné sur une collection de documents commerciaux, et introduisons deux nouvelles tâches de pré-entraînement qui améliorent encore sa capacité à extraire des informations pertinentes. La première vise à mieux comprendre la mise en page complexe des documents, et la seconde se concentre sur les valeurs numériques et leur ordre de grandeur. Ces tâches obligent le modèle à apprendre des représentations mieux contextualisées des documents scannés. Nous introduisons également un nouvel algorithme de post-traitement pour décoder les étiquettes BIESO dans l'extraction d'informations, qui donne de meilleurs résultats avec les entités complexes. Notre méthode améliore considérablement les performances d'extraction sur les ensembles de données publics (de 93,88 à 95,50 pour le score F1) et privés (de 84,35 à 84,84 pour le score F1) composés de reçus de dépenses, de factures et de bons de commande."

In [406]:
spans = xcomet_spans_translator[1635:1644]
spans

[{'index': 1636,
  'source': 'Improving Information Extraction on Business Documents with Specific Pre-Training Tasks',
  'translation': "Amélioration de l'extraction d'information sur des documents commerciaux avec des tâches de pré-entraînement spécifiques",
  'postedition': "Amélioration de l'extraction d'information sur des documents commerciaux avec des tâches de pré-entraînement spécifiques",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 14, 0, 14]],
  'spans_each_mt': [{'text': ['Amélioration'],
    'confidence': 0.45616263151168823,
    'severity': 'minor',
    'start': 0,
    'end': 12,
    'check severity': ['minor']},
   {'text': ["l'extraction", "d'information"],
    'confidence': 0.4250956177711487,
    'severity': 'minor',
    'start': 15,
    'end': 42,
    'check severity': ['minor', 'minor', 'minor']},
   {'text': ['commerciaux'],
    'confidence': 0.42627623677253723,
    'severity': 'minor',
    'start': 60,
    'end': 72,
    'check severity': ['minor']},
   {'text': ['pré-entraînement'],
    'confidence': 0.4056091904640198,
    'severity': 'minor',
    'start': 91,
    'end': 108,
    'check severity': ['minor']}]},
 {'index': 1637,
  'source': 'Transformer-based Language Models are widely used in Natural Language Processing related tasks.',
  'translation': 'Les modèles de langage basés sur des transformateurs sont largement utilisés dans les tâches liées au traitement du langage naturel.',
  'postedition': 'Les modèles de langue basés sur des transformateurs sont largement utilisés dans les tâches liées au traitement automatique des langues.',
  'relevant_words': ['langage', 'du', 'langage', 'naturel.'],
  'difflib operations': [['equal', 0, 3, 0, 3],
   ['replace', 3, 4, 3, 4],
   ['equal', 4, 17, 4, 17],
   ['replace', 17, 20, 17, 20]],
  'spans_each_mt': [{'text': ['transformateurs'],
    'confidence': 0.41461944580078125,
    'severity': 'minor',
    'start': 36,
    'end': 52,
    'check severity': ['minor']}]},
 {'index': 1638,
  'source': 'Thanks to their pre-training, they have been successfully adapted to Information Extraction in business documents.',
  'translation': "Grâce à leur pré-entraînement, ils ont été adaptés avec succès à l'extraction d'informations dans les documents commerciaux.",
  'postedition': "Grâce à leur pré-entraînement, ils ont été adaptés avec succès à l'extraction d'informations dans les documents commerciaux.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 17, 0, 17]],
  'spans_each_mt': [{'text': ['pré-entraînement,'],
    'confidence': 0.4208151400089264,
    'severity': 'minor',
    'start': 12,
    'end': 30,
    'check severity': ['minor', 'minor']},
   {'text': ['été', 'adaptés'],
    'confidence': 0.4211413860321045,
    'severity': 'minor',
    'start': 38,
    'end': 50,
    'check severity': ['minor', 'minor']},
   {'text': ["l'extraction"],
    'confidence': 0.4344745874404907,
    'severity': 'minor',
    'start': 64,
    'end': 77,
    'check severity': ['minor', 'minor']}]},
 {'index': 1639,
  'source': 'However, most pre-training tasks proposed in the literature for business documents are too generic and not sufficient to learn more complex structures.',
  'translation': "Cependant, la plupart des tâches de pré-entraînement proposées dans la littérature pour les documents commerciaux sont trop génériques et ne permettent pas d'apprendre des structures plus complexes.",
  'postedition': "Cependant, la plupart des tâches de pré-entraînement proposées dans la littérature pour les documents commerciaux sont trop génériques et ne permettent pas d'apprendre des structures plus complexes.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 27, 0, 27]],
  'spans_each_mt': []},
 {'index': 1640,
  'source': 'In this paper, we use LayoutLM, a language model pre-trained on a collection of business documents, and introduce two new pre-training tasks that further improve its capacity to extract relevant information.',
  'translation': 'Dans cet article, nous utilisons LayoutLM, un modèle de langage pré-entraîné sur une collection de documents commerciaux, et introduisons deux nouvelles tâches de pré-entraînement qui améliorent encore sa capacité à extraire des informations pertinentes.',
  'postedition': 'Dans cet article, nous utilisons LayoutLM, un modèle de langue pré-entraîné sur une collection de documents commerciaux, et introduisons deux nouvelles tâches de pré-entraînement qui améliorent encore sa capacité à extraire des informations pertinentes.',
  'relevant_words': ['langage'],
  'difflib operations': [['equal', 0, 9, 0, 9],
   ['replace', 9, 10, 9, 10],
   ['equal', 10, 34, 10, 34]],
  'spans_each_mt': [{'text': ['langage', 'pré-entraîné'],
    'confidence': 0.41806909441947937,
    'severity': 'minor',
    'start': 55,
    'end': 76,
    'check severity': ['minor', 'minor', 'minor', 'minor']},
   {'text': ['commerciaux,'],
    'confidence': 0.413889080286026,
    'severity': 'minor',
    'start': 108,
    'end': 121,
    'check severity': ['minor']},
   {'text': ['introduisons'],
    'confidence': 0.3995507061481476,
    'severity': 'minor',
    'start': 124,
    'end': 137,
    'check severity': ['minor']}]},
 {'index': 1641,
  'source': 'The first is aimed at better understanding the complex layout of documents, and the second focuses on numeric values and their order of magnitude.',
  'translation': 'La première vise à mieux comprendre la mise en page complexe des documents, et la seconde se concentre sur les valeurs numériques et leur ordre de grandeur.',
  'postedition': 'La première vise à mieux comprendre la mise en page complexe des documents, et la seconde se concentre sur les valeurs numériques et leur ordre de grandeur.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 27, 0, 27]],
  'spans_each_mt': [{'text': ['ordre', 'de', 'grandeur.'],
    'confidence': 0.4173641800880432,
    'severity': 'minor',
    'start': 137,
    'end': 156,
    'check severity': ['minor', 'minor', 'minor', 'minor']}]},
 {'index': 1642,
  'source': 'These tasks force the model to learn bettercontextualized representations of the scanned documents.',
  'translation': 'Ces tâches obligent le modèle à apprendre des représentations mieux contextualisées des documents scannés.',
  'postedition': 'Ces tâches obligent le modèle à apprendre des représentations mieux contextualisées des documents scannés.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 14, 0, 14]],
  'spans_each_mt': []},
 {'index': 1643,
  'source': 'We further introduce a new post-processing algorithm to decode BIESO tags in Information Extraction that performs better with complex entities.',
  'translation': "Nous introduisons également un nouvel algorithme de post-traitement pour décoder les étiquettes BIESO dans l'extraction d'informations, qui donne de meilleurs résultats avec les entités complexes.",
  'postedition': "Nous introduisons également un nouvel algorithme de post-traitement pour décoder les étiquettes BIESO dans l'extraction d'informations, qui donne de meilleurs résultats avec les entités complexes.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 25, 0, 25]],
  'spans_each_mt': [{'text': ['de', 'post-traitement'],
    'confidence': 0.41894665360450745,
    'severity': 'minor',
    'start': 48,
    'end': 67,
    'check severity': ['minor', 'minor', 'minor', 'minor', 'minor']},
   {'text': ["l'extraction", "d'informations,"],
    'confidence': 0.4012504518032074,
    'severity': 'minor',
    'start': 106,
    'end': 135,
    'check severity': ['minor', 'minor', 'minor', 'minor', 'minor']}]},
 {'index': 1644,
  'source': 'Our method significantly improves extraction performance on both public (from 93.88 to 95.50 F1 score) and private (from 84.35 to 84.84 F1 score) datasets composed of expense receipts, invoices, and purchase orders.',
  'translation': "Notre méthode améliore considérablement les performances d'extraction sur les ensembles de données publics (de 93,88 à 95,50 pour le score F1) et privés (de 84,35 à 84,84 pour le score F1) composés de reçus de dépenses, de factures et de bons de commande.",
  'postedition': "Notre méthode améliore considérablement les performances d'extraction sur les ensembles de données publics (de 93,88 à 95,50 pour le score F1) et privés (de 84,35 à 84,84 pour le score F1) composés de reçus de dépenses, de factures et de bons de commande.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 43, 0, 43]],
  'spans_each_mt': [{'text': ['F1)'],
    'confidence': 0.4204215407371521,
    'severity': 'minor',
    'start': 184,
    'end': 188,
    'check severity': ['minor']}]}]

In [407]:
spans_with_new_starts_ends_19057 = []
previous_sentence_length = 2

In [408]:
spans_19057 = []
for span in spans:
    print(span)
    xcomet_span = span['spans_each_mt'] if 'spans_each_mt' in span else None
    if xcomet_span:
        span_list = []
        for index, each_span in enumerate(xcomet_span):
            span_list.append({
                'text': each_span['text'],
                'start': each_span['start'],
                'end': each_span['end'],
                'severity': each_span['severity'],
                'confidence': each_span['confidence']

            })
        spans_19057.append(span_list)
    else:
        spans_19057.append([])

{'index': 1636, 'source': 'Improving Information Extraction on Business Documents with Specific Pre-Training Tasks', 'translation': "Amélioration de l'extraction d'information sur des documents commerciaux avec des tâches de pré-entraînement spécifiques", 'postedition': "Amélioration de l'extraction d'information sur des documents commerciaux avec des tâches de pré-entraînement spécifiques", 'relevant_words': [], 'difflib operations': [['equal', 0, 14, 0, 14]], 'spans_each_mt': [{'text': ['Amélioration'], 'confidence': 0.45616263151168823, 'severity': 'minor', 'start': 0, 'end': 12, 'check severity': ['minor']}, {'text': ["l'extraction", "d'information"], 'confidence': 0.4250956177711487, 'severity': 'minor', 'start': 15, 'end': 42, 'check severity': ['minor', 'minor', 'minor']}, {'text': ['commerciaux'], 'confidence': 0.42627623677253723, 'severity': 'minor', 'start': 60, 'end': 72, 'check severity': ['minor']}, {'text': ['pré-entraînement'], 'confidence': 0.4056091904640198, 'severity': 'minor', 'start': 91, 'end': 108, 'check severity': ['minor']}]}
{'index': 1637, 'source': 'Transformer-based Language Models are widely used in Natural Language Processing related tasks.', 'translation': 'Les modèles de langage basés sur des transformateurs sont largement utilisés dans les tâches liées au traitement du langage naturel.', 'postedition': 'Les modèles de langue basés sur des transformateurs sont largement utilisés dans les tâches liées au traitement automatique des langues.', 'relevant_words': ['langage', 'du', 'langage', 'naturel.'], 'difflib operations': [['equal', 0, 3, 0, 3], ['replace', 3, 4, 3, 4], ['equal', 4, 17, 4, 17], ['replace', 17, 20, 17, 20]], 'spans_each_mt': [{'text': ['transformateurs'], 'confidence': 0.41461944580078125, 'severity': 'minor', 'start': 36, 'end': 52, 'check severity': ['minor']}]}
{'index': 1638, 'source': 'Thanks to their pre-training, they have been successfully adapted to Information Extraction in business documents.', 'translation': "Grâce à leur pré-entraînement, ils ont été adaptés avec succès à l'extraction d'informations dans les documents commerciaux.", 'postedition': "Grâce à leur pré-entraînement, ils ont été adaptés avec succès à l'extraction d'informations dans les documents commerciaux.", 'relevant_words': [], 'difflib operations': [['equal', 0, 17, 0, 17]], 'spans_each_mt': [{'text': ['pré-entraînement,'], 'confidence': 0.4208151400089264, 'severity': 'minor', 'start': 12, 'end': 30, 'check severity': ['minor', 'minor']}, {'text': ['été', 'adaptés'], 'confidence': 0.4211413860321045, 'severity': 'minor', 'start': 38, 'end': 50, 'check severity': ['minor', 'minor']}, {'text': ["l'extraction"], 'confidence': 0.4344745874404907, 'severity': 'minor', 'start': 64, 'end': 77, 'check severity': ['minor', 'minor']}]}
{'index': 1639, 'source': 'However, most pre-training tasks proposed in the literature for business documents are too generic and not sufficient to learn more complex structures.', 'translation': "Cependant, la plupart des tâches de pré-entraînement proposées dans la littérature pour les documents commerciaux sont trop génériques et ne permettent pas d'apprendre des structures plus complexes.", 'postedition': "Cependant, la plupart des tâches de pré-entraînement proposées dans la littérature pour les documents commerciaux sont trop génériques et ne permettent pas d'apprendre des structures plus complexes.", 'relevant_words': [], 'difflib operations': [['equal', 0, 27, 0, 27]], 'spans_each_mt': []}
{'index': 1640, 'source': 'In this paper, we use LayoutLM, a language model pre-trained on a collection of business documents, and introduce two new pre-training tasks that further improve its capacity to extract relevant information.', 'translation': 'Dans cet article, nous utilisons LayoutLM, un modèle de langage pré-entraîné sur une collection de documents commerciaux, et introduisons deux nouvelles tâches de pré-entraînement qui améliorent encore sa capacité à extraire des informations pertinentes.', 'postedition': 'Dans cet article, nous utilisons LayoutLM, un modèle de langue pré-entraîné sur une collection de documents commerciaux, et introduisons deux nouvelles tâches de pré-entraînement qui améliorent encore sa capacité à extraire des informations pertinentes.', 'relevant_words': ['langage'], 'difflib operations': [['equal', 0, 9, 0, 9], ['replace', 9, 10, 9, 10], ['equal', 10, 34, 10, 34]], 'spans_each_mt': [{'text': ['langage', 'pré-entraîné'], 'confidence': 0.41806909441947937, 'severity': 'minor', 'start': 55, 'end': 76, 'check severity': ['minor', 'minor', 'minor', 'minor']}, {'text': ['commerciaux,'], 'confidence': 0.413889080286026, 'severity': 'minor', 'start': 108, 'end': 121, 'check severity': ['minor']}, {'text': ['introduisons'], 'confidence': 0.3995507061481476, 'severity': 'minor', 'start': 124, 'end': 137, 'check severity': ['minor']}]}
{'index': 1641, 'source': 'The first is aimed at better understanding the complex layout of documents, and the second focuses on numeric values and their order of magnitude.', 'translation': 'La première vise à mieux comprendre la mise en page complexe des documents, et la seconde se concentre sur les valeurs numériques et leur ordre de grandeur.', 'postedition': 'La première vise à mieux comprendre la mise en page complexe des documents, et la seconde se concentre sur les valeurs numériques et leur ordre de grandeur.', 'relevant_words': [], 'difflib operations': [['equal', 0, 27, 0, 27]], 'spans_each_mt': [{'text': ['ordre', 'de', 'grandeur.'], 'confidence': 0.4173641800880432, 'severity': 'minor', 'start': 137, 'end': 156, 'check severity': ['minor', 'minor', 'minor', 'minor']}]}
{'index': 1642, 'source': 'These tasks force the model to learn bettercontextualized representations of the scanned documents.', 'translation': 'Ces tâches obligent le modèle à apprendre des représentations mieux contextualisées des documents scannés.', 'postedition': 'Ces tâches obligent le modèle à apprendre des représentations mieux contextualisées des documents scannés.', 'relevant_words': [], 'difflib operations': [['equal', 0, 14, 0, 14]], 'spans_each_mt': []}
{'index': 1643, 'source': 'We further introduce a new post-processing algorithm to decode BIESO tags in Information Extraction that performs better with complex entities.', 'translation': "Nous introduisons également un nouvel algorithme de post-traitement pour décoder les étiquettes BIESO dans l'extraction d'informations, qui donne de meilleurs résultats avec les entités complexes.", 'postedition': "Nous introduisons également un nouvel algorithme de post-traitement pour décoder les étiquettes BIESO dans l'extraction d'informations, qui donne de meilleurs résultats avec les entités complexes.", 'relevant_words': [], 'difflib operations': [['equal', 0, 25, 0, 25]], 'spans_each_mt': [{'text': ['de', 'post-traitement'], 'confidence': 0.41894665360450745, 'severity': 'minor', 'start': 48, 'end': 67, 'check severity': ['minor', 'minor', 'minor', 'minor', 'minor']}, {'text': ["l'extraction", "d'informations,"], 'confidence': 0.4012504518032074, 'severity': 'minor', 'start': 106, 'end': 135, 'check severity': ['minor', 'minor', 'minor', 'minor', 'minor']}]}
{'index': 1644, 'source': 'Our method significantly improves extraction performance on both public (from 93.88 to 95.50 F1 score) and private (from 84.35 to 84.84 F1 score) datasets composed of expense receipts, invoices, and purchase orders.', 'translation': "Notre méthode améliore considérablement les performances d'extraction sur les ensembles de données publics (de 93,88 à 95,50 pour le score F1) et privés (de 84,35 à 84,84 pour le score F1) composés de reçus de dépenses, de factures et de bons de commande.", 'postedition': "Notre méthode améliore considérablement les performances d'extraction sur les ensembles de données publics (de 93,88 à 95,50 pour le score F1) et privés (de 84,35 à 84,84 pour le score F1) composés de reçus de dépenses, de factures et de bons de commande.", 'relevant_words': [], 'difflib operations': [['equal', 0, 43, 0, 43]], 'spans_each_mt': [{'text': ['F1)'], 'confidence': 0.4204215407371521, 'severity': 'minor', 'start': 184, 'end': 188, 'check severity': ['minor']}]}

In [409]:
for index, spans in enumerate(spans_19057):
    if index == 0:
        spans_title = []
        for span in spans:
            if span['start'] == 0:
                start = 0
            else:
                start = span['start'] + 1
            spans_title.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'],
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_19057.append(spans_title)

    # elif index == 1:
    #     #sentences
    #     spans_each_sentence = []
    #     for span in spans:
    #         spans_each_sentence.append({
    #                             'text': span['text'],
    #                             'startnew': span['start'] + 1 +2,
    #                             'endnew': span['end']
                                
    #                             })

    #     spans_with_new_starts_ends.append(spans_each_sentence)
    elif index == 1:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1]
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        
        for ind,span in enumerate(spans):
            print("index in index 1: ", ind)
            print("spans in index 1: ", span)
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
           
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })
        spans_with_new_starts_ends_19057.append(spans_each_sentence)

    else:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1] + 1
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        for ind,span in enumerate(spans):
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_19057.append(spans_each_sentence)

spans_with_new_starts_ends_19057

index is:  1  and previous sentence lenght:  122
index in index 1:  0
spans in index 1:  {'text': ['transformateurs'], 'start': 36, 'end': 52, 'severity': 'minor', 'confidence': 0.41461944580078125}
index is:  2  and previous sentence lenght:  255
index is:  3  and previous sentence lenght:  380
index is:  4  and previous sentence lenght:  579
index is:  5  and previous sentence lenght:  834
index is:  6  and previous sentence lenght:  991
index is:  7  and previous sentence lenght:  1098
index is:  8  and previous sentence lenght:  1295

[[{'text': ['Amélioration'],
   'startnew': 0,
   'endnew': 12,
   'severity': 'minor',
   'confidence': 0.45616263151168823},
  {'text': ["l'extraction", "d'information"],
   'startnew': 16,
   'endnew': 42,
   'severity': 'minor',
   'confidence': 0.4250956177711487},
  {'text': ['commerciaux'],
   'startnew': 61,
   'endnew': 72,
   'severity': 'minor',
   'confidence': 0.42627623677253723},
  {'text': ['pré-entraînement'],
   'startnew': 92,
   'endnew': 108,
   'severity': 'minor',
   'confidence': 0.4056091904640198}],
 [{'text': ['transformateurs'],
   'startnew': 159,
   'endnew': 174,
   'severity': 'minor',
   'confidence': 0.41461944580078125}],
 [{'text': ['pré-entraînement,'],
   'startnew': 268,
   'endnew': 285,
   'severity': 'minor',
   'confidence': 0.4208151400089264},
  {'text': ['été', 'adaptés'],
   'startnew': 294,
   'endnew': 305,
   'severity': 'minor',
   'confidence': 0.4211413860321045},
  {'text': ["l'extraction"],
   'startnew': 320,
   'endnew': 332,
   'severity': 'minor',
   'confidence': 0.4344745874404907}],
 [],
 [{'text': ['langage', 'pré-entraîné'],
   'startnew': 635,
   'endnew': 655,
   'severity': 'minor',
   'confidence': 0.41806909441947937},
  {'text': ['commerciaux,'],
   'startnew': 688,
   'endnew': 700,
   'severity': 'minor',
   'confidence': 0.413889080286026},
  {'text': ['introduisons'],
   'startnew': 704,
   'endnew': 716,
   'severity': 'minor',
   'confidence': 0.3995507061481476}],
 [{'text': ['ordre', 'de', 'grandeur.'],
   'startnew': 972,
   'endnew': 990,
   'severity': 'minor',
   'confidence': 0.4173641800880432}],
 [],
 [{'text': ['de', 'post-traitement'],
   'startnew': 1147,
   'endnew': 1165,
   'severity': 'minor',
   'confidence': 0.41894665360450745},
  {'text': ["l'extraction", "d'informations,"],
   'startnew': 1205,
   'endnew': 1233,
   'severity': 'minor',
   'confidence': 0.4012504518032074}],
 [{'text': ['F1)'],
   'startnew': 1480,
   'endnew': 1483,
   'severity': 'minor',
   'confidence': 0.4204215407371521}]]

In [410]:
result_19057 = [
    (d['startnew'], d['endnew'], idx + 1, d['severity'], round(d['confidence'], 3))
    for idx, inner_list in enumerate(spans_with_new_starts_ends_19057)
    for d in inner_list
]
result_19057

[(0, 12, 1, 'minor', 0.456),
 (16, 42, 1, 'minor', 0.425),
 (61, 72, 1, 'minor', 0.426),
 (92, 108, 1, 'minor', 0.406),
 (159, 174, 2, 'minor', 0.415),
 (268, 285, 3, 'minor', 0.421),
 (294, 305, 3, 'minor', 0.421),
 (320, 332, 3, 'minor', 0.434),
 (635, 655, 5, 'minor', 0.418),
 (688, 700, 5, 'minor', 0.414),
 (704, 716, 5, 'minor', 0.4),
 (972, 990, 6, 'minor', 0.417),
 (1147, 1165, 8, 'minor', 0.419),
 (1205, 1233, 8, 'minor', 0.401),
 (1480, 1483, 9, 'minor', 0.42)]

In [411]:
len(result_19057)

15

In [412]:
text19057[0:12]

'Amélioration'

In [413]:
text19057[1147:1165]

'de post-traitement'

In [414]:
text19057[1480:1483]

'F1)'

# for text 19251

In [416]:
filtered_df_2.iloc[3]['sentence_indices']

'[410, 411, 412, 413, 414, 415, 416, 417]'

In [417]:
sentences_length_of_abstract = sentence_length_abstract(df_translators.iloc[410:418]['translation'])
sentences_length_of_abstract

[75, 138, 132, 182, 116, 302, 184, 110]

In [418]:
text19251

"Perception de la parole et implémentation dans un assistant médical virtuel\n\nDans les procédures médicales d'urgence, les interactions positives et de confiance entre les suiveurs et les dirigeants sont impératives. Cette interaction est encore plus importante lorsqu'un agent virtuel joue le rôle de leader et qu'un humain joue le rôle de suiveur. Afin de gérer l'interaction homme-ordinateur, le leadership situationnel est utilisé pour faire correspondre le suiveur humain à un style de leadership approprié incarné par l'agent. Le leadership situationnel a été utilisé pour créer 33 énoncés indiquant les quatre styles de leadership différents. Une évaluation des participants a ensuite été réalisée afin d'examiner (1) si les perceptions de la confiance et de la motivation du leader varient en fonction du niveau de préparation et de la syntaxe de l'énoncé et (2) si la capacité et la volonté du suiveur sont affectées par le discours du leader. Nous avons constaté que les perceptions générales du comportement du leader influençaient la performance des suiveurs et que le discours du leader influençait la capacité des suiveurs. Enfin, nous démontrons comment les résultats de cette étude sont mis en œuvre dans un système d'agent virtuel."

In [419]:
spans = xcomet_spans_translator[410:418]
spans

[{'index': 411,
  'source': 'Speech Perception and Implementation in a Virtual Medical Assistant',
  'translation': 'Perception de la parole et implémentation dans un assistant médical virtuel',
  'postedition': 'Perception de la parole et implémentation dans un assistant médical virtuel',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 11, 0, 11]],
  'spans_each_mt': [{'text': ['de'],
    'confidence': 0.4306032955646515,
    'severity': 'minor',
    'start': 10,
    'end': 13,
    'check severity': ['minor']},
   {'text': ['parole'],
    'confidence': 0.4508613049983978,
    'severity': 'minor',
    'start': 16,
    'end': 23,
    'check severity': ['minor']},
   {'text': ['implémentation'],
    'confidence': 0.42203783988952637,
    'severity': 'minor',
    'start': 26,
    'end': 41,
    'check severity': ['minor', 'minor', 'minor']}]},
 {'index': 412,
  'source': 'In emergency medical procedures, positive and trusting interactions between followers and leaders are imperative.',
  'translation': "Dans les procédures médicales d'urgence, les interactions positives et de confiance entre les suiveurs et les dirigeants sont impératives.",
  'postedition': "Dans les procédures médicales d'urgence, les interactions positives et de confiance entre les followers et les leaders sont impératives.",
  'relevant_words': ['suiveurs', 'dirigeants'],
  'difflib operations': [['equal', 0, 13, 0, 13],
   ['replace', 13, 14, 13, 14],
   ['equal', 14, 16, 14, 16],
   ['replace', 16, 17, 16, 17],
   ['equal', 17, 19, 17, 19]],
  'spans_each_mt': [{'text': ['suiveurs'],
    'confidence': 0.41433292627334595,
    'severity': 'minor',
    'start': 93,
    'end': 102,
    'check severity': ['minor', 'minor']}]},
 {'index': 413,
  'source': 'That interaction is even more important when a virtual agent assumes the leader role and a human assumes the follower role.',
  'translation': "Cette interaction est encore plus importante lorsqu'un agent virtuel joue le rôle de leader et qu'un humain joue le rôle de suiveur.",
  'postedition': "Cette interaction est encore plus importante lorsqu'un agent virtuel joue le rôle de leader et qu'un humain joue le rôle de follower.",
  'relevant_words': ['suiveur.'],
  'difflib operations': [['equal', 0, 21, 0, 21], ['replace', 21, 22, 21, 22]],
  'spans_each_mt': [{'text': ['suiveur.'],
    'confidence': 0.4356856346130371,
    'severity': 'minor',
    'start': 123,
    'end': 132,
    'check severity': ['minor', 'minor']}]},
 {'index': 414,
  'source': 'In order to manage the human-computer interaction, situational leadership is employed to match the human follower to an appropriate leadership style embodied by the agent.',
  'translation': "Afin de gérer l'interaction homme-ordinateur, le leadership situationnel est utilisé pour faire correspondre le suiveur humain à un style de leadership approprié incarné par l'agent.",
  'postedition': "Afin de gérer l'interaction homme-ordinateur, le leadership situationnel est utilisé pour faire correspondre le follower humain à un style de leadership approprié incarné par l'agent.",
  'relevant_words': ['suiveur'],
  'difflib operations': [['equal', 0, 14, 0, 14],
   ['replace', 14, 15, 14, 15],
   ['equal', 15, 25, 15, 25]],
  'spans_each_mt': [{'text': ['situationnel'],
    'confidence': 0.4386421740055084,
    'severity': 'minor',
    'start': 59,
    'end': 72,
    'check severity': ['minor', 'minor']},
   {'text': ['suiveur'],
    'confidence': 0.38426753878593445,
    'severity': 'minor',
    'start': 111,
    'end': 119,
    'check severity': ['minor', 'minor', 'minor']}]},
 {'index': 415,
  'source': 'Situational leadership was used to create 33 utterances indicative of the four different leadership styles.',
  'translation': 'Le leadership situationnel a été utilisé pour créer 33 énoncés indiquant les quatre styles de leadership différents.',
  'postedition': 'Le leadership situationnel a été utilisé pour créer 33 énoncés indiquant les quatre styles de leadership différents.',
  'relevant_words': [],
  'difflib operations': [['equal', 0, 17, 0, 17]],
  'spans_each_mt': [{'text': ['leadership', 'situationnel'],
    'confidence': 0.4361695647239685,
    'severity': 'minor',
    'start': 2,
    'end': 26,
    'check severity': ['minor', 'minor', 'minor']},
   {'text': ['énoncés'],
    'confidence': 0.44259199500083923,
    'severity': 'minor',
    'start': 54,
    'end': 62,
    'check severity': ['minor', 'minor', 'minor']}]},
 {'index': 416,
  'source': 'A participant evaluation was then carried out in order to examine (1) whether perceptions of leader trust and motivation vary dependent on both readiness level and utterance syntax and (2) whether follower ability and willingness are affected by the leader’s speech.',
  'translation': "Une évaluation des participants a ensuite été réalisée afin d'examiner (1) si les perceptions de la confiance et de la motivation du leader varient en fonction du niveau de préparation et de la syntaxe de l'énoncé et (2) si la capacité et la volonté du suiveur sont affectées par le discours du leader.",
  'postedition': "Une évaluation des participants a ensuite été réalisée afin d'examiner (1) si les perceptions de la confiance et de la motivation du leader varient en fonction du niveau de préparation et de la syntaxe de l'énoncé et (2) si la capacité et la volonté du follower sont affectées par le discours du leader.",
  'relevant_words': ['suiveur'],
  'difflib operations': [['equal', 0, 45, 0, 45],
   ['replace', 45, 46, 45, 46],
   ['equal', 46, 53, 46, 53]],
  'spans_each_mt': [{'text': ['de', 'la', 'confiance'],
    'confidence': 0.4074436128139496,
    'severity': 'minor',
    'start': 93,
    'end': 109,
    'check severity': ['minor', 'minor', 'minor']},
   {'text': ['motivation', 'du', 'leader'],
    'confidence': 0.37416204810142517,
    'severity': 'major',
    'start': 118,
    'end': 139,
    'check severity': ['minor', 'major', 'minor']},
   {'text': ['préparation'],
    'confidence': 0.379510760307312,
    'severity': 'minor',
    'start': 172,
    'end': 184,
    'check severity': ['minor']},
   {'text': ["l'énoncé"],
    'confidence': 0.41508668661117554,
    'severity': 'minor',
    'start': 204,
    'end': 213,
    'check severity': ['minor', 'minor', 'minor']}]},
 {'index': 417,
  'source': 'We found that general perceptions of leadership behavior influenced follower performance and that the leader’s speech influences followers’ ability.',
  'translation': 'Nous avons constaté que les perceptions générales du comportement du leader influençaient la performance des suiveurs et que le discours du leader influençait la capacité des suiveurs.',
  'postedition': 'Nous avons constaté que les perceptions générales du comportement du leader influençaient la performance des followers et que le discours du leader influençait la capacité des followers.',
  'relevant_words': ['suiveurs', 'suiveurs.'],
  'difflib operations': [['equal', 0, 15, 0, 15],
   ['replace', 15, 16, 15, 16],
   ['equal', 16, 26, 16, 26],
   ['replace', 26, 27, 26, 27]],
  'spans_each_mt': [{'text': ['influençaient'],
    'confidence': 0.398681640625,
    'severity': 'minor',
    'start': 75,
    'end': 89,
    'check severity': ['minor']},
   {'text': ['capacité'],
    'confidence': 0.41435301303863525,
    'severity': 'minor',
    'start': 161,
    'end': 170,
    'check severity': ['minor']}]},
 {'index': 418,
  'source': 'Finally, we demonstrate how the results of this study are implemented in a virtual agent system.',
  'translation': "Enfin, nous démontrons comment les résultats de cette étude sont mis en œuvre dans un système d'agent virtuel.",
  'postedition': "Enfin, nous démontrons comment les résultats de cette étude sont mis en œuvre dans un système d'agent virtuel.",
  'relevant_words': [],
  'difflib operations': [['equal', 0, 18, 0, 18]],
  'spans_each_mt': []}]

In [421]:
len(spans[1]['translation'])

138

In [422]:
spans_with_new_starts_ends_19251 = []
previous_sentence_length = 2

In [423]:
spans_19251 = []
for span in spans:
    print(span)
    xcomet_span = span['spans_each_mt'] if 'spans_each_mt' in span else None
    if xcomet_span:
        span_list = []
        for index, each_span in enumerate(xcomet_span):
            span_list.append({
                'text': each_span['text'],
                'start': each_span['start'],
                'end': each_span['end'],
                'severity': each_span['severity'],
                'confidence': each_span['confidence']

            })
        spans_19251.append(span_list)
    else:
        spans_19251.append([])

{'index': 411, 'source': 'Speech Perception and Implementation in a Virtual Medical Assistant', 'translation': 'Perception de la parole et implémentation dans un assistant médical virtuel', 'postedition': 'Perception de la parole et implémentation dans un assistant médical virtuel', 'relevant_words': [], 'difflib operations': [['equal', 0, 11, 0, 11]], 'spans_each_mt': [{'text': ['de'], 'confidence': 0.4306032955646515, 'severity': 'minor', 'start': 10, 'end': 13, 'check severity': ['minor']}, {'text': ['parole'], 'confidence': 0.4508613049983978, 'severity': 'minor', 'start': 16, 'end': 23, 'check severity': ['minor']}, {'text': ['implémentation'], 'confidence': 0.42203783988952637, 'severity': 'minor', 'start': 26, 'end': 41, 'check severity': ['minor', 'minor', 'minor']}]}
{'index': 412, 'source': 'In emergency medical procedures, positive and trusting interactions between followers and leaders are imperative.', 'translation': "Dans les procédures médicales d'urgence, les interactions positives et de confiance entre les suiveurs et les dirigeants sont impératives.", 'postedition': "Dans les procédures médicales d'urgence, les interactions positives et de confiance entre les followers et les leaders sont impératives.", 'relevant_words': ['suiveurs', 'dirigeants'], 'difflib operations': [['equal', 0, 13, 0, 13], ['replace', 13, 14, 13, 14], ['equal', 14, 16, 14, 16], ['replace', 16, 17, 16, 17], ['equal', 17, 19, 17, 19]], 'spans_each_mt': [{'text': ['suiveurs'], 'confidence': 0.41433292627334595, 'severity': 'minor', 'start': 93, 'end': 102, 'check severity': ['minor', 'minor']}]}
{'index': 413, 'source': 'That interaction is even more important when a virtual agent assumes the leader role and a human assumes the follower role.', 'translation': "Cette interaction est encore plus importante lorsqu'un agent virtuel joue le rôle de leader et qu'un humain joue le rôle de suiveur.", 'postedition': "Cette interaction est encore plus importante lorsqu'un agent virtuel joue le rôle de leader et qu'un humain joue le rôle de follower.", 'relevant_words': ['suiveur.'], 'difflib operations': [['equal', 0, 21, 0, 21], ['replace', 21, 22, 21, 22]], 'spans_each_mt': [{'text': ['suiveur.'], 'confidence': 0.4356856346130371, 'severity': 'minor', 'start': 123, 'end': 132, 'check severity': ['minor', 'minor']}]}
{'index': 414, 'source': 'In order to manage the human-computer interaction, situational leadership is employed to match the human follower to an appropriate leadership style embodied by the agent.', 'translation': "Afin de gérer l'interaction homme-ordinateur, le leadership situationnel est utilisé pour faire correspondre le suiveur humain à un style de leadership approprié incarné par l'agent.", 'postedition': "Afin de gérer l'interaction homme-ordinateur, le leadership situationnel est utilisé pour faire correspondre le follower humain à un style de leadership approprié incarné par l'agent.", 'relevant_words': ['suiveur'], 'difflib operations': [['equal', 0, 14, 0, 14], ['replace', 14, 15, 14, 15], ['equal', 15, 25, 15, 25]], 'spans_each_mt': [{'text': ['situationnel'], 'confidence': 0.4386421740055084, 'severity': 'minor', 'start': 59, 'end': 72, 'check severity': ['minor', 'minor']}, {'text': ['suiveur'], 'confidence': 0.38426753878593445, 'severity': 'minor', 'start': 111, 'end': 119, 'check severity': ['minor', 'minor', 'minor']}]}
{'index': 415, 'source': 'Situational leadership was used to create 33 utterances indicative of the four different leadership styles.', 'translation': 'Le leadership situationnel a été utilisé pour créer 33 énoncés indiquant les quatre styles de leadership différents.', 'postedition': 'Le leadership situationnel a été utilisé pour créer 33 énoncés indiquant les quatre styles de leadership différents.', 'relevant_words': [], 'difflib operations': [['equal', 0, 17, 0, 17]], 'spans_each_mt': [{'text': ['leadership', 'situationnel'], 'confidence': 0.4361695647239685, 'severity': 'minor', 'start': 2, 'end': 26, 'check severity': ['minor', 'minor', 'minor']}, {'text': ['énoncés'], 'confidence': 0.44259199500083923, 'severity': 'minor', 'start': 54, 'end': 62, 'check severity': ['minor', 'minor', 'minor']}]}
{'index': 416, 'source': 'A participant evaluation was then carried out in order to examine (1) whether perceptions of leader trust and motivation vary dependent on both readiness level and utterance syntax and (2) whether follower ability and willingness are affected by the leader’s speech.', 'translation': "Une évaluation des participants a ensuite été réalisée afin d'examiner (1) si les perceptions de la confiance et de la motivation du leader varient en fonction du niveau de préparation et de la syntaxe de l'énoncé et (2) si la capacité et la volonté du suiveur sont affectées par le discours du leader.", 'postedition': "Une évaluation des participants a ensuite été réalisée afin d'examiner (1) si les perceptions de la confiance et de la motivation du leader varient en fonction du niveau de préparation et de la syntaxe de l'énoncé et (2) si la capacité et la volonté du follower sont affectées par le discours du leader.", 'relevant_words': ['suiveur'], 'difflib operations': [['equal', 0, 45, 0, 45], ['replace', 45, 46, 45, 46], ['equal', 46, 53, 46, 53]], 'spans_each_mt': [{'text': ['de', 'la', 'confiance'], 'confidence': 0.4074436128139496, 'severity': 'minor', 'start': 93, 'end': 109, 'check severity': ['minor', 'minor', 'minor']}, {'text': ['motivation', 'du', 'leader'], 'confidence': 0.37416204810142517, 'severity': 'major', 'start': 118, 'end': 139, 'check severity': ['minor', 'major', 'minor']}, {'text': ['préparation'], 'confidence': 0.379510760307312, 'severity': 'minor', 'start': 172, 'end': 184, 'check severity': ['minor']}, {'text': ["l'énoncé"], 'confidence': 0.41508668661117554, 'severity': 'minor', 'start': 204, 'end': 213, 'check severity': ['minor', 'minor', 'minor']}]}
{'index': 417, 'source': 'We found that general perceptions of leadership behavior influenced follower performance and that the leader’s speech influences followers’ ability.', 'translation': 'Nous avons constaté que les perceptions générales du comportement du leader influençaient la performance des suiveurs et que le discours du leader influençait la capacité des suiveurs.', 'postedition': 'Nous avons constaté que les perceptions générales du comportement du leader influençaient la performance des followers et que le discours du leader influençait la capacité des followers.', 'relevant_words': ['suiveurs', 'suiveurs.'], 'difflib operations': [['equal', 0, 15, 0, 15], ['replace', 15, 16, 15, 16], ['equal', 16, 26, 16, 26], ['replace', 26, 27, 26, 27]], 'spans_each_mt': [{'text': ['influençaient'], 'confidence': 0.398681640625, 'severity': 'minor', 'start': 75, 'end': 89, 'check severity': ['minor']}, {'text': ['capacité'], 'confidence': 0.41435301303863525, 'severity': 'minor', 'start': 161, 'end': 170, 'check severity': ['minor']}]}
{'index': 418, 'source': 'Finally, we demonstrate how the results of this study are implemented in a virtual agent system.', 'translation': "Enfin, nous démontrons comment les résultats de cette étude sont mis en œuvre dans un système d'agent virtuel.", 'postedition': "Enfin, nous démontrons comment les résultats de cette étude sont mis en œuvre dans un système d'agent virtuel.", 'relevant_words': [], 'difflib operations': [['equal', 0, 18, 0, 18]], 'spans_each_mt': []}

In [424]:
for index, spans in enumerate(spans_19251):
    if index == 0:
        spans_title = []
        for span in spans:
            if span['start'] == 0:
                start = 0
            else:
                start = span['start'] + 1
            spans_title.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'],
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_19251.append(spans_title)

    # elif index == 1:
    #     #sentences
    #     spans_each_sentence = []
    #     for span in spans:
    #         spans_each_sentence.append({
    #                             'text': span['text'],
    #                             'startnew': span['start'] + 1 +2,
    #                             'endnew': span['end']
                                
    #                             })

    #     spans_with_new_starts_ends.append(spans_each_sentence)
    elif index == 1:
        spans_each_sentence = []
        print("sentences_length_of_abstract[index - 1]: ", sentences_length_of_abstract[index - 1])
        previous_sentence_length += sentences_length_of_abstract[index - 1]
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        
        for ind,span in enumerate(spans):
            print("index in index 1: ", ind)
            print("spans in index 1: ", span)
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
           
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })
        spans_with_new_starts_ends_19251.append(spans_each_sentence)

    else:
        spans_each_sentence = []
        previous_sentence_length += sentences_length_of_abstract[index - 1] + 1
        print("index is: ", index, " and previous sentence lenght: ", previous_sentence_length)
        for ind,span in enumerate(spans):
            if span['start'] == 0:
                start = span['start'] + previous_sentence_length
            else:
                start = span['start'] + previous_sentence_length + 1
            spans_each_sentence.append({
                                'text': span['text'][:],
                                'startnew': start,
                                'endnew': span['end'] + previous_sentence_length,
                                'severity': span['severity'],
                                'confidence': span['confidence']
                                
                                })

        spans_with_new_starts_ends_19251.append(spans_each_sentence)

spans_with_new_starts_ends_19251

sentences_length_of_abstract[index - 1]:  75
index is:  1  and previous sentence lenght:  77
index in index 1:  0
spans in index 1:  {'text': ['suiveurs'], 'start': 93, 'end': 102, 'severity': 'minor', 'confidence': 0.41433292627334595}
index is:  2  and previous sentence lenght:  216
index is:  3  and previous sentence lenght:  349
index is:  4  and previous sentence lenght:  532
index is:  5  and previous sentence lenght:  649
index is:  6  and previous sentence lenght:  952
index is:  7  and previous sentence lenght:  1137

[[{'text': ['de'],
   'startnew': 11,
   'endnew': 13,
   'severity': 'minor',
   'confidence': 0.4306032955646515},
  {'text': ['parole'],
   'startnew': 17,
   'endnew': 23,
   'severity': 'minor',
   'confidence': 0.4508613049983978},
  {'text': ['implémentation'],
   'startnew': 27,
   'endnew': 41,
   'severity': 'minor',
   'confidence': 0.42203783988952637}],
 [{'text': ['suiveurs'],
   'startnew': 171,
   'endnew': 179,
   'severity': 'minor',
   'confidence': 0.41433292627334595}],
 [{'text': ['suiveur.'],
   'startnew': 340,
   'endnew': 348,
   'severity': 'minor',
   'confidence': 0.4356856346130371}],
 [{'text': ['situationnel'],
   'startnew': 409,
   'endnew': 421,
   'severity': 'minor',
   'confidence': 0.4386421740055084},
  {'text': ['suiveur'],
   'startnew': 461,
   'endnew': 468,
   'severity': 'minor',
   'confidence': 0.38426753878593445}],
 [{'text': ['leadership', 'situationnel'],
   'startnew': 535,
   'endnew': 558,
   'severity': 'minor',
   'confidence': 0.4361695647239685},
  {'text': ['énoncés'],
   'startnew': 587,
   'endnew': 594,
   'severity': 'minor',
   'confidence': 0.44259199500083923}],
 [{'text': ['de', 'la', 'confiance'],
   'startnew': 743,
   'endnew': 758,
   'severity': 'minor',
   'confidence': 0.4074436128139496},
  {'text': ['motivation', 'du', 'leader'],
   'startnew': 768,
   'endnew': 788,
   'severity': 'major',
   'confidence': 0.37416204810142517},
  {'text': ['préparation'],
   'startnew': 822,
   'endnew': 833,
   'severity': 'minor',
   'confidence': 0.379510760307312},
  {'text': ["l'énoncé"],
   'startnew': 854,
   'endnew': 862,
   'severity': 'minor',
   'confidence': 0.41508668661117554}],
 [{'text': ['influençaient'],
   'startnew': 1028,
   'endnew': 1041,
   'severity': 'minor',
   'confidence': 0.398681640625},
  {'text': ['capacité'],
   'startnew': 1114,
   'endnew': 1122,
   'severity': 'minor',
   'confidence': 0.41435301303863525}],
 []]

In [425]:

result_19251 = [
    (d['startnew'], d['endnew'], idx + 1, d['severity'], round(d['confidence'], 3))
    for idx, inner_list in enumerate(spans_with_new_starts_ends_19251)
    for d in inner_list
]
result_19251

[(11, 13, 1, 'minor', 0.431),
 (17, 23, 1, 'minor', 0.451),
 (27, 41, 1, 'minor', 0.422),
 (171, 179, 2, 'minor', 0.414),
 (340, 348, 3, 'minor', 0.436),
 (409, 421, 4, 'minor', 0.439),
 (461, 468, 4, 'minor', 0.384),
 (535, 558, 5, 'minor', 0.436),
 (587, 594, 5, 'minor', 0.443),
 (743, 758, 6, 'minor', 0.407),
 (768, 788, 6, 'major', 0.374),
 (822, 833, 6, 'minor', 0.38),
 (854, 862, 6, 'minor', 0.415),
 (1028, 1041, 7, 'minor', 0.399),
 (1114, 1122, 7, 'minor', 0.414)]

In [427]:
len(result_19251)

15

In [428]:
text19251[27:41]

'implémentation'

In [429]:
text19251[1114:1122]

'capacité'

In [430]:
text19251[171:179]

'suiveurs'

In [431]:
text19251[11:13]

'de'

In [432]:
text19251[17:23]

'parole'

In [ ]:
len(result_19251)

15

# creat the annotation table based on the formulas

### get the relative position P of the span in the text (the start index of the span divided by the total text length)

In [462]:
def get_relative_postion_P_of_spans(spans, abstract_length):
    relative_positions_P = []
    for index, span in enumerate(spans):
        start_offset = span[0]
        relative_position = start_offset / abstract_length
        relative_positions_P.append(round(relative_position,3))
    return relative_positions_P

### total characters per abstract

In [463]:
len(text19823)

1821

In [464]:
total_chars_19823 = len(text19823)
total_chars_19823

1821

In [465]:
total_chars_882 = len(text882)
total_chars_882

1561

In [466]:
total_chars_19057 = len(text19057)
total_chars_19057

1550

In [467]:
total_chars_19251 = len(text19251)
total_chars_19251

1247

### get the P

In [468]:
relative_position_P_spans_19823 = get_relative_postion_P_of_spans(result_19823, total_chars_19823)
relative_position_P_spans_19823

[0.173,
 0.21,
 0.248,
 0.255,
 0.305,
 0.343,
 0.378,
 0.488,
 0.709,
 0.817,
 0.921,
 0.986,
 0.995]

In [469]:
relative_position_P_spans_882 = get_relative_postion_P_of_spans(result_882, total_chars_882)
relative_position_P_spans_882

[0.012,
 0.026,
 0.15,
 0.167,
 0.315,
 0.364,
 0.734,
 0.922,
 0.954,
 0.976,
 0.985,
 0.996]

In [471]:
relative_position_P_spans_19057 = get_relative_postion_P_of_spans(result_19057, total_chars_19057)
relative_position_P_spans_19057

[0.0,
 0.01,
 0.039,
 0.059,
 0.103,
 0.173,
 0.19,
 0.206,
 0.41,
 0.444,
 0.454,
 0.627,
 0.74,
 0.777,
 0.955]

In [473]:
relative_position_P_spans_19251 = get_relative_postion_P_of_spans(result_19251, total_chars_19251)
relative_position_P_spans_19251

[0.009,
 0.014,
 0.022,
 0.137,
 0.273,
 0.328,
 0.37,
 0.429,
 0.471,
 0.596,
 0.616,
 0.659,
 0.685,
 0.824,
 0.893]

### get the the span relative length L (the span length divided by the maximum span length in the text)

In [475]:
def get_the_span_relative_length_L(spans):
    relative_length_L = []
    maximum_span_length = 0
    for span in spans:
        length = span[1] - span[0]
        if length > maximum_span_length:
            maximum_span_length = length
    print("maximum span length is: ", maximum_span_length)
    for index, span in enumerate(spans):
        start_offset = span[0]
        end_offset = span[1]
        length = end_offset - start_offset
        print(length)

        relative_length_L.append(round(length/maximum_span_length,3))
    return relative_length_L

In [480]:
span_relative_length_L_19823 = get_the_span_relative_length_L(result_19823)
span_relative_length_L_19823

maximum span length is:  25
9
23
7
25
7
9
17
20
10
7
3
11
10

[0.36, 0.92, 0.28, 1.0, 0.28, 0.36, 0.68, 0.8, 0.4, 0.28, 0.12, 0.44, 0.4]

In [481]:
span_relative_length_L_882 = get_the_span_relative_length_L(result_882)
span_relative_length_L_882

maximum span length is:  22
13
8
7
22
9
10
7
21
8
10
13
6

[0.591,
 0.364,
 0.318,
 1.0,
 0.409,
 0.455,
 0.318,
 0.955,
 0.364,
 0.455,
 0.591,
 0.273]

In [483]:
span_relative_length_L_19057 = get_the_span_relative_length_L(result_19057)
span_relative_length_L_19057

maximum span length is:  28
12
26
11
16
15
17
11
12
20
12
12
18
18
28
3

[0.429,
 0.929,
 0.393,
 0.571,
 0.536,
 0.607,
 0.393,
 0.429,
 0.714,
 0.429,
 0.429,
 0.643,
 0.643,
 1.0,
 0.107]

In [485]:
span_relative_length_L_19251 = get_the_span_relative_length_L(result_19251)
span_relative_length_L_19251

maximum span length is:  23
2
6
14
8
8
12
7
23
7
15
20
11
8
13
8

[0.087,
 0.261,
 0.609,
 0.348,
 0.348,
 0.522,
 0.304,
 1.0,
 0.304,
 0.652,
 0.87,
 0.478,
 0.348,
 0.565,
 0.348]

### now make the annotation table using 4 formulas

4 = severity is doubled

5 = confidence is doubled

6 = position,P is doubled

7 = length,L is doubled

In [487]:
result_19823

[(315, 324, 2, 'minor', 0.415),
 (383, 406, 2, 'major', 0.407),
 (452, 459, 3, 'minor', 0.363),
 (465, 490, 3, 'major', 0.428),
 (556, 563, 3, 'major', 0.46),
 (625, 634, 3, 'minor', 0.376),
 (688, 705, 4, 'minor', 0.452),
 (888, 908, 5, 'minor', 0.445),
 (1291, 1301, 8, 'minor', 0.466),
 (1487, 1494, 9, 'minor', 0.393),
 (1677, 1680, 10, 'minor', 0.446),
 (1795, 1806, 10, 'minor', 0.407),
 (1811, 1821, 10, 'minor', 0.437)]

**confidence + severity + L + P**

In [565]:
def create_annotation_rank_4(spans, L, P, translation_id):
    # severity is doubled
    severity_label_values = {
        'minor': .24,
        'major': .48,
        'critical': .96,
    }
    annotation_rank_4 = []
    for index, span in enumerate(spans):
        severity = span[3]
        #print("severity: ", severity)
        severity_value = severity_label_values[severity]
        #print(severity_value)
        #print("severity value doubled: ", 2 * severity_value)
        confidence = span[4]
        #print("confidence: ", confidence)
        relative_length = L[index]
        #print("relative_length: ", relative_length)
        relative_position = P[index]
        #print("relative_position: ", relative_position)

        rank = confidence + 2 * severity_value + relative_length + relative_position
        #print("rank: ", rank)
        annotation_rank_4.append(rank)
    #print("annotation_rank: ", annotation_rank_4)
    #print("annotation_rank sorted: ", sorted(annotation_rank_4, reverse=True))
    # Zip ranks with tuples
    combined = list(zip(annotation_rank_4, spans))

    # Sort by rank in descending order
    sorted_combined = sorted(combined, key=lambda x: x[0], reverse=True)

    # Unpack back into ranks and tuples
    sorted_annotation_rank_4, sorted_spans_4 = map(list, zip(*sorted_combined))

    print("Sorted Ranks:", sorted_annotation_rank_4)
    print("Sorted Tuples:", sorted_spans_4)
    return sorted_spans_4

In [566]:
def create_annotation_rank_5(spans, L, P, translation_id):
    # confidence is doubled
    severity_label_values = {
        'minor': .24,
        'major': .48,
        'critical': .96,
    }
    annotation_rank_5 = []
    for index, span in enumerate(spans):
        severity = span[3]
        #print("severity: ", severity)
        severity_value = severity_label_values[severity]
        #print(severity_value)
        confidence = span[4]
        #print("confidence: ", confidence)
        #print("confidence is doubled: ", confidence * 2)
        relative_length = L[index]
        #print("relative_length: ", relative_length)
        relative_position = P[index]
        #print("relative_position: ", relative_position)

        rank = confidence * 2 + severity_value + relative_length + relative_position
        #print("rank: ", rank)
        annotation_rank_5.append(rank)
    #print("annotation_rank: ", annotation_rank_5)
    #print("annotation_rank sorted: ", sorted(annotation_rank_5, reverse=True))
    # Zip ranks with tuples
    combined = list(zip(annotation_rank_5, spans))

    # Sort by rank in descending order
    sorted_combined = sorted(combined, key=lambda x: x[0], reverse=True)

    # Unpack back into ranks and tuples
    sorted_annotation_rank_5, sorted_spans_5 = map(list, zip(*sorted_combined))

    print("Sorted Ranks:", sorted_annotation_rank_5)
    print("Sorted Tuples:", sorted_spans_5)
    return sorted_spans_5

In [567]:
def create_annotation_rank_6(spans, L, P, translation_id):
    # relative length is doubled
    severity_label_values = {
        'minor': .24,
        'major': .48,
        'critical': .96,
    }
    annotation_rank_6 = []
    for index, span in enumerate(spans):
        severity = span[3]
        #print("severity: ", severity)
        severity_value = severity_label_values[severity]
        #print(severity_value)
        confidence = span[4]
        #print("confidence: ", confidence)
        #print("confidence is doubled: ", confidence * 2)
        relative_length = L[index]
        #print("relative_length: ", relative_length)
        relative_position = P[index]
        #print("relative_position: ", relative_position)

        rank = confidence + severity_value + 2 * relative_length + relative_position
        #print("rank: ", rank)
        annotation_rank_6.append(rank)
    #print("annotation_rank: ", annotation_rank_6)
    #print("annotation_rank sorted: ", sorted(annotation_rank_6, reverse=True))
    # Zip ranks with tuples
    combined = list(zip(annotation_rank_6, spans))

    # Sort by rank in descending order
    sorted_combined = sorted(combined, key=lambda x: x[0], reverse=True)

    # Unpack back into ranks and tuples
    sorted_annotation_rank_6, sorted_spans_6 = map(list, zip(*sorted_combined))

    print("Sorted Ranks:", sorted_annotation_rank_6)
    print("Sorted Tuples:", sorted_spans_6)
    return sorted_spans_6

In [568]:
def create_annotation_rank_7(spans, L, P, translation_id):
    # relative position is doubled
    severity_label_values = {
        'minor': .24,
        'major': .48,
        'critical': .96,
    }
    annotation_rank_7 = []
    for index, span in enumerate(spans):
        severity = span[3]
        #print("severity: ", severity)
        severity_value = severity_label_values[severity]
        #print(severity_value)
        confidence = span[4]
        #print("confidence: ", confidence)
        #print("confidence is doubled: ", confidence * 2)
        relative_length = L[index]
        #print("relative_length: ", relative_length)
        relative_position = P[index]
        #print("relative_position: ", relative_position)

        rank = confidence + severity_value + relative_length + relative_position * 2
        #print("rank: ", rank)
        annotation_rank_7.append(rank)
    #print("annotation_rank: ", annotation_rank_7)
    #print("annotation_rank sorted: ", sorted(annotation_rank_7, reverse=True))
    # Zip ranks with tuples
    combined = list(zip(annotation_rank_7, spans))

    # Sort by rank in descending order
    sorted_combined = sorted(combined, key=lambda x: x[0], reverse=True)

    # Unpack back into ranks and tuples
    sorted_annotation_rank_7, sorted_spans_7 = map(list, zip(*sorted_combined))

    print("Sorted Ranks:", sorted_annotation_rank_7)
    print("Sorted Tuples:", sorted_spans_7)
    print("sorted tuples type: ", type(sorted_spans_7))
    return sorted_spans_7

In [577]:
def create_annotation_list_of_dicts(annotations, translation_id, annotator_id):
    annotation_list_of_dicts = []
    for index, annotation in enumerate(annotations):
        annotation_list_of_dicts.append({
            'annotation_rank' : index + 1,
            'translation_id' : translation_id,
            'annotator_id' : annotator_id,
            'start_span' : annotation[0],
            'end_span' : annotation[1],
            'severity_level': annotation[3],
            'confidence' : annotation[4]
        })
    print("annotation_list_of_dicts: ", annotation_list_of_dicts)
    return annotation_list_of_dicts

In [578]:
def create_annotations(spans, L, P, translation_id):
    annotations = []

    # create annotations for annotator_id 4
    annotations_4 = create_annotation_rank_4(spans, L, P, translation_id)
    annotations_4_list_of_dicts = create_annotation_list_of_dicts(annotations_4,translation_id,4)
    annotations.append(annotations_4_list_of_dicts)
    # create annotations for annotator_id 5
    
    annotations_5 = create_annotation_rank_5(spans, L, P, translation_id)
    annotations_5_list_of_dicts = create_annotation_list_of_dicts(annotations_5,translation_id,5)
    annotations.append(annotations_5_list_of_dicts)
    # create annotations for annotator_id 6
    annotations_6 = create_annotation_rank_6(spans, L, P, translation_id)
    annotations_6_list_of_dicts = create_annotation_list_of_dicts(annotations_6,translation_id,6)
    annotations.append(annotations_6_list_of_dicts)
    # create annotations for annotator_id 7
    annotations_7 = create_annotation_rank_7(spans, L, P, translation_id)
    annotations_7_list_of_dicts = create_annotation_list_of_dicts(annotations_7,translation_id,7)
    annotations.append(annotations_7_list_of_dicts)
    # for index, span in enumerate(spans):
    #     annotation = {
    #         'start': span[0],
    #         'end': span[1],
    #         'sentence_index': span[2],
    #         'severity': span[3],
    #         'confidence': span[4],
    #         'relative_length_L': L[index],
    #         'relative_position_P': P[index]
    #     }
    #     annotations.append(annotation)
    return annotations

In [579]:
span_relative_length_L_19823

[0.36, 0.92, 0.28, 1.0, 0.28, 0.36, 0.68, 0.8, 0.4, 0.28, 0.12, 0.44, 0.4]

In [580]:
relative_position_P_spans_19823

[0.173,
 0.21,
 0.248,
 0.255,
 0.305,
 0.343,
 0.378,
 0.488,
 0.709,
 0.817,
 0.921,
 0.986,
 0.995]

In [581]:
annotations_19823 = create_annotations(result_19823, span_relative_length_L_19823, relative_position_P_spans_19823, 19823)

Sorted Ranks: [2.643, 2.497, 2.3129999999999997, 2.3120000000000003, 2.213, 2.055, 2.005, 1.9900000000000002, 1.97, 1.9669999999999999, 1.559, 1.428, 1.371]
Sorted Tuples: [(465, 490, 3, 'major', 0.428), (383, 406, 2, 'major', 0.407), (1795, 1806, 10, 'minor', 0.407), (1811, 1821, 10, 'minor', 0.437), (888, 908, 5, 'minor', 0.445), (1291, 1301, 8, 'minor', 0.466), (556, 563, 3, 'major', 0.46), (688, 705, 4, 'minor', 0.452), (1487, 1494, 9, 'minor', 0.393), (1677, 1680, 10, 'minor', 0.446), (625, 634, 3, 'minor', 0.376), (315, 324, 2, 'minor', 0.415), (452, 459, 3, 'minor', 0.363)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 465, 'end_span': 490, 'severity_level': 'major', 'confidence': 0.428}, {'annotation_rank': 2, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 383, 'end_span': 406, 'severity_level': 'major', 'confidence': 0.407}, {'annotation_rank': 3, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 1795, 'end_span': 1806, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 4, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 1811, 'end_span': 1821, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 5, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 888, 'end_span': 908, 'severity_level': 'minor', 'confidence': 0.445}, {'annotation_rank': 6, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 1291, 'end_span': 1301, 'severity_level': 'minor', 'confidence': 0.466}, {'annotation_rank': 7, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 556, 'end_span': 563, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 8, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 688, 'end_span': 705, 'severity_level': 'minor', 'confidence': 0.452}, {'annotation_rank': 9, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 1487, 'end_span': 1494, 'severity_level': 'minor', 'confidence': 0.393}, {'annotation_rank': 10, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 1677, 'end_span': 1680, 'severity_level': 'minor', 'confidence': 0.446}, {'annotation_rank': 11, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 625, 'end_span': 634, 'severity_level': 'minor', 'confidence': 0.376}, {'annotation_rank': 12, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 315, 'end_span': 324, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 13, 'translation_id': 19823, 'annotator_id': 4, 'start_span': 452, 'end_span': 459, 'severity_level': 'minor', 'confidence': 0.363}]
Sorted Ranks: [2.5909999999999997, 2.509, 2.4799999999999995, 2.424, 2.418, 2.281, 2.2020000000000004, 2.173, 2.123, 1.9849999999999999, 1.6949999999999998, 1.6029999999999998, 1.494]
Sorted Tuples: [(465, 490, 3, 'major', 0.428), (1811, 1821, 10, 'minor', 0.437), (1795, 1806, 10, 'minor', 0.407), (383, 406, 2, 'major', 0.407), (888, 908, 5, 'minor', 0.445), (1291, 1301, 8, 'minor', 0.466), (688, 705, 4, 'minor', 0.452), (1677, 1680, 10, 'minor', 0.446), (1487, 1494, 9, 'minor', 0.393), (556, 563, 3, 'major', 0.46), (625, 634, 3, 'minor', 0.376), (315, 324, 2, 'minor', 0.415), (452, 459, 3, 'minor', 0.363)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 465, 'end_span': 490, 'severity_level': 'major', 'confidence': 0.428}, {'annotation_rank': 2, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 1811, 'end_span': 1821, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 3, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 1795, 'end_span': 1806, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 4, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 383, 'end_span': 406, 'severity_level': 'major', 'confidence': 0.407}, {'annotation_rank': 5, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 888, 'end_span': 908, 'severity_level': 'minor', 'confidence': 0.445}, {'annotation_rank': 6, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 1291, 'end_span': 1301, 'severity_level': 'minor', 'confidence': 0.466}, {'annotation_rank': 7, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 688, 'end_span': 705, 'severity_level': 'minor', 'confidence': 0.452}, {'annotation_rank': 8, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 1677, 'end_span': 1680, 'severity_level': 'minor', 'confidence': 0.446}, {'annotation_rank': 9, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 1487, 'end_span': 1494, 'severity_level': 'minor', 'confidence': 0.393}, {'annotation_rank': 10, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 556, 'end_span': 563, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 11, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 625, 'end_span': 634, 'severity_level': 'minor', 'confidence': 0.376}, {'annotation_rank': 12, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 315, 'end_span': 324, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 13, 'translation_id': 19823, 'annotator_id': 5, 'start_span': 452, 'end_span': 459, 'severity_level': 'minor', 'confidence': 0.363}]
Sorted Ranks: [3.163, 2.9370000000000003, 2.773, 2.513, 2.472, 2.43, 2.215, 2.01, 1.847, 1.805, 1.6789999999999998, 1.548, 1.411]
Sorted Tuples: [(465, 490, 3, 'major', 0.428), (383, 406, 2, 'major', 0.407), (888, 908, 5, 'minor', 0.445), (1795, 1806, 10, 'minor', 0.407), (1811, 1821, 10, 'minor', 0.437), (688, 705, 4, 'minor', 0.452), (1291, 1301, 8, 'minor', 0.466), (1487, 1494, 9, 'minor', 0.393), (1677, 1680, 10, 'minor', 0.446), (556, 563, 3, 'major', 0.46), (625, 634, 3, 'minor', 0.376), (315, 324, 2, 'minor', 0.415), (452, 459, 3, 'minor', 0.363)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 465, 'end_span': 490, 'severity_level': 'major', 'confidence': 0.428}, {'annotation_rank': 2, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 383, 'end_span': 406, 'severity_level': 'major', 'confidence': 0.407}, {'annotation_rank': 3, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 888, 'end_span': 908, 'severity_level': 'minor', 'confidence': 0.445}, {'annotation_rank': 4, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 1795, 'end_span': 1806, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 5, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 1811, 'end_span': 1821, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 6, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 688, 'end_span': 705, 'severity_level': 'minor', 'confidence': 0.452}, {'annotation_rank': 7, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 1291, 'end_span': 1301, 'severity_level': 'minor', 'confidence': 0.466}, {'annotation_rank': 8, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 1487, 'end_span': 1494, 'severity_level': 'minor', 'confidence': 0.393}, {'annotation_rank': 9, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 1677, 'end_span': 1680, 'severity_level': 'minor', 'confidence': 0.446}, {'annotation_rank': 10, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 556, 'end_span': 563, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 11, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 625, 'end_span': 634, 'severity_level': 'minor', 'confidence': 0.376}, {'annotation_rank': 12, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 315, 'end_span': 324, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 13, 'translation_id': 19823, 'annotator_id': 6, 'start_span': 452, 'end_span': 459, 'severity_level': 'minor', 'confidence': 0.363}]
Sorted Ranks: [3.067, 3.059, 2.648, 2.5469999999999997, 2.524, 2.4610000000000003, 2.418, 2.227, 2.128, 1.83, 1.662, 1.379, 1.3610000000000002]
Sorted Tuples: [(1811, 1821, 10, 'minor', 0.437), (1795, 1806, 10, 'minor', 0.407), (1677, 1680, 10, 'minor', 0.446), (1487, 1494, 9, 'minor', 0.393), (1291, 1301, 8, 'minor', 0.466), (888, 908, 5, 'minor', 0.445), (465, 490, 3, 'major', 0.428), (383, 406, 2, 'major', 0.407), (688, 705, 4, 'minor', 0.452), (556, 563, 3, 'major', 0.46), (625, 634, 3, 'minor', 0.376), (452, 459, 3, 'minor', 0.363), (315, 324, 2, 'minor', 0.415)]
sorted tuples type:  <class 'list'>
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 1811, 'end_span': 1821, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 2, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 1795, 'end_span': 1806, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 3, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 1677, 'end_span': 1680, 'severity_level': 'minor', 'confidence': 0.446}, {'annotation_rank': 4, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 1487, 'end_span': 1494, 'severity_level': 'minor', 'confidence': 0.393}, {'annotation_rank': 5, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 1291, 'end_span': 1301, 'severity_level': 'minor', 'confidence': 0.466}, {'annotation_rank': 6, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 888, 'end_span': 908, 'severity_level': 'minor', 'confidence': 0.445}, {'annotation_rank': 7, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 465, 'end_span': 490, 'severity_level': 'major', 'confidence': 0.428}, {'annotation_rank': 8, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 383, 'end_span': 406, 'severity_level': 'major', 'confidence': 0.407}, {'annotation_rank': 9, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 688, 'end_span': 705, 'severity_level': 'minor', 'confidence': 0.452}, {'annotation_rank': 10, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 556, 'end_span': 563, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 11, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 625, 'end_span': 634, 'severity_level': 'minor', 'confidence': 0.376}, {'annotation_rank': 12, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 452, 'end_span': 459, 'severity_level': 'minor', 'confidence': 0.363}, {'annotation_rank': 13, 'translation_id': 19823, 'annotator_id': 7, 'start_span': 315, 'end_span': 324, 'severity_level': 'minor', 'confidence': 0.415}]

In [582]:
annotations_19823

[[{'annotation_rank': 1,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 465,
   'end_span': 490,
   'severity_level': 'major',
   'confidence': 0.428},
  {'annotation_rank': 2,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 383,
   'end_span': 406,
   'severity_level': 'major',
   'confidence': 0.407},
  {'annotation_rank': 3,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 1795,
   'end_span': 1806,
   'severity_level': 'minor',
   'confidence': 0.407},
  {'annotation_rank': 4,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 1811,
   'end_span': 1821,
   'severity_level': 'minor',
   'confidence': 0.437},
  {'annotation_rank': 5,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 888,
   'end_span': 908,
   'severity_level': 'minor',
   'confidence': 0.445},
  {'annotation_rank': 6,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 1291,
   'end_span': 1301,
   'severity_level': 'minor',
   'confidence': 0.466},
  {'annotation_rank': 7,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 556,
   'end_span': 563,
   'severity_level': 'major',
   'confidence': 0.46},
  {'annotation_rank': 8,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 688,
   'end_span': 705,
   'severity_level': 'minor',
   'confidence': 0.452},
  {'annotation_rank': 9,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 1487,
   'end_span': 1494,
   'severity_level': 'minor',
   'confidence': 0.393},
  {'annotation_rank': 10,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 1677,
   'end_span': 1680,
   'severity_level': 'minor',
   'confidence': 0.446},
  {'annotation_rank': 11,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 625,
   'end_span': 634,
   'severity_level': 'minor',
   'confidence': 0.376},
  {'annotation_rank': 12,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 315,
   'end_span': 324,
   'severity_level': 'minor',
   'confidence': 0.415},
  {'annotation_rank': 13,
   'translation_id': 19823,
   'annotator_id': 4,
   'start_span': 452,
   'end_span': 459,
   'severity_level': 'minor',
   'confidence': 0.363}],
 [{'annotation_rank': 1,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 465,
   'end_span': 490,
   'severity_level': 'major',
   'confidence': 0.428},
  {'annotation_rank': 2,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 1811,
   'end_span': 1821,
   'severity_level': 'minor',
   'confidence': 0.437},
  {'annotation_rank': 3,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 1795,
   'end_span': 1806,
   'severity_level': 'minor',
   'confidence': 0.407},
  {'annotation_rank': 4,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 383,
   'end_span': 406,
   'severity_level': 'major',
   'confidence': 0.407},
  {'annotation_rank': 5,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 888,
   'end_span': 908,
   'severity_level': 'minor',
   'confidence': 0.445},
  {'annotation_rank': 6,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 1291,
   'end_span': 1301,
   'severity_level': 'minor',
   'confidence': 0.466},
  {'annotation_rank': 7,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 688,
   'end_span': 705,
   'severity_level': 'minor',
   'confidence': 0.452},
  {'annotation_rank': 8,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 1677,
   'end_span': 1680,
   'severity_level': 'minor',
   'confidence': 0.446},
  {'annotation_rank': 9,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 1487,
   'end_span': 1494,
   'severity_level': 'minor',
   'confidence': 0.393},
  {'annotation_rank': 10,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 556,
   'end_span': 563,
   'severity_level': 'major',
   'confidence': 0.46},
  {'annotation_rank': 11,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 625,
   'end_span': 634,
   'severity_level': 'minor',
   'confidence': 0.376},
  {'annotation_rank': 12,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 315,
   'end_span': 324,
   'severity_level': 'minor',
   'confidence': 0.415},
  {'annotation_rank': 13,
   'translation_id': 19823,
   'annotator_id': 5,
   'start_span': 452,
   'end_span': 459,
   'severity_level': 'minor',
   'confidence': 0.363}],
 [{'annotation_rank': 1,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 465,
   'end_span': 490,
   'severity_level': 'major',
   'confidence': 0.428},
  {'annotation_rank': 2,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 383,
   'end_span': 406,
   'severity_level': 'major',
   'confidence': 0.407},
  {'annotation_rank': 3,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 888,
   'end_span': 908,
   'severity_level': 'minor',
   'confidence': 0.445},
  {'annotation_rank': 4,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 1795,
   'end_span': 1806,
   'severity_level': 'minor',
   'confidence': 0.407},
  {'annotation_rank': 5,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 1811,
   'end_span': 1821,
   'severity_level': 'minor',
   'confidence': 0.437},
  {'annotation_rank': 6,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 688,
   'end_span': 705,
   'severity_level': 'minor',
   'confidence': 0.452},
  {'annotation_rank': 7,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 1291,
   'end_span': 1301,
   'severity_level': 'minor',
   'confidence': 0.466},
  {'annotation_rank': 8,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 1487,
   'end_span': 1494,
   'severity_level': 'minor',
   'confidence': 0.393},
  {'annotation_rank': 9,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 1677,
   'end_span': 1680,
   'severity_level': 'minor',
   'confidence': 0.446},
  {'annotation_rank': 10,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 556,
   'end_span': 563,
   'severity_level': 'major',
   'confidence': 0.46},
  {'annotation_rank': 11,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 625,
   'end_span': 634,
   'severity_level': 'minor',
   'confidence': 0.376},
  {'annotation_rank': 12,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 315,
   'end_span': 324,
   'severity_level': 'minor',
   'confidence': 0.415},
  {'annotation_rank': 13,
   'translation_id': 19823,
   'annotator_id': 6,
   'start_span': 452,
   'end_span': 459,
   'severity_level': 'minor',
   'confidence': 0.363}],
 [{'annotation_rank': 1,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 1811,
   'end_span': 1821,
   'severity_level': 'minor',
   'confidence': 0.437},
  {'annotation_rank': 2,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 1795,
   'end_span': 1806,
   'severity_level': 'minor',
   'confidence': 0.407},
  {'annotation_rank': 3,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 1677,
   'end_span': 1680,
   'severity_level': 'minor',
   'confidence': 0.446},
  {'annotation_rank': 4,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 1487,
   'end_span': 1494,
   'severity_level': 'minor',
   'confidence': 0.393},
  {'annotation_rank': 5,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 1291,
   'end_span': 1301,
   'severity_level': 'minor',
   'confidence': 0.466},
  {'annotation_rank': 6,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 888,
   'end_span': 908,
   'severity_level': 'minor',
   'confidence': 0.445},
  {'annotation_rank': 7,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 465,
   'end_span': 490,
   'severity_level': 'major',
   'confidence': 0.428},
  {'annotation_rank': 8,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 383,
   'end_span': 406,
   'severity_level': 'major',
   'confidence': 0.407},
  {'annotation_rank': 9,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 688,
   'end_span': 705,
   'severity_level': 'minor',
   'confidence': 0.452},
  {'annotation_rank': 10,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 556,
   'end_span': 563,
   'severity_level': 'major',
   'confidence': 0.46},
  {'annotation_rank': 11,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 625,
   'end_span': 634,
   'severity_level': 'minor',
   'confidence': 0.376},
  {'annotation_rank': 12,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 452,
   'end_span': 459,
   'severity_level': 'minor',
   'confidence': 0.363},
  {'annotation_rank': 13,
   'translation_id': 19823,
   'annotator_id': 7,
   'start_span': 315,
   'end_span': 324,
   'severity_level': 'minor',
   'confidence': 0.415}]]

In [586]:
annotations_882 = create_annotations(result_882, span_relative_length_L_882, relative_position_P_spans_882, 882)

Sorted Ranks: [2.797, 2.479, 2.348, 2.2, 2.144, 2.135, 2.053, 1.944, 1.706, 1.524, 1.3539999999999999, 1.305]
Sorted Tuples: [(1439, 1460, 8, 'minor', 0.44), (1538, 1551, 8, 'minor', 0.423), (1524, 1534, 8, 'minor', 0.437), (1489, 1497, 8, 'minor', 0.402), (492, 501, 2, 'major', 0.46), (1555, 1561, 8, 'minor', 0.386), (260, 282, 2, 'minor', 0.406), (1145, 1152, 6, 'minor', 0.412), (568, 578, 3, 'minor', 0.407), (18, 31, 1, 'minor', 0.441), (234, 241, 2, 'minor', 0.406), (40, 48, 1, 'minor', 0.435)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 882, 'annotator_id': 4, 'start_span': 1439, 'end_span': 1460, 'severity_level': 'minor', 'confidence': 0.44}, {'annotation_rank': 2, 'translation_id': 882, 'annotator_id': 4, 'start_span': 1538, 'end_span': 1551, 'severity_level': 'minor', 'confidence': 0.423}, {'annotation_rank': 3, 'translation_id': 882, 'annotator_id': 4, 'start_span': 1524, 'end_span': 1534, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 4, 'translation_id': 882, 'annotator_id': 4, 'start_span': 1489, 'end_span': 1497, 'severity_level': 'minor', 'confidence': 0.402}, {'annotation_rank': 5, 'translation_id': 882, 'annotator_id': 4, 'start_span': 492, 'end_span': 501, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 6, 'translation_id': 882, 'annotator_id': 4, 'start_span': 1555, 'end_span': 1561, 'severity_level': 'minor', 'confidence': 0.386}, {'annotation_rank': 7, 'translation_id': 882, 'annotator_id': 4, 'start_span': 260, 'end_span': 282, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 8, 'translation_id': 882, 'annotator_id': 4, 'start_span': 1145, 'end_span': 1152, 'severity_level': 'minor', 'confidence': 0.412}, {'annotation_rank': 9, 'translation_id': 882, 'annotator_id': 4, 'start_span': 568, 'end_span': 578, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 10, 'translation_id': 882, 'annotator_id': 4, 'start_span': 18, 'end_span': 31, 'severity_level': 'minor', 'confidence': 0.441}, {'annotation_rank': 11, 'translation_id': 882, 'annotator_id': 4, 'start_span': 234, 'end_span': 241, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 12, 'translation_id': 882, 'annotator_id': 4, 'start_span': 40, 'end_span': 48, 'severity_level': 'minor', 'confidence': 0.435}]
Sorted Ranks: [2.9970000000000003, 2.662, 2.545, 2.362, 2.281, 2.219, 2.124, 2.116, 1.8729999999999998, 1.7249999999999999, 1.52, 1.4999999999999998]
Sorted Tuples: [(1439, 1460, 8, 'minor', 0.44), (1538, 1551, 8, 'minor', 0.423), (1524, 1534, 8, 'minor', 0.437), (1489, 1497, 8, 'minor', 0.402), (1555, 1561, 8, 'minor', 0.386), (260, 282, 2, 'minor', 0.406), (492, 501, 2, 'major', 0.46), (1145, 1152, 6, 'minor', 0.412), (568, 578, 3, 'minor', 0.407), (18, 31, 1, 'minor', 0.441), (234, 241, 2, 'minor', 0.406), (40, 48, 1, 'minor', 0.435)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 882, 'annotator_id': 5, 'start_span': 1439, 'end_span': 1460, 'severity_level': 'minor', 'confidence': 0.44}, {'annotation_rank': 2, 'translation_id': 882, 'annotator_id': 5, 'start_span': 1538, 'end_span': 1551, 'severity_level': 'minor', 'confidence': 0.423}, {'annotation_rank': 3, 'translation_id': 882, 'annotator_id': 5, 'start_span': 1524, 'end_span': 1534, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 4, 'translation_id': 882, 'annotator_id': 5, 'start_span': 1489, 'end_span': 1497, 'severity_level': 'minor', 'confidence': 0.402}, {'annotation_rank': 5, 'translation_id': 882, 'annotator_id': 5, 'start_span': 1555, 'end_span': 1561, 'severity_level': 'minor', 'confidence': 0.386}, {'annotation_rank': 6, 'translation_id': 882, 'annotator_id': 5, 'start_span': 260, 'end_span': 282, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 7, 'translation_id': 882, 'annotator_id': 5, 'start_span': 492, 'end_span': 501, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 8, 'translation_id': 882, 'annotator_id': 5, 'start_span': 1145, 'end_span': 1152, 'severity_level': 'minor', 'confidence': 0.412}, {'annotation_rank': 9, 'translation_id': 882, 'annotator_id': 5, 'start_span': 568, 'end_span': 578, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 10, 'translation_id': 882, 'annotator_id': 5, 'start_span': 18, 'end_span': 31, 'severity_level': 'minor', 'confidence': 0.441}, {'annotation_rank': 11, 'translation_id': 882, 'annotator_id': 5, 'start_span': 234, 'end_span': 241, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 12, 'translation_id': 882, 'annotator_id': 5, 'start_span': 40, 'end_span': 48, 'severity_level': 'minor', 'confidence': 0.435}]
Sorted Ranks: [3.512, 2.83, 2.8129999999999997, 2.563, 2.324, 2.168, 2.073, 2.022, 1.9209999999999998, 1.875, 1.432, 1.429]
Sorted Tuples: [(1439, 1460, 8, 'minor', 0.44), (1538, 1551, 8, 'minor', 0.423), (260, 282, 2, 'minor', 0.406), (1524, 1534, 8, 'minor', 0.437), (1489, 1497, 8, 'minor', 0.402), (1555, 1561, 8, 'minor', 0.386), (492, 501, 2, 'major', 0.46), (1145, 1152, 6, 'minor', 0.412), (568, 578, 3, 'minor', 0.407), (18, 31, 1, 'minor', 0.441), (234, 241, 2, 'minor', 0.406), (40, 48, 1, 'minor', 0.435)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 882, 'annotator_id': 6, 'start_span': 1439, 'end_span': 1460, 'severity_level': 'minor', 'confidence': 0.44}, {'annotation_rank': 2, 'translation_id': 882, 'annotator_id': 6, 'start_span': 1538, 'end_span': 1551, 'severity_level': 'minor', 'confidence': 0.423}, {'annotation_rank': 3, 'translation_id': 882, 'annotator_id': 6, 'start_span': 260, 'end_span': 282, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 4, 'translation_id': 882, 'annotator_id': 6, 'start_span': 1524, 'end_span': 1534, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 5, 'translation_id': 882, 'annotator_id': 6, 'start_span': 1489, 'end_span': 1497, 'severity_level': 'minor', 'confidence': 0.402}, {'annotation_rank': 6, 'translation_id': 882, 'annotator_id': 6, 'start_span': 1555, 'end_span': 1561, 'severity_level': 'minor', 'confidence': 0.386}, {'annotation_rank': 7, 'translation_id': 882, 'annotator_id': 6, 'start_span': 492, 'end_span': 501, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 8, 'translation_id': 882, 'annotator_id': 6, 'start_span': 1145, 'end_span': 1152, 'severity_level': 'minor', 'confidence': 0.412}, {'annotation_rank': 9, 'translation_id': 882, 'annotator_id': 6, 'start_span': 568, 'end_span': 578, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 10, 'translation_id': 882, 'annotator_id': 6, 'start_span': 18, 'end_span': 31, 'severity_level': 'minor', 'confidence': 0.441}, {'annotation_rank': 11, 'translation_id': 882, 'annotator_id': 6, 'start_span': 234, 'end_span': 241, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 12, 'translation_id': 882, 'annotator_id': 6, 'start_span': 40, 'end_span': 48, 'severity_level': 'minor', 'confidence': 0.435}]
Sorted Ranks: [3.479, 3.224, 3.084, 2.9139999999999997, 2.891, 2.4379999999999997, 1.98, 1.979, 1.83, 1.296, 1.264, 1.0910000000000002]
Sorted Tuples: [(1439, 1460, 8, 'minor', 0.44), (1538, 1551, 8, 'minor', 0.423), (1524, 1534, 8, 'minor', 0.437), (1489, 1497, 8, 'minor', 0.402), (1555, 1561, 8, 'minor', 0.386), (1145, 1152, 6, 'minor', 0.412), (260, 282, 2, 'minor', 0.406), (492, 501, 2, 'major', 0.46), (568, 578, 3, 'minor', 0.407), (18, 31, 1, 'minor', 0.441), (234, 241, 2, 'minor', 0.406), (40, 48, 1, 'minor', 0.435)]
sorted tuples type:  <class 'list'>
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 882, 'annotator_id': 7, 'start_span': 1439, 'end_span': 1460, 'severity_level': 'minor', 'confidence': 0.44}, {'annotation_rank': 2, 'translation_id': 882, 'annotator_id': 7, 'start_span': 1538, 'end_span': 1551, 'severity_level': 'minor', 'confidence': 0.423}, {'annotation_rank': 3, 'translation_id': 882, 'annotator_id': 7, 'start_span': 1524, 'end_span': 1534, 'severity_level': 'minor', 'confidence': 0.437}, {'annotation_rank': 4, 'translation_id': 882, 'annotator_id': 7, 'start_span': 1489, 'end_span': 1497, 'severity_level': 'minor', 'confidence': 0.402}, {'annotation_rank': 5, 'translation_id': 882, 'annotator_id': 7, 'start_span': 1555, 'end_span': 1561, 'severity_level': 'minor', 'confidence': 0.386}, {'annotation_rank': 6, 'translation_id': 882, 'annotator_id': 7, 'start_span': 1145, 'end_span': 1152, 'severity_level': 'minor', 'confidence': 0.412}, {'annotation_rank': 7, 'translation_id': 882, 'annotator_id': 7, 'start_span': 260, 'end_span': 282, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 8, 'translation_id': 882, 'annotator_id': 7, 'start_span': 492, 'end_span': 501, 'severity_level': 'major', 'confidence': 0.46}, {'annotation_rank': 9, 'translation_id': 882, 'annotator_id': 7, 'start_span': 568, 'end_span': 578, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 10, 'translation_id': 882, 'annotator_id': 7, 'start_span': 18, 'end_span': 31, 'severity_level': 'minor', 'confidence': 0.441}, {'annotation_rank': 11, 'translation_id': 882, 'annotator_id': 7, 'start_span': 234, 'end_span': 241, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 12, 'translation_id': 882, 'annotator_id': 7, 'start_span': 40, 'end_span': 48, 'severity_level': 'minor', 'confidence': 0.435}]

In [588]:
annotations_19057 = create_annotations(result_19057, span_relative_length_L_19057, relative_position_P_spans_19057, 19057)

Sorted Ranks: [2.658, 2.282, 2.167, 2.022, 1.9619999999999997, 1.844, 1.767, 1.763, 1.681, 1.549, 1.534, 1.5159999999999998, 1.484, 1.365, 1.3379999999999999]
Sorted Tuples: [(1205, 1233, 8, 'minor', 0.401), (1147, 1165, 8, 'minor', 0.419), (972, 990, 6, 'minor', 0.417), (635, 655, 5, 'minor', 0.418), (1480, 1483, 9, 'minor', 0.42), (16, 42, 1, 'minor', 0.425), (688, 700, 5, 'minor', 0.414), (704, 716, 5, 'minor', 0.4), (268, 285, 3, 'minor', 0.421), (320, 332, 3, 'minor', 0.434), (159, 174, 2, 'minor', 0.415), (92, 108, 1, 'minor', 0.406), (294, 305, 3, 'minor', 0.421), (0, 12, 1, 'minor', 0.456), (61, 72, 1, 'minor', 0.426)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 1205, 'end_span': 1233, 'severity_level': 'minor', 'confidence': 0.401}, {'annotation_rank': 2, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 1147, 'end_span': 1165, 'severity_level': 'minor', 'confidence': 0.419}, {'annotation_rank': 3, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 972, 'end_span': 990, 'severity_level': 'minor', 'confidence': 0.417}, {'annotation_rank': 4, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 635, 'end_span': 655, 'severity_level': 'minor', 'confidence': 0.418}, {'annotation_rank': 5, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 1480, 'end_span': 1483, 'severity_level': 'minor', 'confidence': 0.42}, {'annotation_rank': 6, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 16, 'end_span': 42, 'severity_level': 'minor', 'confidence': 0.425}, {'annotation_rank': 7, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 688, 'end_span': 700, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 8, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 704, 'end_span': 716, 'severity_level': 'minor', 'confidence': 0.4}, {'annotation_rank': 9, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 268, 'end_span': 285, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 10, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 320, 'end_span': 332, 'severity_level': 'minor', 'confidence': 0.434}, {'annotation_rank': 11, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 159, 'end_span': 174, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 12, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 92, 'end_span': 108, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 13, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 294, 'end_span': 305, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 14, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 0, 'end_span': 12, 'severity_level': 'minor', 'confidence': 0.456}, {'annotation_rank': 15, 'translation_id': 19057, 'annotator_id': 4, 'start_span': 61, 'end_span': 72, 'severity_level': 'minor', 'confidence': 0.426}]
Sorted Ranks: [2.819, 2.461, 2.344, 2.2, 2.142, 2.029, 1.941, 1.923, 1.8619999999999999, 1.743, 1.7089999999999999, 1.682, 1.6649999999999998, 1.5810000000000002, 1.524]
Sorted Tuples: [(1205, 1233, 8, 'minor', 0.401), (1147, 1165, 8, 'minor', 0.419), (972, 990, 6, 'minor', 0.417), (635, 655, 5, 'minor', 0.418), (1480, 1483, 9, 'minor', 0.42), (16, 42, 1, 'minor', 0.425), (688, 700, 5, 'minor', 0.414), (704, 716, 5, 'minor', 0.4), (268, 285, 3, 'minor', 0.421), (320, 332, 3, 'minor', 0.434), (159, 174, 2, 'minor', 0.415), (92, 108, 1, 'minor', 0.406), (294, 305, 3, 'minor', 0.421), (0, 12, 1, 'minor', 0.456), (61, 72, 1, 'minor', 0.426)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 1205, 'end_span': 1233, 'severity_level': 'minor', 'confidence': 0.401}, {'annotation_rank': 2, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 1147, 'end_span': 1165, 'severity_level': 'minor', 'confidence': 0.419}, {'annotation_rank': 3, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 972, 'end_span': 990, 'severity_level': 'minor', 'confidence': 0.417}, {'annotation_rank': 4, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 635, 'end_span': 655, 'severity_level': 'minor', 'confidence': 0.418}, {'annotation_rank': 5, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 1480, 'end_span': 1483, 'severity_level': 'minor', 'confidence': 0.42}, {'annotation_rank': 6, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 16, 'end_span': 42, 'severity_level': 'minor', 'confidence': 0.425}, {'annotation_rank': 7, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 688, 'end_span': 700, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 8, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 704, 'end_span': 716, 'severity_level': 'minor', 'confidence': 0.4}, {'annotation_rank': 9, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 268, 'end_span': 285, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 10, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 320, 'end_span': 332, 'severity_level': 'minor', 'confidence': 0.434}, {'annotation_rank': 11, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 159, 'end_span': 174, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 12, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 92, 'end_span': 108, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 13, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 294, 'end_span': 305, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 14, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 0, 'end_span': 12, 'severity_level': 'minor', 'confidence': 0.456}, {'annotation_rank': 15, 'translation_id': 19057, 'annotator_id': 5, 'start_span': 61, 'end_span': 72, 'severity_level': 'minor', 'confidence': 0.426}]
Sorted Ranks: [3.418, 2.685, 2.5700000000000003, 2.533, 2.496, 2.048, 1.956, 1.952, 1.8469999999999998, 1.83, 1.8289999999999997, 1.738, 1.637, 1.5539999999999998, 1.4909999999999999]
Sorted Tuples: [(1205, 1233, 8, 'minor', 0.401), (1147, 1165, 8, 'minor', 0.419), (972, 990, 6, 'minor', 0.417), (16, 42, 1, 'minor', 0.425), (635, 655, 5, 'minor', 0.418), (268, 285, 3, 'minor', 0.421), (688, 700, 5, 'minor', 0.414), (704, 716, 5, 'minor', 0.4), (92, 108, 1, 'minor', 0.406), (159, 174, 2, 'minor', 0.415), (1480, 1483, 9, 'minor', 0.42), (320, 332, 3, 'minor', 0.434), (294, 305, 3, 'minor', 0.421), (0, 12, 1, 'minor', 0.456), (61, 72, 1, 'minor', 0.426)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 1205, 'end_span': 1233, 'severity_level': 'minor', 'confidence': 0.401}, {'annotation_rank': 2, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 1147, 'end_span': 1165, 'severity_level': 'minor', 'confidence': 0.419}, {'annotation_rank': 3, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 972, 'end_span': 990, 'severity_level': 'minor', 'confidence': 0.417}, {'annotation_rank': 4, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 16, 'end_span': 42, 'severity_level': 'minor', 'confidence': 0.425}, {'annotation_rank': 5, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 635, 'end_span': 655, 'severity_level': 'minor', 'confidence': 0.418}, {'annotation_rank': 6, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 268, 'end_span': 285, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 7, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 688, 'end_span': 700, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 8, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 704, 'end_span': 716, 'severity_level': 'minor', 'confidence': 0.4}, {'annotation_rank': 9, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 92, 'end_span': 108, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 10, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 159, 'end_span': 174, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 11, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 1480, 'end_span': 1483, 'severity_level': 'minor', 'confidence': 0.42}, {'annotation_rank': 12, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 320, 'end_span': 332, 'severity_level': 'minor', 'confidence': 0.434}, {'annotation_rank': 13, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 294, 'end_span': 305, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 14, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 0, 'end_span': 12, 'severity_level': 'minor', 'confidence': 0.456}, {'annotation_rank': 15, 'translation_id': 19057, 'annotator_id': 6, 'start_span': 61, 'end_span': 72, 'severity_level': 'minor', 'confidence': 0.426}]
Sorted Ranks: [3.1950000000000003, 2.782, 2.6769999999999996, 2.5540000000000003, 2.1919999999999997, 1.9769999999999999, 1.971, 1.614, 1.6139999999999999, 1.515, 1.4340000000000002, 1.397, 1.335, 1.137, 1.125]
Sorted Tuples: [(1205, 1233, 8, 'minor', 0.401), (1147, 1165, 8, 'minor', 0.419), (1480, 1483, 9, 'minor', 0.42), (972, 990, 6, 'minor', 0.417), (635, 655, 5, 'minor', 0.418), (704, 716, 5, 'minor', 0.4), (688, 700, 5, 'minor', 0.414), (16, 42, 1, 'minor', 0.425), (268, 285, 3, 'minor', 0.421), (320, 332, 3, 'minor', 0.434), (294, 305, 3, 'minor', 0.421), (159, 174, 2, 'minor', 0.415), (92, 108, 1, 'minor', 0.406), (61, 72, 1, 'minor', 0.426), (0, 12, 1, 'minor', 0.456)]
sorted tuples type:  <class 'list'>
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 1205, 'end_span': 1233, 'severity_level': 'minor', 'confidence': 0.401}, {'annotation_rank': 2, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 1147, 'end_span': 1165, 'severity_level': 'minor', 'confidence': 0.419}, {'annotation_rank': 3, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 1480, 'end_span': 1483, 'severity_level': 'minor', 'confidence': 0.42}, {'annotation_rank': 4, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 972, 'end_span': 990, 'severity_level': 'minor', 'confidence': 0.417}, {'annotation_rank': 5, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 635, 'end_span': 655, 'severity_level': 'minor', 'confidence': 0.418}, {'annotation_rank': 6, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 704, 'end_span': 716, 'severity_level': 'minor', 'confidence': 0.4}, {'annotation_rank': 7, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 688, 'end_span': 700, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 8, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 16, 'end_span': 42, 'severity_level': 'minor', 'confidence': 0.425}, {'annotation_rank': 9, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 268, 'end_span': 285, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 10, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 320, 'end_span': 332, 'severity_level': 'minor', 'confidence': 0.434}, {'annotation_rank': 11, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 294, 'end_span': 305, 'severity_level': 'minor', 'confidence': 0.421}, {'annotation_rank': 12, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 159, 'end_span': 174, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 13, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 92, 'end_span': 108, 'severity_level': 'minor', 'confidence': 0.406}, {'annotation_rank': 14, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 61, 'end_span': 72, 'severity_level': 'minor', 'confidence': 0.426}, {'annotation_rank': 15, 'translation_id': 19057, 'annotator_id': 7, 'start_span': 0, 'end_span': 12, 'severity_level': 'minor', 'confidence': 0.456}]

In [590]:
annotations_19251 = create_annotations(result_19251, span_relative_length_L_19251, relative_position_P_spans_19251, 19251)

Sorted Ranks: [2.8200000000000003, 2.3449999999999998, 2.268, 2.1350000000000002, 2.135, 1.997, 1.928, 1.7690000000000001, 1.698, 1.5379999999999998, 1.537, 1.533, 1.379, 1.2060000000000002, 1.007]
Sorted Tuples: [(768, 788, 6, 'major', 0.374), (535, 558, 5, 'minor', 0.436), (1028, 1041, 7, 'minor', 0.399), (743, 758, 6, 'minor', 0.407), (1114, 1122, 7, 'minor', 0.414), (822, 833, 6, 'minor', 0.38), (854, 862, 6, 'minor', 0.415), (409, 421, 4, 'minor', 0.439), (587, 594, 5, 'minor', 0.443), (461, 468, 4, 'minor', 0.384), (340, 348, 3, 'minor', 0.436), (27, 41, 1, 'minor', 0.422), (171, 179, 2, 'minor', 0.414), (17, 23, 1, 'minor', 0.451), (11, 13, 1, 'minor', 0.431)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 768, 'end_span': 788, 'severity_level': 'major', 'confidence': 0.374}, {'annotation_rank': 2, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 535, 'end_span': 558, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 3, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 1028, 'end_span': 1041, 'severity_level': 'minor', 'confidence': 0.399}, {'annotation_rank': 4, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 743, 'end_span': 758, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 5, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 1114, 'end_span': 1122, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 6, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 822, 'end_span': 833, 'severity_level': 'minor', 'confidence': 0.38}, {'annotation_rank': 7, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 854, 'end_span': 862, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 8, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 409, 'end_span': 421, 'severity_level': 'minor', 'confidence': 0.439}, {'annotation_rank': 9, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 587, 'end_span': 594, 'severity_level': 'minor', 'confidence': 0.443}, {'annotation_rank': 10, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 461, 'end_span': 468, 'severity_level': 'minor', 'confidence': 0.384}, {'annotation_rank': 11, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 340, 'end_span': 348, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 12, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 27, 'end_span': 41, 'severity_level': 'minor', 'confidence': 0.422}, {'annotation_rank': 13, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 171, 'end_span': 179, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 14, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 17, 'end_span': 23, 'severity_level': 'minor', 'confidence': 0.451}, {'annotation_rank': 15, 'translation_id': 19251, 'annotator_id': 4, 'start_span': 11, 'end_span': 13, 'severity_level': 'minor', 'confidence': 0.431}]
Sorted Ranks: [2.714, 2.541, 2.427, 2.309, 2.302, 2.137, 2.1029999999999998, 1.968, 1.9009999999999998, 1.733, 1.715, 1.682, 1.553, 1.417, 1.1979999999999997]
Sorted Tuples: [(768, 788, 6, 'major', 0.374), (535, 558, 5, 'minor', 0.436), (1028, 1041, 7, 'minor', 0.399), (1114, 1122, 7, 'minor', 0.414), (743, 758, 6, 'minor', 0.407), (822, 833, 6, 'minor', 0.38), (854, 862, 6, 'minor', 0.415), (409, 421, 4, 'minor', 0.439), (587, 594, 5, 'minor', 0.443), (340, 348, 3, 'minor', 0.436), (27, 41, 1, 'minor', 0.422), (461, 468, 4, 'minor', 0.384), (171, 179, 2, 'minor', 0.414), (17, 23, 1, 'minor', 0.451), (11, 13, 1, 'minor', 0.431)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 768, 'end_span': 788, 'severity_level': 'major', 'confidence': 0.374}, {'annotation_rank': 2, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 535, 'end_span': 558, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 3, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 1028, 'end_span': 1041, 'severity_level': 'minor', 'confidence': 0.399}, {'annotation_rank': 4, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 1114, 'end_span': 1122, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 5, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 743, 'end_span': 758, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 6, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 822, 'end_span': 833, 'severity_level': 'minor', 'confidence': 0.38}, {'annotation_rank': 7, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 854, 'end_span': 862, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 8, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 409, 'end_span': 421, 'severity_level': 'minor', 'confidence': 0.439}, {'annotation_rank': 9, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 587, 'end_span': 594, 'severity_level': 'minor', 'confidence': 0.443}, {'annotation_rank': 10, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 340, 'end_span': 348, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 11, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 27, 'end_span': 41, 'severity_level': 'minor', 'confidence': 0.422}, {'annotation_rank': 12, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 461, 'end_span': 468, 'severity_level': 'minor', 'confidence': 0.384}, {'annotation_rank': 13, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 171, 'end_span': 179, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 14, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 17, 'end_span': 23, 'severity_level': 'minor', 'confidence': 0.451}, {'annotation_rank': 15, 'translation_id': 19251, 'annotator_id': 5, 'start_span': 11, 'end_span': 13, 'severity_level': 'minor', 'confidence': 0.431}]
Sorted Ranks: [3.21, 3.105, 2.593, 2.547, 2.243, 2.2350000000000003, 2.051, 2.036, 1.902, 1.762, 1.645, 1.6019999999999999, 1.4869999999999999, 1.227, 0.854]
Sorted Tuples: [(768, 788, 6, 'major', 0.374), (535, 558, 5, 'minor', 0.436), (1028, 1041, 7, 'minor', 0.399), (743, 758, 6, 'minor', 0.407), (1114, 1122, 7, 'minor', 0.414), (822, 833, 6, 'minor', 0.38), (409, 421, 4, 'minor', 0.439), (854, 862, 6, 'minor', 0.415), (27, 41, 1, 'minor', 0.422), (587, 594, 5, 'minor', 0.443), (340, 348, 3, 'minor', 0.436), (461, 468, 4, 'minor', 0.384), (171, 179, 2, 'minor', 0.414), (17, 23, 1, 'minor', 0.451), (11, 13, 1, 'minor', 0.431)]
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 768, 'end_span': 788, 'severity_level': 'major', 'confidence': 0.374}, {'annotation_rank': 2, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 535, 'end_span': 558, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 3, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 1028, 'end_span': 1041, 'severity_level': 'minor', 'confidence': 0.399}, {'annotation_rank': 4, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 743, 'end_span': 758, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 5, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 1114, 'end_span': 1122, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 6, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 822, 'end_span': 833, 'severity_level': 'minor', 'confidence': 0.38}, {'annotation_rank': 7, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 409, 'end_span': 421, 'severity_level': 'minor', 'confidence': 0.439}, {'annotation_rank': 8, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 854, 'end_span': 862, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 9, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 27, 'end_span': 41, 'severity_level': 'minor', 'confidence': 0.422}, {'annotation_rank': 10, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 587, 'end_span': 594, 'severity_level': 'minor', 'confidence': 0.443}, {'annotation_rank': 11, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 340, 'end_span': 348, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 12, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 461, 'end_span': 468, 'severity_level': 'minor', 'confidence': 0.384}, {'annotation_rank': 13, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 171, 'end_span': 179, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 14, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 17, 'end_span': 23, 'severity_level': 'minor', 'confidence': 0.451}, {'annotation_rank': 15, 'translation_id': 19251, 'annotator_id': 6, 'start_span': 11, 'end_span': 13, 'severity_level': 'minor', 'confidence': 0.431}]
Sorted Ranks: [2.956, 2.852, 2.788, 2.534, 2.4909999999999997, 2.416, 2.373, 1.929, 1.8570000000000002, 1.668, 1.57, 1.315, 1.2759999999999998, 0.9800000000000001, 0.776]
Sorted Tuples: [(768, 788, 6, 'major', 0.374), (1028, 1041, 7, 'minor', 0.399), (1114, 1122, 7, 'minor', 0.414), (535, 558, 5, 'minor', 0.436), (743, 758, 6, 'minor', 0.407), (822, 833, 6, 'minor', 0.38), (854, 862, 6, 'minor', 0.415), (587, 594, 5, 'minor', 0.443), (409, 421, 4, 'minor', 0.439), (461, 468, 4, 'minor', 0.384), (340, 348, 3, 'minor', 0.436), (27, 41, 1, 'minor', 0.422), (171, 179, 2, 'minor', 0.414), (17, 23, 1, 'minor', 0.451), (11, 13, 1, 'minor', 0.431)]
sorted tuples type:  <class 'list'>
annotation_list_of_dicts:  [{'annotation_rank': 1, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 768, 'end_span': 788, 'severity_level': 'major', 'confidence': 0.374}, {'annotation_rank': 2, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 1028, 'end_span': 1041, 'severity_level': 'minor', 'confidence': 0.399}, {'annotation_rank': 3, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 1114, 'end_span': 1122, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 4, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 535, 'end_span': 558, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 5, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 743, 'end_span': 758, 'severity_level': 'minor', 'confidence': 0.407}, {'annotation_rank': 6, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 822, 'end_span': 833, 'severity_level': 'minor', 'confidence': 0.38}, {'annotation_rank': 7, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 854, 'end_span': 862, 'severity_level': 'minor', 'confidence': 0.415}, {'annotation_rank': 8, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 587, 'end_span': 594, 'severity_level': 'minor', 'confidence': 0.443}, {'annotation_rank': 9, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 409, 'end_span': 421, 'severity_level': 'minor', 'confidence': 0.439}, {'annotation_rank': 10, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 461, 'end_span': 468, 'severity_level': 'minor', 'confidence': 0.384}, {'annotation_rank': 11, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 340, 'end_span': 348, 'severity_level': 'minor', 'confidence': 0.436}, {'annotation_rank': 12, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 27, 'end_span': 41, 'severity_level': 'minor', 'confidence': 0.422}, {'annotation_rank': 13, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 171, 'end_span': 179, 'severity_level': 'minor', 'confidence': 0.414}, {'annotation_rank': 14, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 17, 'end_span': 23, 'severity_level': 'minor', 'confidence': 0.451}, {'annotation_rank': 15, 'translation_id': 19251, 'annotator_id': 7, 'start_span': 11, 'end_span': 13, 'severity_level': 'minor', 'confidence': 0.431}]

In [583]:
def populate_annotations(annotations):
    import json
    import mysql.connector
    from mysql.connector import Error

    # Database configuration
    DB_CONFIG = {
        'host': 'localhost',
        'user': 'root',
        'password': '',
        'database': 'matos',
        'port': 3306
    }

    # JSON file path

    def populate_annotations():
        try:
            # Load JSON data
        
            
            # Connect to database
            connection = mysql.connector.connect(**DB_CONFIG)
            cursor = connection.cursor()
            
            # SQL insert query for Annotation table
            insert_query = """
            INSERT INTO Annotation (
                annotation_rank, 
                translation_id, 
                annotator_id, 
                start_span, 
                end_span, 
                severity_level, 
                confidence
            ) VALUES (%s, %s, %s, %s, %s, %s, %s)
            """
            
            # Prepare data for insertion
            records = []
            for ann in annotations:
                records.append((
                    ann['annotation_rank'],
                    ann['translation_id'],
                    ann['annotator_id'],
                    ann['start_span'],
                    ann['end_span'],
                    ann['severity_level'],
                    ann['confidence']
                ))
            
            # Execute batch insert
            cursor.executemany(insert_query, records)
            connection.commit()
            print(f"Successfully inserted {len(records)} annotations")
            
        except Error as e:
            print(f"Database error: {e}")
            if 'connection' in locals() and connection.is_connected():
                connection.rollback()
        except Exception as e:
            print(f"General error: {e}")
        finally:
            if 'connection' in locals() and connection.is_connected():
                cursor.close()
                connection.close()

    if __name__ == "__main__":
        populate_annotations()

### now populate the table

In [585]:
for annotation in annotations_19823:
    populate_annotations(annotation)

Successfully inserted 13 annotations
Successfully inserted 13 annotations
Successfully inserted 13 annotations
Successfully inserted 13 annotations

In [587]:
for annotation in annotations_882:
    populate_annotations(annotation)

Successfully inserted 12 annotations
Successfully inserted 12 annotations
Successfully inserted 12 annotations
Successfully inserted 12 annotations

In [589]:
for annotation in annotations_19057:
    populate_annotations(annotation)

Successfully inserted 15 annotations
Successfully inserted 15 annotations
Successfully inserted 15 annotations
Successfully inserted 15 annotations

In [591]:
for annotation in annotations_19251:

    populate_annotations(annotation)

Successfully inserted 15 annotations
Successfully inserted 15 annotations
Successfully inserted 15 annotations
Successfully inserted 15 annotations