### Initial inspection of Eng to cz dataset

In this inspection, we get these important information:

1. If the 20 documents in this dataset have desired mean length as our en-fr experiments. We filter out **8 documents** as the rest have either document lengths exceeding 2000 characters or below 1300 characters.

[3, 5, 6, 7, 13, 17, 18, 19] - document number / Translation_id

[1785, 1575, 1367, 1625, 1525, 1472, 1523, 1356] / doc lengths

2. We calculate the spans using XCOMET custom class and we have [73, 59, 41, 32, 90, 74, 42, 25] spans for each document. We can work with documents with spans 41, 32, 42, and 25 as they have reasonable many spans, but we have to be careful if the spans have at least 4 characters.

3. We do not create the dataset here for our purpose, we will build it in **statistics_translator_en_cz.ipynb** file.

**here its xcomet_frn_czech_both and in terminal its xcomet**

how to activate the env in the terminal:
conda activate envs/xcomet/
(xcomet) Singularity>

In [1]:
from datasets import load_dataset
data_wmt = load_dataset("zouharvi/optimal-reference-translations", 'ort_wmt')["train"]

In [2]:
data_wmt

Dataset({
    features: ['ref', 'systems', 'src'],
    num_rows: 160
})

In [3]:
print(data_wmt)

Dataset({
    features: ['ref', 'systems', 'src'],
    num_rows: 160
})

In [4]:
print(data_wmt.column_names)

['ref', 'systems', 'src']

In [5]:
print(data_wmt[0])

{'ref': {'R1': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_layman_cardiff': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_layman_funafuti': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_layman_hanoi': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_layman_washington': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_professional_ankara': 'Vláda během čtvrté části zátahu na nepoctivé státní zaměstnance obviněné z korupce a zneužití úřední moci nařídila nucený odchod do důchodu dalším 15 daňovým úředníkům.', 'R1_pe_professional_caracas': 'Vláda odvolala dalších 15 daňových úředníků v rámci čtvrtého balíčku opatření proti nepoctivým úředníkům obviněným z korupce a dalších nekalých praktik.', 'R1_pe_professional_lome': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_professional_tiraspol': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého kola zátahu proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_student_kampala': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R1_pe_student_montevideo': 'V rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik přikázala Indická vláda dalším 15 daňovým úředníkům, aby odešli do důchodu.', 'R1_pe_student_sahara': 'Indická vláda přikázala odchod do důchodu dalším patnácti daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R2': 'Vláda povinně poslala do důchodu dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti špatným úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_layman_cardiff': 'Vláda povinně poslala do důchodu dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti špatným úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_layman_funafuti': 'Vláda povinně poslala do důchodu dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_layman_hanoi': 'Vláda povinně poslala do důchodu dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti špatným úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_layman_washington': 'Vláda povinně poslala do důchodu dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti nepoctivým úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_professional_ankara': 'Vláda během čtvrté části zátahu na nepoctivé státní zaměstnance obviněné z korupce a zneužití úřední moci nařídila nucený odchod do důchodu dalším 15 daňovým úředníkům.', 'R2_pe_professional_caracas': 'Vláda odvolala dalších 15 daňových úředníků v rámci čtvrté vlny svého zásahu proti nepoctivým úředníkům obviněným z korupce a dalších nekalých praktik.', 'R2_pe_professional_lome': 'Vláda povinně poslala do penze dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_professional_tiraspol': 'Vláda povinně poslala do důchodu dalších 15 daňových úředníků ve čtvrté vlně svého zásahu proti špatným úředníkům obviněným z korupce a dalších profesních pochybení.', 'R2_pe_student_kampala': 'Vláda ve čtvrté vlně svého zásahu proti úředníkům obviněným z korupce a dalších profesních pochyben povinně poslala do důchodu dalších 15 daňových úředníků', 'R2_pe_student_montevideo': 'Indická vláda ve čtvrté vlně svého zásahu proti úředníkům obviněným z korupce a dalších profesních pochybení povinně poslala do důchodu dalších 15 daňových úředníků .', 'R2_pe_student_sahara': 'Indická vláda ve čtvrté vlně svého zásahu proti úředníkům obviněným z korupce a dalších profesních pochybení poslala dalších patnáct daňových úředníků do povinného důchodu.', 'R3': 'Vláda odvolala 15 dalších daňových úředníků ve čtvrté tranši stíhání vykyvujících úředníků obviněných z korupce a dalších nezákonných praktik.', 'R3_pe_layman_cardiff': 'Vláda odvolala 15 dalších daňových úředníků ve čtvrté tranši stíhání úředníků obviněných z korupce a dalších nezákonných praktik.', 'R3_pe_layman_funafuti': 'Vláda nařídila povinný odchod do důchodu pro 15 dalších daňových úředníků ve čtvrté části opatření ke stíhání úředníků obviněných z korupce a dalších nezákonných praktik.', 'R3_pe_layman_hanoi': 'Vláda odvolala 15 dalších daňových úředníků ve čtvrté tranši stíhání vykyvujících úředníků obviněných z korupce a dalších nezákonných praktik.', 'R3_pe_layman_washington': 'Vláda odvolala dalších 15 daňových úředníků ve čtvrté tranši stíhání nepoctivých úředníků obviněných z korupce a dalších nezákonných praktik.', 'R3_pe_professional_ankara': 'Vláda během čtvrté části zátahu na nepoctivé státní zaměstnance obviněné z korupce a zneužití úřední moci nařídila nucený odchod do důchodu dalším 15 daňovým úředníkům.', 'R3_pe_professional_caracas': 'Vláda odvolala 15 dalších daňových úředníků ve čtvrtém kole zásahu proti nepoctivým úředníkům obviněných z korupce a dalších nekalých praktik.', 'R3_pe_professional_lome': 'Vláda odvolala 15 dalších daňových úředníků ve čtvrté vlně stíhání úředníků obviněných z korupce a dalších nezákonných praktik.', 'R3_pe_professional_tiraspol': 'Vláda odvolala 15 dalších daňových úředníků ve čtvrté vlně zásahů proti úředníkům obviněným z korupce a dalších nezákonných praktik.', 'R3_pe_student_kampala': 'Vláda ve čtvrté vlně stíhání úředníků obviněných z korupce a dalších nezákonných praktik odvolala dalších 15 daňových úředníků.', 'R3_pe_student_montevideo': 'Indická vláda odvolala ve čtvrté vlně stíhání úředníků obviněných z korupce a jiných nezákonných praktik dalších 15 daňových úředníků.', 'R3_pe_student_sahara': 'Indická vláda ve čtvrté fázi stíhání úředníků obviněných z korupce a dalších nezákonných praktik odvolala patnáct dalších daňových úředníků.', 'R4': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_layman_cardiff': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_layman_funafuti': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_layman_hanoi': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_layman_washington': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_professional_ankara': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_professional_caracas': 'Vláda odvolala dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nekalých praktik.', 'R4_pe_professional_lome': 'Vláda nařídila okamžitě poslat do penze dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_professional_tiraspol': 'Vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_student_kampala': 'Vláda nařídila poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_student_montevideo': 'Indická vláda nařídila okamžitě poslat do důchodu dalších 15 daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.', 'R4_pe_student_sahara': 'Indická vláda nařídila nucený odchod do důchodu dalších patnácti daňových úředníků v rámci čtvrtého kola zátahu na nepoctivé státní zaměstnance obviněné z korupce a dalších nezákonných praktik.'}, 'systems': {'CUNI-DocTransformer.1450': {'score': 0.768625609971165, 'tgt': 'Vláda poslala do penze dalších 15 daňových úředníků ve čtvrté části svého zátahu proti zatoulaným úředníkům obviněným z korupce a dalších nekalých praktik.'}, 'CUNI-T2T-2018.1071': {'score': -0.287179215917026, 'tgt': 'Vláda ve čtvrté tranši svého zátahu proti pochybným úředníkům obviněným z korupce a dalších nekalých praktik povinně odvolala dalších 15 daňových úředníků.'}, 'CUNI-Transformer.1080': {'score': 0.33815971885602303, 'tgt': 'Vláda nuceně propustila dalších 15 daňových úředníků ve čtvrté tranši svého zátahu proti chybujícím úředníkům obviněným z korupce a dalších nekalých praktik.'}, 'OPPO.1121': {'score': 1.90938792054803, 'tgt': 'Vláda ve čtvrté tranši svého zásahu proti zbloudilým úředníkům obviněným z korupce a dalších nekalých praktik nuceně propustila dalších 15 daňových úředníků.'}, 'Online-A.1573': {'score': -0.46360315621142206, 'tgt': 'Vláda povinně odešel 15 více daňových úředníků ve čtvrté tranši svého zákroku proti potulný úředníků obviněných z korupce a dalších nekalých praktik.'}, 'Online-B.1589': {'score': -0.961245691263453, 'tgt': 'Vláda povinně odešla do důchodu dalších 15 daňových úředníků ve čtvrté tranši svého zákroku proti errancujícím úředníkům obviněným z korupce a jiných nezákonných praktik.'}, 'Online-G.1555': {'score': 0.133070704619838, 'tgt': 'Vláda nuceně poslala do důchodu dalších 15 daňových úředníků ve čtvrté části svého zákroku proti zbloudilým úředníkům obviněným z korupce a jiných pochybení.'}, 'Online-Z.1630': {'score': 0.11005665393442401, 'tgt': 'Vláda povinně vysloužila 15 dalších daňových úředníků ve čtvrtém tranši svého zásahu proti potulným úředníkům obviněným z korupce a dalších zanedbaných praktik.'}, 'SRPOL.522': {'score': -0.13950326931169, 'tgt': 'Vláda povinně odvolala dalších 15 daňových úředníků ve čtvrté části svého zásahu proti chybujícím úředníkům obviněným z korupce a dalších nekalých praktik.'}, 'UEDIN-CUNI.1482': {'score': 0.0, 'tgt': 'Vláda povinně odvolala dalších 15 daňových úředníků ve čtvrté tranši zátahu proti potulným úředníkům obviněným z korupce a dalších nekalých praktik.'}, 'eTranslation.1048': {'score': 0.444703520638052, 'tgt': 'Vláda ve čtvrté tranši svého zákroku proti chybujícím úředníkům obviněným z korupce a dalších nekalých praktik nuceně odvolala dalších 15 daňových úředníků.'}, 'ref': {'score': 0.282610797572385, 'tgt': 'Vláda přikázala odchod do důchodu dalším 15 daňovým úředníkům v rámci čtvrtého balíčku opatření proti úředníkům obviněným z korupce a dalších nezákonných praktik.'}, 'zlabs-nlp.1151': {'score': -1.20533986295174, 'tgt': 'Vláda povinně odešel do důchodu 15 dalších daňových důstojníků ve čtvrtém tranši jeho praskání na vymazané úředníky obviněné z korupce a dalších malpraktices.'}}, 'src': 'The government has compulsorily retired 15 more tax officers in the fourth tranche of its crackdown on errant officials accused of corruption and other malpractices.'}

In [6]:
count = 1
for data in data_wmt:
    print("line no: ", count)
    print(data["src"])
    count += 1

line no:  1
The government has compulsorily retired 15 more tax officers in the fourth tranche of its crackdown on errant officials accused of corruption and other malpractices.
line no:  2
The Central Board of Indirect Taxes and Customs (CBIC) -- the agency that oversees GST and import tax collections -- compulsorily retired 15 senior officers under Fundamental Rule 56 (J) on corruption and other charges, official sources said.
line no:  3
Since June, this is the fourth round of sacking of corrupt tax officials. In the previous three rounds, 49 high ranking tax officers, including 12 from the Central Board of Direct Taxes (CBDT), were compulsorily retired.
line no:  4
Sources said the action was in line with Prime Minister Narendra Modi's address to the nation from the ramparts of the Red Fort when he had said some black sheep in the tax administration may have misused their powers and harassed taxpayers, either by targeting honest assesses or taking excessive action for minor or procedural violations.
line no:  5
"We have recently taken the bold step of compulsorily retiring a significant number of tax officials, and we will not tolerate this type of behaviour," he had said.
line no:  6
Nearly half of the officials retired were those who were arrested by the CBI for allegedly receiving illegal gratification. One of them was caught accepting a bribe of Rs 15,000. One official is accused of having assets disproportionate to his known source of income.
line no:  7
In June, the government had compulsorily retired 15 commissioner-level officials of CBIC on charges of corruption, collecting and giving bribes, smuggling and even criminal conspiracy. Prior to that, the government had compulsorily retired 12 senior IRS officials from the Income Tax department over charges of corruption, sexual harassment, disproportionate assets under Rule 56 (J) of the Central Civil Services (Pension) Rules.
line no:  8
In August, the government compulsorily retired 22 CBIC officials. The Rule 56 (J) of Central Civil Services (Pension) Rules, 1972 provides for periodical review of the performance of government servants with a view to ascertain whether they should be retained in service or retired in public interest.
line no:  9
A woman in Maine got 500 letters from United Healthcare within five days
line no:  10
Stephanie Lay said she found the piles of letters from the insurance company stashed in her mailbox between Thursday and Monday.
line no:  11
"A week ago Thursday was the first wave of letters, I got 46 letters," she told CNN. "I immediately called United Healthcare insurance and told them I received 46 letters of the same letter."
line no:  12
And the letters just kept coming, piling up to more than 500 by Monday.
line no:  13
They were addressed to her son, who has autism and lives in a private care facility, she said. But instead of her son's name inside when you opened them, the letters said Dear Maine's Department of Health and Human Services -- in Cincinnati, she told local media.
line no:  14
The letters were about a $54 or $0 healthcare claim that United Healthcare said is not covered, Lay said.
line no:  15
When she asked United Healthcare why she was receiving a mountain of letters, she was told it was a coding issue, she said.
line no:  16
In a statement, United Healthcare told CNN it's working to resolve the issue but it cannot provide details due to privacy requirements.
line no:  17
Using data and artificial intelligence to try and boost revenues is part of HSBC's broader push to squeeze more out of its large physical network and client data, a key priority for interim Chief Executive Noel Quinn.
line no:  18
"It's one of the first commercial uses of investment in financial crime prevention, and the business we're getting in this way is inherently lower risk and quicker to win," said Stuart Nivison, HSBC's global head of client network banking.
line no:  19
HSBC declined to comment on how much it expects to make from the new system but said the broader "network income" initiative has already yielded hundreds of millions of dollars in additional revenue.
line no:  20
The drive is an important part of the bank's efforts to defend its global presence at a time when some analysts and investors are saying it should shrink or exit markets like the United States where it makes returns below its cost of capital.
line no:  21
HSBC was forced to invest hundreds of millions of dollars in financial crime compliance as part of a $1.9 billion settlement in 2012 with U.S. authorities over the bank's failure to prevent money laundering by drug cartels though its Mexican unit.
line no:  22
The system works by mapping individual customers" and companies ties to each other and then looking for unusual patterns of transactions or unearthing previously unknown connections between those entities.
line no:  23
That system has already freed up more than 400 staff to go from manually checking transactions and records to client-facing roles where they can spend time helping customers, said Adrian Rigby, chief operating officer of HSBC's trade business.
line no:  24
HSBC's Nivison said the lightbulb moment was realizing the tool could be repurposed to look for "green flags" of attractive potential clients rather than "red flags" of wrongdoing.
line no:  25
Shortly after the arrest, a search warrant was executed at a home where officers seized a number of items relevant to the investigation.
line no:  26
The man pleaded guilty to seven charges involving the attack and a further three charges over the grooming and sexual abuse of another girl, aged 11, between August 2016 and April 2017.
line no:  27
The 12-year-old victim had been walking along a track when she looked back and saw him suddenly emerge from the bushes armed with a large tree branch and a knife.
line no:  28
An example of a camouflage Ghillie suit the man used.
line no:  29
When she pleaded "stop, stop, stop," he put her in a headlock and forced her into the scrub.
line no:  30
The man told the girl: "Shhh, don't scream. Don't scream or I'll have to hurt you."
line no:  31
Holding the knife in his right hand, he tied her hands and feet with cable ties before lashing her to the tree and abusing her for almost an hour. After he cut her loose, the girl ran crying hysterically to school.
line no:  32
The man arrived at work about 9.30am after failing to reply to several text messages and phone calls from colleagues.
line no:  33
Stem cells of 56 child cancer patients lost at Children's Hospital after freezer malfunction
line no:  34
A freezer malfunction at Children's Hospital Los Angeles resulted in the loss of 56 children's blood stem cells that were harvested at the beginning of each patient's oncology therapy and stored in the event they could prove useful in the future.
line no:  35
"We apologize for any distress or confusion that this has caused our patients and their families," the hospital wrote in a statement. "If you have not received a letter or phone call from our team, your child is not impacted."
line no:  36
All but one patient had gone through initial therapy. That patient did require the recollection of stem cells, chief medical officer James Stein said.
line no:  37
A letter sent to families earlier in September informing them of the loss was accidentally addressed to the children - rather than the parents. The hospital has also apologized to parents for the messaging oversight.
line no:  38
The hospital said that the loss of stem cells, which had been placed in long-term storage, has not jeopardized any child's health. The hospital has also offered to assist families who want to harvest again. But the process can be grueling.
line no:  39
One of the patients described it as "painful." Sean Anderson Corona, 13, underwent stem cell therapy when he was diagnosed with Stage 4 Neuroblastoma - a cancer often found in the adrenal glands. The boy was hooked up to machines for a daylong process that collects the stem cells from the blood. The blood is then reinfused back into the body.
line no:  40
"I would try to sleep and my body would just start shaking, and then I just started to freak out and I'd start crying," Corona told ABC-7.
line no:  41
Three Scottish students named among Europe's best
line no:  42
Three University of Dundee students have been named regional winners as top graduates in Europe.
line no:  43
The University of Dundee students were named as top graduates in their respective fields in Europe in the 2019 Global Undergraduate Awards, whilst five other students from the same university were praised by the judges.
line no:  44
Scott Sheldrick, who graduated in Molecular Genetics, won the Europe award for Life Sciences, Chester Cornford studied MSc Mental Health Nursing and was awarded the Nursing, Midwifery & Allied Healthcare prize, whilst Lola Knibb won the Visual Arts award.
line no:  45
Although all three made it through to the global final, they lost out in the final round to strong competition from some of the 3,500 entrants from across the world.
line no:  46
Professor Blair Grubb, Vice-Principal (Education) at the University, said: "To get to this stage, our students and graduates faced competition from peers attending some of the world's top universities.
line no:  47
"The Undergraduate Awards are fiercely contested by thousands of students around the world and it is a great reflection of the quality of our students, and the education they receive here, that Dundee is so strongly represented amongst the prize winners.
line no:  48
"I would like to offer my warmest congratulations to Scott, Chester and Lola on this fantastic achievement, alongside the other Dundee representatives who were highly commended."
line no:  49
LNG investments hit record in 2019 & the biggest growth is coming from China
line no:  50
Investments in liquefied natural gas since the start of the year have hit an all-time high of $50 billion, the International Energy Agency's head, Fatih Birol, told an industry conference.
line no:  51
"This year, 2019 already broke the highest amount of (final investment decisions) for the first time ever, $50 billion," Birol told the LNG Producer-Consumer conference in Tokyo, as quoted by Reuters.
line no:  52
Unsurprisingly, the driver of this growth in investments is growing demand for the fuel in Asia, with China still expected to overtake Japan as the world's top importer of LNG.
line no:  53
"The biggest growth is coming from China. In the next five years, about one-third of global LNG demand will come from China alone," Birol said. He added that in five years, China will become the largest importer of the fuel.
line no:  54
As for the growth in investments, there are no surprises there, either. The bulk of these has been made in the United States and Canada.
line no:  55
In a December 2018 report the Energy Information Administration said it expected the United States" LNG export capacity to double by the end of this year to 8.9 billion cu ft daily. This will make the US the third-largest exporter of LNG in terms of capacity after Qatar and Australia. By 2030, US LNG exports are estimated to reach 17 billion cu ft daily, from some 3 billion cu ft at the start of 2019.
line no:  56
In Canada, there is just one LNG project under development right now - LNG Canada - but it could have a final capacity of 28 million tons of the fuel annually. The US$31-billion project is led by Shell, with minority participants including Petronas, PetroChina, Mitsubishi, and Kogas.
line no:  57
Military Sees Frustrating Trend As Suicides Spike
line no:  58
Military suicides surged this year to a record high among active duty troops, continuing a deadly trend that Pentagon officials say is frustrating and they are struggling to counter.
line no:  59
The Army, Navy and Marine Corps all saw the rate of suicides go up as well as the overall numbers, with only the Air Force showing a decrease, according to data released by the Pentagon Thursday. Suicides among members of the Reserves and the National Guard also grew.
line no:  60
The difficulties involved in identifying service members with possible problems and finding ways to prevent suicides were underscored earlier this month when the Navy reported that three crew members who served on the USS George H.W. Bush took their own lives within a week.
line no:  61
Asked about the deaths in the crew of the aircraft carrier, Defense Secretary Mark Esper said, "I wish I could tell you we have an answer to prevent further, future suicides in the Armed Services. We don't. We are caught up in what some call a national epidemic of suicide among our youth."
line no:  62
The number of suicides across the military increased from 511 in 2017 to 541 in 2018. According to the Pentagon, the most at-risk population is young enlisted men, and at least 60 percent of the time they chose a gun as their suicide method. Army suicides went from 114 to 139, while the Marines went from 43 to 58 and the Navy went from 65 to 68. The Air Force dipped from 63 to 60.
line no:  63
"Our numbers are not moving in the right direction," said Elizabeth Van Winkle, director of the Pentagon's office of force resiliency. She said that most of the military rates are comparable to civilians, but added, "that's hardly comforting."
line no:  64
Military and defense leaders expressed dismay and a resolve to do more to increase resilience in the force, train service members how to handle stress better and encourage troops to seek help when they need it. Van Winkle said the military is also looking at increasing efforts to train troops on the safe storage of firearms and medication. She said there are no consistent rules or regulations across the department and the services requiring gun locks or other controls on firearms, but that some states or bases have their own restrictions.
line no:  65
Sony, Disney Back To Work On Third Spider-Man Film
line no:  66
Looks like there will be a homecoming of sorts for Spider-Man, now that Disney and Sony have settled their differences.
line no:  67
The two studios announced on Friday that they will collaborate on a third Spider-Man film starring Tom Holland.
line no:  68
The as yet untitled film will be released on July 16, 2021, and be produced by the Disney-owned Marvel Studios and its president, Kevin Feige, according to a press release sent by both studios.
line no:  69
Amy Pascal will also produce through Pascal Pictures, as she has on the first two Holland-led films, the release said.
line no:  70
"I am thrilled that Spidey's journey in the MCU will continue, and I and all of us at Marvel Studios are very excited that we get to keep working on it," Feige said in the release. "Spider-Man is a powerful icon and hero whose story crosses all ages and audiences around the globe."
line no:  71
The agreement also allows Spidey to appear in a future Marvel Studios film.
line no:  72
Feige acknowledged the collaboration makes the webslinger unique among superheroes.
line no:  73
The All England Club, which hosts the Wimbledon tournament, handed the fine to Williams after she reportedly caused damage during a practice round on the outside courts on June 30, according to The Associated Press and CNN.
line no:  74
The 37-year-old tennis star appeared to shrug off the fine while speaking to reporters after winning the quarterfinal round against Alison Riske on Tuesday.
line no:  75
"I haven't really thought about it, to be honest," she said when asked about the fine. "I just threw my racquet. I got fined."
line no:  76
Williams said she didn't know how that could've caused damage.
line no:  77
"I mean, I guess if you could tell me, I would appreciate it," she told reporters. "I mean, I have always been an Avenger in my heart. Maybe I'm super strong. I don't know."
line no:  78
Williams is after her eighth Wimbledon title, which would be her 24th grand slam victory. She is advancing to the singles semifinals on Thursday against Czech player Barbora Strýcová.
line no:  79
Williams was also fined a total of $17,000 last year after she defended herself against an umpire at the U.S. Open who accused her of illegally communicating with her coach during a match.
line no:  80
During that incident, the umpire issued three code violations to Williams: One for receiving illegal coaching, a second for breaking her tennis racket in frustration and a third after she confronted the umpire and called him a "thief."
line no:  81
Pete Townshend explained what was going on to the audience: "It sounds like he cannot do any more, I'm afraid..."
line no:  82
The band left the stage, originally suggesting they would try to work out the rest of the set without Roger.
line no:  83
When he returned, Townsend said: "I'm really, really sorry. Roger cannot actually speak now.
line no:  84
"Apparently, before the show, he saw a doctor, and you know, he's been singing so f***ing great through this tour. I don't know what the f*** is going on. He has been on top of his game.
line no:  85
"I'm really sorry this has happened to you guys tonight... I don't think there is much point trying to put anything together that makes any sense because this is Roger's show and he's not in good shape."
line no:  86
The crowd was completely supportive, cheering the 74-year-old as he explained what had happened and how the band hoped to return to honour their commitment to the show.
line no:  87
Townsend said; "We will publish a date for our return as soon as we can. Let me explain one thing... We only do one day on, one day off. This is because Roger's vocal surgeon insists he has a day off...
line no:  88
"I swear to you we will come back and we will honour your tickets. I love you so much and I'm sorry to let you down."
line no:  89
Amari Allen, a 12-year-old student at the private K-12 Christian school, said the boys called her dreadlocks "ugly" and "nappy" before cutting them off on the playground during recess.
line no:  90
"They kept laughing and calling me names," Amari told CBS affiliate WUSA-TV, tearing up. "They called me 'ugly,' said, 'I shouldn't have been born.' They called me 'an attention-seeker.'"
line no:  91
According to WUSA, one of the boys allegedly covered Amari's mouth while another held her hands behind her back and a third took a pair of scissors to her dreadlocks.
line no:  92
Amari didn't tell her family about the incident until after her grandmother noticed the length of her hair had changed.
line no:  93
"They ran off laughing, and I was just sitting there," Amari said.
line no:  94
The alleged incident occurred on Monday, but the shy preteen said she didn't tell her family about it until Wednesday, after her grandmother noticed her hair looked different. She feared retaliation if she confessed the truth, she said.
line no:  95
"It's very painful," said Cynthia Allen, Amari's grandmother. "I want to see them dismissed from the school. I want to see something done."
line no:  96
Allen's family pays nearly $12,000 per year for Amari to attend the school, which made headlines earlier this year after Karen Pence took an art teaching job at the famously anti-LGBTQ institution.
line no:  97
Jonathan Van Ness Just Hung Out With Nancy Pelosi And They've Got A Plan
line no:  98
"Queer Eye" star Jonathan Van Ness strutted his stuff on Capitol Hill on Thursday, joining forces with House Speaker Nancy Pelosi (D-Calif.) to discuss the Equality Act.
line no:  99
The Equality Act would extend nondiscrimination protections to LGBTQ individuals in credit, education, employment, housing, federal financial assistance, jury service and public accommodations.
line no:  100
The bill would amend the Civil Rights Act of 1964 to include sexual orientation and gender identity to the list of already protected classes.
line no:  101

In [7]:
df = data_wmt.to_pandas()

In [8]:
df.head()

,ref,systems,src
0,{'R1': 'Vláda přikázala odchod do důchodu dalš...,{'CUNI-DocTransformer.1450': {'score': 0.76862...,The government has compulsorily retired 15 mor...
1,{'R1': 'Ústřední rada nepřímých daní a cel (CB...,{'CUNI-DocTransformer.1450': {'score': 0.58643...,The Central Board of Indirect Taxes and Custom...
2,"{'R1': 'Od června je to už počtvrté, co jsou z...",{'CUNI-DocTransformer.1450': {'score': 0.63602...,"Since June, this is the fourth round of sackin..."
3,{'R1': 'Podle oficiálních zdrojů proběhla akce...,{'CUNI-DocTransformer.1450': {'score': -0.2728...,Sources said the action was in line with Prime...
4,"{'R1': '„Nedávno jsme podnikli odvážný krok, k...",{'CUNI-DocTransformer.1450': {'score': 0.37188...,"""We have recently taken the bold step of compu..."

The dataset only has three columns ref, systems, src. We need only R1 and online B and the the source as R1 is the postedited version of the online B sytem. We make a central dataset adding document number and line number for each document so that later we can trace back to it according to the line number we took for creating the updated dataset.

Analysis of the official WMT20 reference (REF1) revealed it was not translated "from scratch" as required by official guidelines. Using automated detection, researchers confirmed that **REF1 is a post-edited version of the ONLINE-B system.**

**R1 (P1/REF1) – Post-edited MT: Created by an agency using ONLINE-B as a base.** High quality, but structurally biased toward the MT system.

# add line number and document number to each line/ sentences

As each document contains 8 source sentences, and there are 20 documents, we add line numbers from 1 to 8 and document number from 1 to 20 inclusive.

In [9]:
df["document_id"] = df.index // 8 + 1
df["line_id"] = df.index % 8 + 1

In [10]:
print(df["document_id"].unique())
print(df["line_id"].unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5 6 7 8]

In [11]:
df.head(24)

,ref,systems,src,document_id,line_id
0,{'R1': 'Vláda přikázala odchod do důchodu dalš...,{'CUNI-DocTransformer.1450': {'score': 0.76862...,The government has compulsorily retired 15 mor...,1,1
1,{'R1': 'Ústřední rada nepřímých daní a cel (CB...,{'CUNI-DocTransformer.1450': {'score': 0.58643...,The Central Board of Indirect Taxes and Custom...,1,2
2,"{'R1': 'Od června je to už počtvrté, co jsou z...",{'CUNI-DocTransformer.1450': {'score': 0.63602...,"Since June, this is the fourth round of sackin...",1,3
3,{'R1': 'Podle oficiálních zdrojů proběhla akce...,{'CUNI-DocTransformer.1450': {'score': -0.2728...,Sources said the action was in line with Prime...,1,4
4,"{'R1': '„Nedávno jsme podnikli odvážný krok, k...",{'CUNI-DocTransformer.1450': {'score': 0.37188...,"""We have recently taken the bold step of compu...",1,5
5,"{'R1': 'Téměř polovina úředníků, kteří odešli ...",{'CUNI-DocTransformer.1450': {'score': 0.28887...,Nearly half of the officials retired were thos...,1,6
6,{'R1': 'V červnu vláda donutila odejít do důch...,{'CUNI-DocTransformer.1450': {'score': 0.63602...,"In June, the government had compulsorily retir...",1,7
7,{'R1': 'V srpnu vláda poslala do důchodu 22 úř...,{'CUNI-DocTransformer.1450': {'score': 0.47106...,"In August, the government compulsorily retired...",1,8
8,{'R1': 'Žena v Maine obdržela během pěti dnů 5...,"{'CUNI-DocTransformer.1450': {'score': 0.0, 't...",A woman in Maine got 500 letters from United H...,2,1
9,"{'R1': 'Stephanie Layová uvedla, že během čtvr...","{'CUNI-DocTransformer.1450': {'score': 0.0, 't...",Stephanie Lay said she found the piles of lett...,2,2
10,{'R1': '„Před týdnem ve čtvrtek přišla první v...,"{'CUNI-DocTransformer.1450': {'score': 0.0, 't...","""A week ago Thursday was the first wave of let...",2,3
11,{'R1': 'Dopisy chodily dál a v pondělí se jich...,"{'CUNI-DocTransformer.1450': {'score': 0.0, 't...","And the letters just kept coming, piling up to...",2,4
12,"{'R1': 'Byly adresovány jejímu synovi, který t...","{'CUNI-DocTransformer.1450': {'score': 0.0, 't...","They were addressed to her son, who has autism...",2,5
13,{'R1': 'Dopisy se týkaly nároku na zdravotní p...,"{'CUNI-DocTransformer.1450': {'score': 0.0, 't...",The letters were about a $54 or $0 healthcare ...,2,6
14,"{'R1': 'Když se zeptala United Healthcare, pro...","{'CUNI-DocTransformer.1450': {'score': 0.0, 't...",When she asked United Healthcare why she was r...,2,7
15,{'R1': 'Společnost United Healthcare v prohláš...,"{'CUNI-DocTransformer.1450': {'score': 0.0, 't...","In a statement, United Healthcare told CNN it'...",2,8
16,{'R1': 'Využití dat a umělé inteligence ke zvý...,{'CUNI-DocTransformer.1450': {'score': -0.1240...,Using data and artificial intelligence to try ...,3,1
17,{'R1': '„Je to jedna z prvních komerčních inve...,{'CUNI-DocTransformer.1450': {'score': 0.22954...,"""It's one of the first commercial uses of inve...",3,2
18,"{'R1': 'HSBC se odmítla vyjádřit k tomu, co oč...",{'CUNI-DocTransformer.1450': {'score': 0.58758...,HSBC declined to comment on how much it expect...,3,3
19,{'R1': 'Kampaň je důležitou součástí úsilí ban...,{'CUNI-DocTransformer.1450': {'score': 0.35858...,The drive is an important part of the bank's e...,3,4
20,{'R1': 'HSBC byla nucena investovat stovky mil...,{'CUNI-DocTransformer.1450': {'score': 0.41280...,HSBC was forced to invest hundreds of millions...,3,5
21,"{'R1': 'Systém funguje tak, že mapuje jednotli...",{'CUNI-DocTransformer.1450': {'score': 0.52032...,The system works by mapping individual custome...,3,6
22,{'R1': 'Tento systém umožnil již více než 400 ...,{'CUNI-DocTransformer.1450': {'score': 0.57052...,That system has already freed up more than 400...,3,7
23,"{'R1': 'Pan Nivison z HSBC řekl, že si banka n...",{'CUNI-DocTransformer.1450': {'score': 0.10786...,HSBC's Nivison said the lightbulb moment was r...,3,8

now we need only the Ref1/R1, online B from systems and the source. "Online-B.1589" has this structure:
{
    "Online-B.1589": {
        "tgt": "Kmenové buňky 56 pacientů...",
        "score": -0.4510520479
    }
}

so we need to extract the tgt key in our new dataset

In [12]:
# Create new dataframe
new_df = df[["ref", "systems", "src", "document_id", "line_id"]].copy()

# Extract R1 from ref
new_df["ref"] = df["ref"].apply(
    lambda x: x["R1"]
)

# Extract tgt from online-B
new_df["sys"] = df["systems"].apply(
    lambda x: x["Online-B.1589"]["tgt"]
)

# Keep only the columns we want
new_df = new_df[
    ["ref", "sys", "src", "document_id", "line_id"]
]

# Display
print(new_df.head())

                                                 ref  \
0  Vláda přikázala odchod do důchodu dalším 15 da...
1  Ústřední rada nepřímých daní a cel (CBIC) – ag...
2  Od června je to už počtvrté, co jsou zkorumpov...
3  Podle oficiálních zdrojů proběhla akce v návaz...
4  „Nedávno jsme podnikli odvážný krok, když jsme...

                                                 sys  \
0  Vláda povinně odešla do důchodu dalších 15 daň...
1  Ústřední rada nepřímých daní a cel (CBIC) - ag...
2  Od června je to čtvrté kolo vyhození zkorumpov...
3  Zdroj uvedl, že akce byla v souladu s adresou ...
4  "Nedávno jsme podnikli odvážný krok povinného ...

                                                 src  document_id  line_id
0  The government has compulsorily retired 15 mor...            1        1
1  The Central Board of Indirect Taxes and Custom...            1        2
2  Since June, this is the fourth round of sackin...            1        3
3  Sources said the action was in line with Prime...            1        4
4  "We have recently taken the bold step of compu...            1        5

check the created dataset is correct one

In [13]:
new_df.head(50)

,ref,sys,src,document_id,line_id
0,Vláda přikázala odchod do důchodu dalším 15 da...,Vláda povinně odešla do důchodu dalších 15 daň...,The government has compulsorily retired 15 mor...,1,1
1,Ústřední rada nepřímých daní a cel (CBIC) – ag...,Ústřední rada nepřímých daní a cel (CBIC) - ag...,The Central Board of Indirect Taxes and Custom...,1,2
2,"Od června je to už počtvrté, co jsou zkorumpov...",Od června je to čtvrté kolo vyhození zkorumpov...,"Since June, this is the fourth round of sackin...",1,3
3,Podle oficiálních zdrojů proběhla akce v návaz...,"Zdroj uvedl, že akce byla v souladu s adresou ...",Sources said the action was in line with Prime...,1,4
4,"„Nedávno jsme podnikli odvážný krok, když jsme...","""Nedávno jsme podnikli odvážný krok povinného ...","""We have recently taken the bold step of compu...",1,5
5,"Téměř polovina úředníků, kteří odešli do důcho...","Téměř polovina úředníků v důchodu byli ti, kte...",Nearly half of the officials retired were thos...,1,6
6,V červnu vláda donutila odejít do důchodu 15 ú...,V červnu vláda povinně odešla do důchodu 15 úř...,"In June, the government had compulsorily retir...",1,7
7,V srpnu vláda poslala do důchodu 22 úředníků C...,V srpnu vláda povinně odešla do důchodu 22 úře...,"In August, the government compulsorily retired...",1,8
8,Žena v Maine obdržela během pěti dnů 500 dopis...,Žena v Maine dostala 500 dopisů od United Heal...,A woman in Maine got 500 letters from United H...,2,1
9,"Stephanie Layová uvedla, že během čtvrtka a po...","Stephanie Lay uvedla, že ve čtvrtek a pondělí ...",Stephanie Lay said she found the piles of lett...,2,2
10,„Před týdnem ve čtvrtek přišla první vlna dopi...,"„Před týdnem byla čtvrtek první vlna dopisů, m...","""A week ago Thursday was the first wave of let...",2,3
11,Dopisy chodily dál a v pondělí se jich nahroma...,A dopisy právě přicházely a v pondělí se hroma...,"And the letters just kept coming, piling up to...",2,4
12,"Byly adresovány jejímu synovi, který trpí auti...","Byli adresováni svému synovi, který má autismu...","They were addressed to her son, who has autism...",2,5
13,Dopisy se týkaly nároku na zdravotní péči ve v...,Dopisy se týkaly zdravotního tvrzení ve výši 5...,The letters were about a $54 or $0 healthcare ...,2,6
14,"Když se zeptala United Healthcare, proč dostáv...","Když se zeptala na United Healthcare, proč dos...",When she asked United Healthcare why she was r...,2,7
15,Společnost United Healthcare v prohlášení pro ...,"United Healthcare v prohlášení uvedla, že CNN ...","In a statement, United Healthcare told CNN it'...",2,8
16,Využití dat a umělé inteligence ke zvýšení výn...,Využití dat a umělé inteligence k vyzkoušení a...,Using data and artificial intelligence to try ...,3,1
17,„Je to jedna z prvních komerčních investic do ...,„Je to jedno z prvních komerčních investic do ...,"""It's one of the first commercial uses of inve...",3,2
18,"HSBC se odmítla vyjádřit k tomu, co očekává od...","HSBC se odmítla vyjádřit k tomu, co očekává od...",HSBC declined to comment on how much it expect...,3,3
19,Kampaň je důležitou součástí úsilí banky obháj...,Pohon je důležitou součástí úsilí banky bránit...,The drive is an important part of the bank's e...,3,4
20,HSBC byla nucena investovat stovky milionů dol...,HSBC byla nucena investovat stovky milionů dol...,HSBC was forced to invest hundreds of millions...,3,5
21,"Systém funguje tak, že mapuje jednotlivé zákaz...","Systém funguje tak, že mapuje jednotlivé zákaz...",The system works by mapping individual custome...,3,6
22,Tento systém umožnil již více než 400 zaměstna...,Tento systém již uvolnil více než 400 zaměstna...,That system has already freed up more than 400...,3,7
23,"Pan Nivison z HSBC řekl, že si banka náhle uvě...","Společnost Nivison společnosti HSBC uvedla, že...",HSBC's Nivison said the lightbulb moment was r...,3,8
24,Krátce po zatčení byl proveden příkaz k prohlí...,Krátce po zatčení byl proveden příkaz k prohlí...,"Shortly after the arrest, a search warrant was...",4,1
25,Od srpna 2016 do dubna 2017 se muž přiznal k s...,Od srpna 2016 do dubna 2017 se muž obvinil ze ...,The man pleaded guilty to seven charges involv...,4,2
26,"Dvanáctiletá oběť šla podél kolejí, když se oh...","Dvanáctiletá oběť šla po stopě, když se ohlédl...",The 12-year-old victim had been walking along ...,4,3
27,"Ukázka maskovacího obleku Ghillie, který muž p...","Příklad maskovacího obleku Ghillie, který muž ...",An example of a camouflage Ghillie suit the ma...,4,4
28,"Když prosila „přestaň, přestaň, přestaň,“ chyt...","Když prosila „zastav, zastav, zastav,“ vložil ...","When she pleaded ""stop, stop, stop,"" he put he...",4,5
29,"Muž dívce řekl: „Ššš, nekřič. Nekřič, nebo ti ...","Muž řekl dívce: „Ššš, nekřič. Ne křič, nebo ti...","The man told the girl: ""Shhh, don't scream. Do...",4,6
30,"V pravé ruce držel nůž, svázal dívčiny ruce a ...","Držel nůž v pravé ruce, svázal si ruce a nohy ...","Holding the knife in his right hand, he tied h...",4,7
31,"Muž dorazil do práce kolem v 9:30 poté, co neo...","Muž dorazil do práce asi v 9:30 poté, co neodp...",The man arrived at work about 9.30am after fai...,4,8
32,Kmenové buňky 56 dětských pacientů s rakovinou...,Kmenové buňky 56 pacientů s rakovinou u dětí z...,Stem cells of 56 child cancer patients lost at...,5,1
33,Porucha mrazáku v dětské nemocnici v Los Angel...,Porucha mrazáku v dětské nemocnici v Los Angel...,A freezer malfunction at Children's Hospital L...,5,2
34,„Omlouváme se za způsobenou bolest či nejasnos...,„Omlouváme se za jakékoli trápení nebo nejasno...,"""We apologize for any distress or confusion th...",5,3
35,Kromě jednoho prošli všichni pacienti počátečn...,Všichni pacienti kromě jednoho prošli počátečn...,All but one patient had gone through initial t...,5,4
36,"Dopis zaslaný rodičům na začátku září, který j...",Dopis zaslaný rodinám začátkem září informujíc...,A letter sent to families earlier in September...,5,5
37,"Nemocnice uvedla, že ztráta kmenových buněk, k...","Nemocnice uvedla, že ztráta kmenových buněk, k...","The hospital said that the loss of stem cells,...",5,6
38,Jeden z pacientů popsal odběr jako „bolestivý“...,Jeden z pacientů to popsal jako „bolestivý“. S...,"One of the patients described it as ""painful.""...",5,7
39,„Zkoušel jsem usnout a moje tělo se jen začalo...,„Pokusil jsem se spát a moje tělo se jen začal...,"""I would try to sleep and my body would just s...",5,8
40,Tři skotští studenti byli zařazeni mezi nejlep...,Tři skotští studenti byli zařazeni mezi nejlep...,Three Scottish students named among Europe's best,6,1
41,Tři studenti z Univerzity Dundee se stali regi...,Tři studenti univerzity Dundee byli jmenováni ...,Three University of Dundee students have been ...,6,2
42,Studenti Univerzity Dundee byli oceněni jako n...,Studenti University of Dundee byli jmenováni j...,The University of Dundee students were named a...,6,3
43,"Scott Sheldrick, který vystudoval molekulární ...","Scott Sheldrick, který vystudoval molekulární ...","Scott Sheldrick, who graduated in Molecular Ge...",6,4
44,Přestože se všichni tři dostali do celosvětové...,Přestože se všichni tři dostali do globálního ...,Although all three made it through to the glob...,6,5
45,"Profesor Blair Grubb, univerzitní zástupce řed...","Profesor Blair Grubb, zástupce ředitele pro vz...","Professor Blair Grubb, Vice-Principal (Educati...",6,6
46,„O ocenění za vysokoškolská studia velmi usilu...,„Ceny bakalářského studia jsou ostře zpochybňo...,"""The Undergraduate Awards are fiercely contest...",6,7
47,„Chtěl bych poděkovat a srdečně pogratulovat S...,"""Chtěl bych poděkovat svým nejteplejším gratul...","""I would like to offer my warmest congratulati...",6,8
48,Investice do LNG dosáhly v roce 2019 rekordníh...,Investice LNG dosáhly rekordních výsledků v ro...,LNG investments hit record in 2019 & the bigge...,7,1
49,Investice do zkapalněného zemního plynu (LNG) ...,Investice do zkapalněného zemního plynu od zač...,Investments in liquefied natural gas since the...,7,2

**Now check the length of each document**

In [14]:
df_doc_len = (
    new_df.groupby("document_id")["sys"]
      .agg(list)
      .reset_index()
)

In [15]:
df_doc_len.head(20)

    document_id                                                sys
0             1  [Vláda povinně odešla do důchodu dalších 15 da...
1             2  [Žena v Maine dostala 500 dopisů od United Hea...
2             3  [Využití dat a umělé inteligence k vyzkoušení ...
3             4  [Krátce po zatčení byl proveden příkaz k prohl...
4             5  [Kmenové buňky 56 pacientů s rakovinou u dětí ...
5             6  [Tři skotští studenti byli zařazeni mezi nejle...
6             7  [Investice LNG dosáhly rekordních výsledků v r...
7             8  [Vojenské vidí frustrující trend jako sebevraž...
8             9  [Sony, Disney zpátky do práce na třetím filmu ...
9            10  [All England Club, který pořádá turnaj ve Wimb...
10           11  [Pete Townshend vysvětlil, co se děje publiku:...
11           12  [Amari Allen, dvanáctiletá studentka soukromé ...
12           13  [Jonathan Van Ness právě vyrazil s Nancy Pelos...
13           14  [V roce, kdy ve svém rodném Švédsku uspořádala...
14           15  [Pompeo obviňuje Sýrii z používání chemických ...
15           16  [Brexit odtud může být mnohem toxičtější, Poni...
16           17  [„Čína byla vždy odhodlána řešit spory o územn...
17           18  [Indická monzunová sezóna se překročila téměř ...
18           19  [USA vysílají do Saúdské Arábie vojáky, systém...
19           20  [Seth Dunlap Louisiana: WWL Radio hostitel, kt...

In [16]:
document_id_list = []
document_len_list = []
for index, row in df_doc_len.iterrows():
    #print(index)
    #print(row["document_id"])
    #print(row["sys"])
    doc_len = 0
    for sys in row["sys"]:
        doc_len += len(sys) 
    if doc_len > 1300 and doc_len <1800:
        #print(row['sys'])
        print(row["document_id"])
        print(doc_len)
        document_id_list.append(row["document_id"])
        document_len_list.append(doc_len)

3
1785
5
1575
6
1367
7
1625
13
1525
17
1472
18
1523
19
1356

In [17]:
print(document_id_list)
print(document_len_list)

[3, 5, 6, 7, 13, 17, 18, 19]
[1785, 1575, 1367, 1625, 1525, 1472, 1523, 1356]

In [18]:
for index, row in df_doc_len.iterrows():
    #print(index)
    #print(row["document_id"])
    #print(row["sys"])
    doc_len = 0
    for sys in row["sys"]:
        doc_len += len(sys) 
    
    print(doc_len)

2000
1085
1785
884
1575
1367
1625
2088
1020
1271
1019
1169
1525
2443
1252
2477
1472
1523
1356
2096

In [19]:
# Keep only the selected document IDs
df_8_abstracts_with_len = df_doc_len[
    df_doc_len["document_id"].isin(document_id_list)
].copy()

# Add the document length
df_8_abstracts_with_len["document_len"] = df_8_abstracts_with_len["document_id"].map(
    dict(zip(document_id_list, document_len_list))
)

In [20]:
df_8_abstracts_with_len

,document_id,sys,document_len
2,3,[Využití dat a umělé inteligence k vyzkoušení ...,1785
4,5,[Kmenové buňky 56 pacientů s rakovinou u dětí ...,1575
5,6,[Tři skotští studenti byli zařazeni mezi nejle...,1367
6,7,[Investice LNG dosáhly rekordních výsledků v r...,1625
12,13,[Jonathan Van Ness právě vyrazil s Nancy Pelos...,1525
16,17,[„Čína byla vždy odhodlána řešit spory o územn...,1472
17,18,[Indická monzunová sezóna se překročila téměř ...,1523
18,19,"[USA vysílají do Saúdské Arábie vojáky, systém...",1356

In [21]:
for index, row in df_8_abstracts_with_len.iterrows():
    doc_len = 0
    for line in row['sys']:
        doc_len+= len(line)
    print(doc_len)

1785
1575
1367
1625
1525
1472
1523
1356

**next steps**

We calculated oracle error spans for translators postedited version instead of community version. 

- [x] make sure this by loading the translator dataset and finding the **translation_id** there.
    
    Findings: yes they are from translators dataset

1. pass these selected documents through xcomet xl
2. count how many spans there are
3. then calculate the ideal spans
4. if both contains more than 12 spans for each document, prepare everything else.

In [22]:
#check if the translations are from translator dataset or not
import pandas as pd
post_edit_file = "/storage/brno2/home/rahmang/xcomet/arafat_comet/COMET_GR/postedition_aligned.final.translator.tsv"
# Read TSV file into DataFrame
df_translators = pd.read_csv(post_edit_file, sep='\t')
abstracts = [2433, 935, 18234, 18608]
df_translators[df_translators["Translation_id"].isin(abstracts)].drop_duplicates(subset="Translation_id")

,id_hal,Translation_id,line_id,source,translation,postedition
894,1011059,2433,0,Correcting and Validating Syntactic Dependency...,Correction et validation de la dépendance synt...,Correction et validation de la dépendance synt...
923,3986142,18608,0,Exploring Category Structure with Contextual L...,Exploration de la structure des catégories à l...,Exploration de la structure syntaxique à l'aid...
1009,3727214,935,0,Effectiveness of French Language Models on Abs...,Efficacité des modèles de langue française sur...,Efficacité des modèles de langue française sur...
1115,3248881,18234,0,BERT-based Semantic Model for Rescoring N-best...,Modèle sémantique basé sur BERT pour le recala...,Modèle sémantique fondé sur BERT pour la rééva...

### calculate the spans using xcomet

**create data list for calculating the spans without the ref**

In [23]:
# add ref and sources for the selected documents 
grouped = new_df.groupby("document_id").agg({"ref": list, "src": list}).reset_index()
df_8_abstracts_with_len = df_8_abstracts_with_len.merge(grouped, on="document_id", how="left")

In [24]:
df_8_abstracts_with_len.head(8)

,document_id,sys,document_len,ref,src
0,3,[Využití dat a umělé inteligence k vyzkoušení ...,1785,[Využití dat a umělé inteligence ke zvýšení vý...,[Using data and artificial intelligence to try...
1,5,[Kmenové buňky 56 pacientů s rakovinou u dětí ...,1575,[Kmenové buňky 56 dětských pacientů s rakovino...,[Stem cells of 56 child cancer patients lost a...
2,6,[Tři skotští studenti byli zařazeni mezi nejle...,1367,[Tři skotští studenti byli zařazeni mezi nejle...,[Three Scottish students named among Europe's ...
3,7,[Investice LNG dosáhly rekordních výsledků v r...,1625,[Investice do LNG dosáhly v roce 2019 rekordní...,[LNG investments hit record in 2019 & the bigg...
4,13,[Jonathan Van Ness právě vyrazil s Nancy Pelos...,1525,[Jonathan Van Ness se setkal s Nancy Pelosiovo...,[Jonathan Van Ness Just Hung Out With Nancy Pe...
5,17,[„Čína byla vždy odhodlána řešit spory o územn...,1472,[„Čína se vždy snažila řešit spory o územní i ...,"[""China has always been dedicated to resolving..."
6,18,[Indická monzunová sezóna se překročila téměř ...,1523,[Monzunové období v Indii se prodloužilo téměř...,[India's monsoon season has overrun by almost ...
7,19,"[USA vysílají do Saúdské Arábie vojáky, systém...",1356,[USA posílají do Saúdské Arábie vojenské jedno...,"[US sends troops, air defense systems to Saudi..."

In [41]:
data = []
count = 0
for index, row in df_8_abstracts_with_len.iterrows():
    for src_line, sys_line in zip(row["src"], row["sys"]): # all sys, ref, and src have same number of lines
        data.append({
            "src": src_line,
            "mt": sys_line
            
        }
        )

In [26]:
data[0]

{'src': "Using data and artificial intelligence to try and boost revenues is part of HSBC's broader push to squeeze more out of its large physical network and client data, a key priority for interim Chief Executive Noel Quinn.",
 'mt': 'Využití dat a umělé inteligence k vyzkoušení a zvýšení výnosů je součástí širšího tlaku HSBC na vytlačení více z jeho rozsáhlé fyzické sítě a klientských dat, což je klíčová priorita dočasného generálního ředitele Noela Quinna.'}

In [27]:
# load the xcomet custom class and initialize it with xcomet model
#These lines allow the file to load the COMET_GR model - starts here
import sys
from pathlib import Path

COMET_GR = Path.cwd().parent
sys.path.insert(0, str(COMET_GR))
#These lines allow the file to load the COMET_GR model - ends here

# load the custom class without initializing it.
from comet import download_model, load_from_checkpoint
from comet.models.multitask.unified_metric import UnifiedMetric

class CustomXCOMET(UnifiedMetric):
    print("custom unified_metric")

custom unified_metric

In [28]:
#these checks if we loaded the correct COMET codes and where it is located and are we getting 
#the unified_metric class correctly. 
import comet

print("COMET:", comet.__file__)
print("UnifiedMetric:", UnifiedMetric.__module__)

COMET: /auto/brno2/brno2/rahmang/xcomet/arafat_comet/COMET_GR/comet/__init__.py
UnifiedMetric: comet.models.multitask.unified_metric

In [29]:
# here it download the model and load it from the downloaded checkpoint
from comet import download_model, load_from_checkpoint

model_path = download_model("Unbabel/XCOMET-XL")
model = load_from_checkpoint(model_path)
# Here we are initializing the custom class using the loaded checkpoint, so the model is downloaded and
#it will get initialized using the custom class.
model = CustomXCOMET.load_from_checkpoint(model_path,strict = False)

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Encoder model frozen.
/storage/brno2/home/rahmang/envs/xcomet/lib/python3.11/site-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']
Encoder model frozen.

In [30]:
data = [
    {
        "src": "Boris Johnson teeters on edge of favour with Tory MPs",
        "mt": "Boris Johnsons Beliebtheit bei Tory-Abgeordneten völlig in der Gunst",
        "ref": "Boris Johnsons Beliebtheit bei Tory-MPs steht auf der Kippe"
    }
]

model_output = model.predict(data, batch_size=8, gpus=1)
# Segment-level scores
print (model_output.scores)

# System-level score
print (model_output.system_score)

# Score explanation (error spans)
print (model_output.metadata.error_spans)

/storage/brno2/home/rahmang/envs/xcomet/lib/python3.11/site-packages/torch/utils/data/dataloader.py:617: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA A40') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [GPU-a499a47b-6eca-00c0-ef67-07b64dce9e09]
/storage/brno2/home/rahmang/envs/xcomet/lib/python3.11/site-packages/torch/utils/data/dataloader.py:617: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
Predicting DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

[0.6540005207061768]
0.6540005207061768
[[{'text': ['Beliebtheit'], 'confidence': 0.3624686002731323, 'severity': 'major', 'start': 14, 'end': 26, 'check severity': ['major', 'major', 'major', 'major']}, {'text': ['Tory-Abgeordneten', 'völlig', 'in', 'der', 'Gunst'], 'confidence': 0.3602065443992615, 'severity': 'critical', 'start': 30, 'end': 68, 'check severity': ['minor', 'minor', 'minor', 'minor', 'major', 'critical', 'major', 'critical', 'critical']}]]

**now compute the spans for our en_cz dataset**

In [42]:
model_output_en_cz = model.predict(data, batch_size=8, gpus=1)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [GPU-a499a47b-6eca-00c0-ef67-07b64dce9e09]
/storage/brno2/home/rahmang/envs/xcomet/lib/python3.11/site-packages/torch/utils/data/dataloader.py:617: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Predicting DataLoader 0: 100%|██████████| 8/8 [00:03<00:00,  2.60it/s]

In [43]:
print(len(model_output_en_cz.scores)) #we should get 64 outputs as we have 64 lines

64

In [44]:
print (model_output_en_cz.metadata.error_spans[0]) # check the spans for line 1

[{'text': ['k', 'vyzkoušení', 'a', 'zvýšení', 'výnosů'], 'confidence': 0.4998055100440979, 'severity': 'major', 'start': 31, 'end': 61, 'check severity': ['major', 'major', 'major', 'major', 'major', 'major', 'major', 'major']}, {'text': ['tlaku'], 'confidence': 0.4838374853134155, 'severity': 'major', 'start': 81, 'end': 87, 'check severity': ['major']}, {'text': ['na', 'vytlačení', 'více'], 'confidence': 0.4628485143184662, 'severity': 'major', 'start': 92, 'end': 110, 'check severity': ['major', 'major', 'major', 'major', 'major']}]

In [45]:
# now calculate how many spans each line has

print(type(model_output_en_cz.metadata.error_spans)) # should be a list of dict

<class 'list'>

In [46]:
number_of_spans_list = []
for line in model_output_en_cz.metadata.error_spans:
    number_of_spans = 0
    for span in line:
        number_of_spans += len(span['text'])
    number_of_spans_list.append(number_of_spans)

In [47]:
print(number_of_spans_list[0])

9

In [48]:
print(number_of_spans_list)

[9, 12, 6, 5, 12, 8, 6, 15, 11, 0, 0, 7, 7, 9, 14, 11, 0, 2, 8, 14, 2, 0, 7, 8, 2, 1, 13, 6, 2, 3, 1, 4, 4, 27, 1, 1, 26, 17, 4, 10, 7, 3, 23, 5, 1, 28, 4, 3, 3, 5, 4, 6, 3, 1, 15, 5, 0, 0, 1, 8, 0, 12, 1, 3]

In [49]:
len(number_of_spans_list)

64

In [50]:
# now calculate total number of spans in each doc
spans_per_doc = [sum(number_of_spans_list[i:i+8]) for i in range(0, len(number_of_spans_list), 8)]

In [51]:
spans_per_doc

[73, 59, 41, 32, 90, 74, 42, 25]