In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./abstract_metadata_with_ideal_spans_correct_no_spans_with_min4chars_df_en_cz_final_with_selected_8_docs.tsv", sep = '\t')

In [3]:
first_4_text_list = (3, 7, 6, 19)

In [4]:
filtered_df_first_4 = df[df['hal_id'].isin(first_4_text_list)]

In [5]:
filtered_df_first_4

,hal_id,translation_id,sentence_indices,num_sentences,total_characters,source,total_spans,total_span_chars,span_char_ratio_pct
0,3,3,"[0, 1, 2, 3, 4, 5, 6, 7]",8,1785,Using data and artificial intelligence to try ...,42,600,33.61
1,7,7,"[24, 25, 26, 27, 28, 29, 30, 31]",8,1625,LNG investments hit record in 2019 & the bigge...,29,401,24.68
6,6,6,"[16, 17, 18, 19, 20, 21, 22, 23]",8,1367,Three Scottish students named among Europe's b...,30,574,41.99
7,19,19,"[56, 57, 58, 59, 60, 61, 62, 63]",8,1356,"US sends troops, air defense systems to Saudi ...",35,457,33.70

In [6]:
values = filtered_df_first_4[['hal_id','total_spans']]
values

   hal_id  total_spans
0       3           42
1       7           29
6       6           30
7      19           35

In [7]:
import json

In [8]:
path_json = "spans_ideal_df_en_cz_final_with_selected_8_docs.json"
# Load JSON data
with open(path_json, 'r', encoding='utf-8') as f:
    json_data_ideal_spans = json.load(f)

In [9]:
print(len(json_data_ideal_spans))

64

**Check which indices/sentences do not have any spans**

In [10]:
for index, data in enumerate(json_data_ideal_spans):
    if not data:
        print(index)

16

In [11]:
import pandas as pd
path_csv = "postedition_aligned_with_tokenized_offsets_df_en_cz_final_with_selected_8_docs.csv"
df_en_cz = pd.read_csv(path_csv)

**Get sentence length for each abstract**

In [12]:
def sentence_length_abstract(translations):
    sentences_length_of_abstract = []
    for idx, value in translations.items():
        sentences_length_of_abstract.append(len(value))
    return sentences_length_of_abstract

In [13]:
first_4_text_list

(3, 7, 6, 19)

In [14]:
import ast
sentences_length_of_abstract = []
for abstract_id in first_4_text_list:
    row = filtered_df_first_4[filtered_df_first_4['translation_id'] == abstract_id]
    indices = ast.literal_eval(row["sentence_indices"].iloc[0])
    first_index = indices[0]
    last_index = indices[-1]
    print(abstract_id, first_index, last_index)
    
    sentences_length_of_each_abstract = sentence_length_abstract(df_en_cz.iloc[first_index:last_index+1]['translation'])
    sentences_length_of_abstract.append({
        "translation_id":abstract_id,
        "translation_starting_index": first_index,
        "translation_ending_index": last_index,
        "document_length":sentences_length_of_each_abstract
    })

3 0 7
7 24 31
6 16 23
19 56 63

In [15]:
sentences_length_of_abstract[2]

{'translation_id': 6,
 'translation_starting_index': 16,
 'translation_ending_index': 23,
 'document_length': [57, 100, 207, 248, 137, 236, 211, 171]}

In [16]:
print(sum(sentences_length_of_abstract[1]["document_length"]))

1625

In [17]:
spans_all_abstracts = []
for abstract_info in sentences_length_of_abstract:
    translation_starting_index = abstract_info["translation_starting_index"]
    translation_ending_index = abstract_info["translation_ending_index"]
    spans_each_abstract = json_data_ideal_spans[translation_starting_index:translation_ending_index+1]
    spans_all_abstracts.append({
        "translation_id": abstract_info["translation_id"],
        "ideal_spans":spans_each_abstract
    })

In [18]:
spans_all_abstracts[0]

{'translation_id': 3,
 'ideal_spans': [[{'text': ['k', 'vyzkoušení', 'a'], 'start': 31, 'end': 46},
   {'text': ['HSBC'], 'start': 87, 'end': 92},
   {'text': ['vytlačení'], 'start': 95, 'end': 105},
   {'text': ['z', 'jeho'], 'start': 110, 'end': 117},
   {'text': ['klíčová', 'priorita'], 'start': 165, 'end': 182}],
  [{'text': ['jedno'], 'start': 6, 'end': 12},
   {'text': ['je', 'ze'], 'start': 120, 'end': 126},
   {'text': ['podstaty'], 'start': 130, 'end': 139},
   {'text': ['globální'], 'start': 197, 'end': 206},
   {'text': ['klientského'], 'start': 214, 'end': 226},
   {'text': ['společnosti'], 'start': 239, 'end': 251}],
  [{'text': ['uvedla,'], 'start': 66, 'end': 74},
   {'text': ['iniciativa', '„síťový', 'příjem“'], 'start': 83, 'end': 110},
   {'text': ['přinesla'], 'start': 114, 'end': 123},
   {'text': ['stovky'], 'start': 136, 'end': 143}],
  [{'text': ['Pohon'], 'start': 0, 'end': 5},
   {'text': ['bránit', 'svou'], 'start': 39, 'end': 51},
   {'text': ['přítomnost'], 'start': 60, 'end': 71},
   {'text': ['kdy'], 'start': 79, 'end': 83},
   {'text': ['kde'], 'start': 187, 'end': 191},
   {'text': ['návratnosti', 'pod'], 'start': 200, 'end': 216}],
  [{'text': ['do'], 'start': 49, 'end': 52},
   {'text': ['urovnání'], 'start': 92, 'end': 101},
   {'text': ['miliardy'], 'start': 105, 'end': 114},
   {'text': ['kvůli', 'tomu,'], 'start': 149, 'end': 161},
   {'text': ['jednotky.'], 'start': 236, 'end': 246}],
  [{'text': ['zákazníky', '“a', 'společnosti'], 'start': 40, 'end': 65},
   {'text': ['navazuje'], 'start': 73, 'end': 82},
   {'text': ['transakcí'], 'start': 112, 'end': 122},
   {'text': ['dříve'], 'start': 136, 'end': 142},
   {'text': ['spojení'], 'start': 152, 'end': 160}],
  [{'text': ['uvolnil'], 'start': 16, 'end': 24},
   {'text': ['zaměstnanců,',
     'kteří',
     'by',
     'mohli',
     'přecházet',
     'z',
     'ručních',
     'kontrol'],
    'start': 37,
    'end': 93},
   {'text': ['do', 'rolí', 'zaměřených'], 'start': 113, 'end': 132},
   {'text': ['klienta,'], 'start': 135, 'end': 144},
   {'text': ['trávit', 'čas', 'pomáháním'], 'start': 154, 'end': 175},
   {'text': ['provozní'], 'start': 214, 'end': 223},
   {'text': ['obchodu'], 'start': 231, 'end': 239}],
  [{'text': ['Společnost'], 'start': 0, 'end': 10},
   {'text': ['společnosti'], 'start': 18, 'end': 30},
   {'text': ['uvedla,'], 'start': 35, 'end': 43},
   {'text': ['okamžik', 'žárovky'], 'start': 46, 'end': 62},
   {'text': ['uvědomuje,'], 'start': 65, 'end': 76},
   {'text': ['přemístěn'], 'start': 105, 'end': 115},
   {'text': ['„zelené',
     'vlajky“',
     'atraktivních',
     'potenciálních',
     'klientů,',
     'spíše',
     'než',
     '„červené',
     'vlajky“',
     'protiprávního',
     'jednání.'],
    'start': 131,
    'end': 233}]]}

In [19]:
for index, spans_each_abstract in enumerate(spans_all_abstracts):
    print(len(spans_all_abstracts[index]["ideal_spans"])) #check if all the sentences has ideal spans

8
8
8
8

**Recompute the span offsets for each abstract**

The ideal spans were computed on sentence level. That is why they contain the start and end for each span w.r.t to the sentence length. However, when we show the abstract on the system, we show all the sentences as document. So we need to readjust the span offsets. For en_fr, there was a title and the next sentence started as a new line which is 2 space in python space. But for en_cz, there is no title, so we can add 1 space after the first sentence. 

**Now how to tackle when a sentence does not have any spans**

its handled in line 4 and 23, if the list does not contain any span, then the inner loop will not run and in line line 21, its adding the previous sentence length so that even the loop is not running, the calculation is not hampered.

In [20]:
def compute_absolute_spans(sentence_spans, sentences_length_of_abstract, has_title=False, title_gap=2, sep_gap=1):
    """
    sentence_spans: list of lists — one list of span-dicts per sentence
                     (each span-dict has 'text', 'start', 'end' — offsets local to that sentence)
    sentences_length_of_abstract: list of ints — character length of each sentence, in the SAME order
                       as sentence_spans (must be same length, or one longer if has_title=True
                       and the title's length is sentence_lengths[0])
    has_title: if True, sentence_spans[0] is treated as a title block separated by title_gap
    title_gap: characters between title and first sentence (only used if has_title)
    sep_gap: characters between consecutive sentences (e.g. 1 for a single space)
    """
    spans_with_new_starts_ends = []
    spans_with_new_starts_ends = []
    previous_sentence_length = title_gap if has_title else 0
    for index, spans in enumerate(sentence_spans):
        if index == 0:
            spans_title = []
            for span in spans: #
                if span['start'] == 0:
                    start = 0
                else:
                    start = span['start'] + 1
                spans_title.append({
                                    'text': span['text'][:],
                                    'startnew': start,
                                    'endnew': span['end']

                                    })

            spans_with_new_starts_ends.append(spans_title)


        elif index == 1 and has_title:
            spans_each_sentence = []
            previous_sentence_length += sentences_length_of_abstract[index - 1]

            for ind,span in enumerate(spans):
                print("index in index 1: ", ind)
                print("spans in index 1: ", span)
                if span['start'] == 0:
                    start = span['start'] + previous_sentence_length
                else:
                    start = span['start'] + previous_sentence_length + 1

                spans_each_sentence.append({
                                    'text': span['text'][:],
                                    'startnew': start,
                                    'endnew': span['end'] + previous_sentence_length

                                    })
            spans_with_new_starts_ends.append(spans_each_sentence)

        else:
            spans_each_sentence = []
            previous_sentence_length += sentences_length_of_abstract[index - 1] + sep_gap
            for ind,span in enumerate(spans):
                if span['start'] == 0:
                    start = span['start'] + previous_sentence_length
                else:
                    start = span['start'] + previous_sentence_length + sep_gap
                spans_each_sentence.append({
                                    'text': span['text'][:],
                                    'startnew': start,
                                    'endnew': span['end'] + previous_sentence_length

                                    })

            spans_with_new_starts_ends.append(spans_each_sentence)
    return spans_with_new_starts_ends

 **Match the list length of spans_all_spans and sentences_length_of_abstract**
 
 From the whole dataset, we need to select only the translations which we want to use for exp1 or for ideal case. Here we can get the sentence lengths for each abstract when the **translation_id** matches in both list.

In [21]:
updated_spans_offsets_all_documents = []
for spans_each_abstract in spans_all_abstracts:
    translation_id = spans_each_abstract['translation_id']
    sentence_spans = spans_each_abstract['ideal_spans']

    # find the single matching entry, then pull its document_length
    matching_entry = next(entry for entry in sentences_length_of_abstract if entry['translation_id'] == translation_id)
    sentences_length = matching_entry['document_length']
    updated_spans_offsets_all_documents.append({
        'translation_id':translation_id,
        'updated_spans_offsets': compute_absolute_spans(sentence_spans, sentences_length)
    })

In [22]:
updated_spans_offsets_all_documents

[{'translation_id': 3,
  'updated_spans_offsets': [[{'text': ['k', 'vyzkoušení', 'a'],
     'startnew': 32,
     'endnew': 46},
    {'text': ['HSBC'], 'startnew': 88, 'endnew': 92},
    {'text': ['vytlačení'], 'startnew': 96, 'endnew': 105},
    {'text': ['z', 'jeho'], 'startnew': 111, 'endnew': 117},
    {'text': ['klíčová', 'priorita'], 'startnew': 166, 'endnew': 182}],
   [{'text': ['jedno'], 'startnew': 235, 'endnew': 240},
    {'text': ['je', 'ze'], 'startnew': 349, 'endnew': 354},
    {'text': ['podstaty'], 'startnew': 359, 'endnew': 367},
    {'text': ['globální'], 'startnew': 426, 'endnew': 434},
    {'text': ['klientského'], 'startnew': 443, 'endnew': 454},
    {'text': ['společnosti'], 'startnew': 468, 'endnew': 479}],
   [{'text': ['uvedla,'], 'startnew': 553, 'endnew': 560},
    {'text': ['iniciativa', '„síťový', 'příjem“'],
     'startnew': 570,
     'endnew': 596},
    {'text': ['přinesla'], 'startnew': 601, 'endnew': 609},
    {'text': ['stovky'], 'startnew': 623, 'endnew': 629}],
   [{'text': ['Pohon'], 'startnew': 646, 'endnew': 651},
    {'text': ['bránit', 'svou'], 'startnew': 686, 'endnew': 697},
    {'text': ['přítomnost'], 'startnew': 707, 'endnew': 717},
    {'text': ['kdy'], 'startnew': 726, 'endnew': 729},
    {'text': ['kde'], 'startnew': 834, 'endnew': 837},
    {'text': ['návratnosti', 'pod'], 'startnew': 847, 'endnew': 862}],
   [{'text': ['do'], 'startnew': 933, 'endnew': 935},
    {'text': ['urovnání'], 'startnew': 976, 'endnew': 984},
    {'text': ['miliardy'], 'startnew': 989, 'endnew': 997},
    {'text': ['kvůli', 'tomu,'], 'startnew': 1033, 'endnew': 1044},
    {'text': ['jednotky.'], 'startnew': 1120, 'endnew': 1129}],
   [{'text': ['zákazníky', '“a', 'společnosti'],
     'startnew': 1171,
     'endnew': 1195},
    {'text': ['navazuje'], 'startnew': 1204, 'endnew': 1212},
    {'text': ['transakcí'], 'startnew': 1243, 'endnew': 1252},
    {'text': ['dříve'], 'startnew': 1267, 'endnew': 1272},
    {'text': ['spojení'], 'startnew': 1283, 'endnew': 1290}],
   [{'text': ['uvolnil'], 'startnew': 1330, 'endnew': 1337},
    {'text': ['zaměstnanců,',
      'kteří',
      'by',
      'mohli',
      'přecházet',
      'z',
      'ručních',
      'kontrol'],
     'startnew': 1351,
     'endnew': 1406},
    {'text': ['do', 'rolí', 'zaměřených'], 'startnew': 1427, 'endnew': 1445},
    {'text': ['klienta,'], 'startnew': 1449, 'endnew': 1457},
    {'text': ['trávit', 'čas', 'pomáháním'], 'startnew': 1468, 'endnew': 1488},
    {'text': ['provozní'], 'startnew': 1528, 'endnew': 1536},
    {'text': ['obchodu'], 'startnew': 1545, 'endnew': 1552}],
   [{'text': ['Společnost'], 'startnew': 1559, 'endnew': 1569},
    {'text': ['společnosti'], 'startnew': 1578, 'endnew': 1589},
    {'text': ['uvedla,'], 'startnew': 1595, 'endnew': 1602},
    {'text': ['okamžik', 'žárovky'], 'startnew': 1606, 'endnew': 1621},
    {'text': ['uvědomuje,'], 'startnew': 1625, 'endnew': 1635},
    {'text': ['přemístěn'], 'startnew': 1665, 'endnew': 1674},
    {'text': ['„zelené',
      'vlajky“',
      'atraktivních',
      'potenciálních',
      'klientů,',
      'spíše',
      'než',
      '„červené',
      'vlajky“',
      'protiprávního',
      'jednání.'],
     'startnew': 1691,
     'endnew': 1792}]]},
 {'translation_id': 7,
  'updated_spans_offsets': [[{'text': ['rekordních', 'výsledků'],
     'startnew': 22,
     'endnew': 41},
    {'text': ['růst'], 'startnew': 65, 'endnew': 69}],
   [{'text': ['rekordně', 'vysokých'], 'startnew': 149, 'endnew': 166}],
   [{'text': ['„Letos', '2019', 'poprvé', 'zlomil'],
     'startnew': 271,
     'endnew': 296},
    {'text': ['(konečná', 'investiční'], 'startnew': 313, 'endnew': 332},
    {'text': ['producentů', 'a', 'spotřebitelů', 'LNG'],
     'startnew': 398,
     'endnew': 427}],
   [{'text': ['překvapením,'], 'startnew': 471, 'endnew': 483},
    {'text': ['rostoucí'], 'startnew': 524, 'endnew': 532},
    {'text': ['špičkový'], 'startnew': 623, 'endnew': 631}],
   [{'text': ['"Největší', 'růst'], 'startnew': 645, 'endnew': 659},
    {'text': ['přijde'], 'startnew': 700, 'endnew': 706},
    {'text': ['Číny,"', 'uvedla'], 'startnew': 761, 'endnew': 774},
    {'text': ['za', 'pět'], 'startnew': 792, 'endnew': 798}],
   [{'text': ['neexistují'], 'startnew': 871, 'endnew': 881},
    {'text': ['žádná', 'překvapení.', 'Většina'],
     'startnew': 886,
     'endnew': 911},
    {'text': ['byla', 'vyrobena'], 'startnew': 919, 'endnew': 932}],
   [{'text': ['očekává,', 'že', 'se'], 'startnew': 1032, 'endnew': 1046},
    {'text': ['kapacita'], 'startnew': 1056, 'endnew': 1064},
    {'text': ['zdvojnásobí'], 'startnew': 1114, 'endnew': 1125},
    {'text': ['miliard', 'cu', 'ft'], 'startnew': 1133, 'endnew': 1146},
    {'text': ['bude'], 'startnew': 1164, 'endnew': 1168},
    {'text': ['LNG.'], 'startnew': 1219, 'endnew': 1223},
    {'text': ['cu', 'ft'], 'startnew': 1318, 'endnew': 1323},
    {'text': ['z', 'přibližně'], 'startnew': 1331, 'endnew': 1342},
    {'text': ['cu', 'ft'], 'startnew': 1353, 'endnew': 1358}],
   [{'text': ['právě'], 'startnew': 1393, 'endnew': 1398},
    {'text': ['-'], 'startnew': 1430, 'endnew': 1431},
    {'text': ['-'], 'startnew': 1443, 'endnew': 1444},
    {'text': ['mít', 'konečnou', 'kapacitu'],
     'startnew': 1454,
     'endnew': 1475},
    {'text': ['je', 'veden', 'společností'], 'startnew': 1538, 'endnew': 1558},
    {'text': ['s', 'účastníky', 'menšin', 'včetně'],
     'startnew': 1565,
     'endnew': 1590}]]},
 {'translation_id': 6,
  'updated_spans_offsets': [[],
   [{'text': ['univerzity'], 'startnew': 71, 'endnew': 81},
    {'text': ['byli', 'jmenováni'], 'startnew': 89, 'endnew': 103},
    {'text': ['absolventi', 'v', 'Evropě.'], 'startnew': 138, 'endnew': 158}],
   [{'text': ['University', 'of'], 'startnew': 168, 'endnew': 181},
    {'text': ['jmenováni'], 'startnew': 194, 'endnew': 203},
    {'text': ['Awards,', 'zatímco'], 'startnew': 288, 'endnew': 303},
    {'text': ['byli', 'soudci', 'oceněni.'], 'startnew': 346, 'endnew': 366}],
   [{'text': ['Evropskou'], 'startnew': 430, 'endnew': 439},
    {'text': ['Life', 'Sciences,'], 'startnew': 448, 'endnew': 462},
    {'text': ['Mental', 'Health', 'Nursing'], 'startnew': 495, 'endnew': 516},
    {'text': ['Nursing,',
      'Midwifery',
      '&',
      'Allied',
      'Healthcare,',
      'zatímco'],
     'startnew': 531,
     'endnew': 578},
    {'text': ['Knibb'], 'startnew': 584, 'endnew': 589},
    {'text': ['Visual', 'Arts.'], 'startnew': 603, 'endnew': 615}],
   [{'text': ['globálního'], 'startnew': 651, 'endnew': 661},
    {'text': ['ve', 'finále'], 'startnew': 670, 'endnew': 679},
    {'text': ['některých', 'z'], 'startnew': 710, 'endnew': 721}],
   [{'text': ['vzdělávání', 'na', 'univerzitě,'],
     'startnew': 798,
     'endnew': 823},
    {'text': ['čelili'], 'startnew': 892, 'endnew': 898},
    {'text': ['ze', 'strany'], 'startnew': 910, 'endnew': 919},
    {'text': ['navštěvují', 'některé', 'z'], 'startnew': 938, 'endnew': 958},
    {'text': ['univerzit.'], 'startnew': 980, 'endnew': 990}],
   [{'text': ['„Ceny', 'bakalářského'], 'startnew': 991, 'endnew': 1009},
    {'text': ['jsou',
      'ostře',
      'zpochybňovány',
      'tisíci',
      'studenty',
      'po',
      'celém',
      'světě'],
     'startnew': 1017,
     'endnew': 1072},
    {'text': ['to', 'velká', 'reflexe', 'kvality'],
     'startnew': 1078,
     'endnew': 1102},
    {'text': ['získávají,',
      'že',
      'Dundee',
      'je',
      'tak',
      'silně',
      'zastoupen',
      'mezi',
      'výherci',
      'cen.'],
     'startnew': 1141,
     'endnew': 1202}],
   [{'text': ['"Chtěl'], 'startnew': 1203, 'endnew': 1209},
    {'text': ['svým', 'nejteplejším', 'gratulacím'],
     'startnew': 1225,
     'endnew': 1253},
    {'text': ['Lolovi'], 'startnew': 1277, 'endnew': 1283},
    {'text': ['spolu', 's', 'dalšími', 'zástupci'],
     'startnew': 1315,
     'endnew': 1339},
    {'text': ['velmi', 'oceněni."'], 'startnew': 1359, 'endnew': 1374}]]},
 {'translation_id': 19,
  'updated_spans_offsets': [[{'text': ['vysílají'],
     'startnew': 4,
     'endnew': 12},
    {'text': ['vojáky,'], 'startnew': 31, 'endnew': 38},
    {'text': ['íránské'], 'startnew': 81, 'endnew': 88}],
   [{'text': ['odesílají'], 'startnew': 99, 'endnew': 108},
    {'text': ['jednotek', 'do', 'Saúdské', 'Arábie,'],
     'startnew': 184,
     'endnew': 211},
    {'text': ['odrazily'], 'startnew': 216, 'endnew': 224},
    {'text': ['agresivnější'], 'startnew': 231, 'endnew': 243},
    {'text': ['Íránu.'], 'startnew': 252, 'endnew': 258}],
   [{'text': ['další'], 'startnew': 295, 'endnew': 300},
    {'text': ['připraveny'], 'startnew': 331, 'endnew': 341},
    {'text': ['jít,'], 'startnew': 360, 'endnew': 364}],
   [{'text': ['"Jiné'], 'startnew': 380, 'endnew': 385},
    {'text': ['íránské', 'zneužívání'], 'startnew': 399, 'endnew': 417},
    {'text': ['regionu'], 'startnew': 426, 'endnew': 433},
    {'text': ['hledáme,'], 'startnew': 439, 'endnew': 447},
    {'text': ['přispěli', 'prostředky', 'v', 'mezinárodním', 'úsilí'],
     'startnew': 452,
     'endnew': 492},
    {'text': ['Arábie,"'], 'startnew': 519, 'endnew': 527}],
   [{'text': ['Minulý', 'týden'], 'startnew': 568, 'endnew': 580},
    {'text': ['z'], 'startnew': 710, 'endnew': 711}],
   [{'text': ['uvedl,'], 'startnew': 725, 'endnew': 731},
    {'text': ['násilnějších', 'činů'], 'startnew': 780, 'endnew': 797},
    {'text': ['-'], 'startnew': 814, 'endnew': 815},
    {'text': ['tohoto'], 'startnew': 823, 'endnew': 829},
    {'text': ['na', 'tento', 'měsíc'], 'startnew': 842, 'endnew': 856},
    {'text': ['-'], 'startnew': 890, 'endnew': 891},
    {'text': ['útoky', 'zintenzívnily'], 'startnew': 917, 'endnew': 936},
    {'text': ['odsoudily.'], 'startnew': 939, 'endnew': 949}],
   [{'text': ['reholové'], 'startnew': 969, 'endnew': 977},
    {'text': ['si', 'nárokovali', 'odpovědnost'],
     'startnew': 994,
     'endnew': 1019},
    {'text': ['ropnou', 'továrnu', 'na', 'zpracování', 'ropy'],
     'startnew': 1052,
     'endnew': 1085},
    {'text': ['Irán', 'přímo.'], 'startnew': 1141, 'endnew': 1152},
    {'text': ['odmítl', 'účast'], 'startnew': 1158, 'endnew': 1170},
    {'text': ['útoku.'], 'startnew': 1174, 'endnew': 1180}],
   [{'text': ['"Je'], 'startnew': 1181, 'endnew': 1184},
    {'text': ['zbraně'], 'startnew': 1209, 'endnew': 1215},
    {'text': ['vyrobeny'], 'startnew': 1221, 'endnew': 1229},
    {'text': ['vypuštěny'], 'startnew': 1247, 'endnew': 1256},
    {'text': ['Jemenu,"'], 'startnew': 1259, 'endnew': 1267},
    {'text': ['všechna', 'označení', 'ukazují,'],
     'startnew': 1304,
     'endnew': 1329},
    {'text': ['"'], 'startnew': 1362, 'endnew': 1363}]]}]

**update all the word offsets in the abstracts/documents**

Before we have updated the span offsets w.r.t the merged document. This time we need to do it for all the words as we need to align

here we store the word offsets from **postedition_aligned_with_tokenized_offsets_df_en_cz_final_with_selected_8_docs.csv** for the translation_id we will work for exp1.

each entry in the list will be a dictionary in this format:

`{
'translation_id': translation_id,
'word_offsets': word_offsets
}`

In [23]:
first_4_text_list

(3, 7, 6, 19)

In [24]:
df_en_cz.iloc[0]

id_hal                                                                     3
Translation_id                                                             3
line_id                                                                    1
source                     Using data and artificial intelligence to try ...
translation                Využití dat a umělé inteligence k vyzkoušení a...
postedition                Využití dat a umělé inteligence ke zvýšení výn...
translation_tokenized      ['Využití', 'dat', 'a', 'umělé', 'inteligence'...
translation_word_offset    [(0, 7), (7, 11), (11, 13), (13, 19), (19, 31)...
postedition_tokenized      ['Využití', 'dat', 'a', 'umělé', 'inteligence'...
postedition_word_offset    [(0, 7), (7, 11), (11, 13), (13, 19), (19, 31)...
Name: 0, dtype: object

In [25]:
sentences_length_of_abstract[0]

{'translation_id': 3,
 'translation_starting_index': 0,
 'translation_ending_index': 7,
 'document_length': [227, 257, 159, 236, 246, 182, 245, 233]}

In [26]:
import ast
word_offsets_all_abstract = []
for translation_id in first_4_text_list:
    word_offsets = []
    for value in sentences_length_of_abstract:
        if value['translation_id'] == translation_id:
            start_index = value['translation_starting_index']
            end_index = value['translation_ending_index']
            #Convert the string representations to actual Python objects (list of tuples)
            word_offsets = df_en_cz.iloc[start_index:end_index+1]["translation_word_offset"].apply(ast.literal_eval)

    word_offsets_all_abstract.append({
        'translation_id': translation_id,
        'word_offsets': word_offsets
    })

In [27]:
word_offsets_all_abstract[0] #List[dict[tuple]]

{'translation_id': 3,
 'word_offsets': 0    [(0, 7), (7, 11), (11, 13), (13, 19), (19, 31)...
 1    [(0, 3), (3, 6), (6, 12), (12, 14), (14, 22), ...
 2    [(0, 4), (4, 7), (7, 15), (15, 24), (24, 26), ...
 3    [(0, 5), (5, 8), (8, 18), (18, 27), (27, 33), ...
 4    [(0, 4), (4, 9), (9, 16), (16, 27), (27, 34), ...
 5    [(0, 6), (6, 14), (14, 19), (19, 22), (22, 29)...
 6    [(0, 5), (5, 12), (12, 16), (16, 24), (24, 29)...
 7    [(0, 10), (10, 18), (18, 30), (30, 35), (35, 4...
 Name: translation_word_offset, dtype: object}

**Now update all the word offsets for each document**

The word offsets we retrieved in the last cell, they are for each sentence. Just like we updated the span offsets w.r.t. the abstracts/documents, we will do that here again.

- [x] can we call the same function here as well? we can but there we are also getting the text for each span which we do not need here, so we will use another function

In [28]:
def update_word_offsets(word_offsets, sentences_length_of_abstract, has_title=False, title_gap=2, sep_gap=1):
    updated_word_offsets = []
    counter = 0
    previous_sentence_length = title_gap if has_title else 0

    for index, value in word_offsets.items():
        if counter == 0:
            updated_offsets_each_sentence = []
            for offset in value:
                if offset[0] == 0:
                    start = 0
                else:
                    start = offset[0] + 1
                updated_offsets_each_sentence.append((start, offset[1]))

            updated_word_offsets.append(updated_offsets_each_sentence)

        elif counter == 1:
            updated_offsets_each_sentence = []
            previous_sentence_length += sentences_length_of_abstract[counter - 1] + sep_gap
            for ind,offset in enumerate(value):
                if ind == 0:
                    start = offset[0]+previous_sentence_length
                else:
                    start = offset[0]+previous_sentence_length + 1
                updated_offsets_each_sentence.append((start, offset[1]+previous_sentence_length))

            updated_word_offsets.append(updated_offsets_each_sentence)
        else:
            updated_offsets_each_sentence = []
            previous_sentence_length += sentences_length_of_abstract[counter - 1] + sep_gap
            for ind,offset in enumerate(value):
                if ind == 0:
                    start = offset[0]+previous_sentence_length
                else:
                    start = offset[0]+previous_sentence_length + 1
                updated_offsets_each_sentence.append((start, offset[1]+previous_sentence_length))
            updated_word_offsets.append(updated_offsets_each_sentence)
        counter += 1
    return updated_word_offsets

In [29]:
# reuse the function we used for updating the span offsets
#lets check what is the type of sentence spans
updated_word_offsets_all_documents = []
for index, word_offsets in enumerate(word_offsets_all_abstract):
    translation_id = word_offsets_all_abstract[index]['translation_id']
    word_offsets = word_offsets_all_abstract[index]['word_offsets']
    
    # find the single matching entry, then pull its document_length
    matching_entry = next(entry for entry in sentences_length_of_abstract if entry['translation_id'] == translation_id)
    sentences_length = matching_entry['document_length']
    updated_word_offsets_all_documents.append({
        'translation_id':translation_id,
        'updated_word_offsets': update_word_offsets(word_offsets, sentences_length)
    })

In [30]:
updated_word_offsets_all_documents

[{'translation_id': 3,
  'updated_word_offsets': [[(0, 7),
    (8, 11),
    (12, 13),
    (14, 19),
    (20, 31),
    (32, 33),
    (34, 44),
    (45, 46),
    (47, 54),
    (55, 61),
    (62, 64),
    (65, 73),
    (74, 81),
    (82, 87),
    (88, 92),
    (93, 95),
    (96, 105),
    (106, 110),
    (111, 112),
    (113, 117),
    (118, 126),
    (127, 134),
    (135, 139),
    (140, 141),
    (142, 153),
    (154, 158),
    (159, 162),
    (163, 165),
    (166, 173),
    (174, 182),
    (183, 192),
    (193, 204),
    (205, 213),
    (214, 219),
    (220, 227)],
   [(228, 231),
    (232, 234),
    (235, 240),
    (241, 242),
    (243, 250),
    (251, 261),
    (262, 270),
    (271, 273),
    (274, 282),
    (283, 291),
    (292, 303),
    (304, 305),
    (306, 316),
    (317, 322),
    (323, 328),
    (329, 337),
    (338, 348),
    (349, 351),
    (352, 354),
    (355, 358),
    (359, 367),
    (368, 373),
    (374, 380),
    (381, 382),
    (383, 392),
    (393, 404),
    (405, 409),
    (410, 416),
    (417, 425),
    (426, 434),
    (435, 442),
    (443, 454),
    (455, 467),
    (468, 479),
    (480, 485)],
   [(486, 490),
    (491, 493),
    (494, 501),
    (502, 510),
    (511, 512),
    (513, 518),
    (519, 521),
    (522, 529),
    (530, 532),
    (533, 539),
    (540, 548),
    (549, 552),
    (553, 560),
    (561, 563),
    (564, 569),
    (570, 580),
    (581, 588),
    (589, 596),
    (597, 600),
    (601, 609),
    (610, 615),
    (616, 622),
    (623, 629),
    (630, 637),
    (638, 645)],
   [(646, 651),
    (652, 654),
    (655, 664),
    (665, 673),
    (674, 679),
    (680, 685),
    (686, 692),
    (693, 697),
    (698, 706),
    (707, 717),
    (718, 719),
    (720, 725),
    (726, 729),
    (730, 737),
    (738, 747),
    (748, 749),
    (750, 759),
    (760, 767),
    (768, 770),
    (771, 773),
    (774, 778),
    (779, 788),
    (789, 793),
    (794, 802),
    (803, 808),
    (809, 813),
    (814, 818),
    (819, 826),
    (827, 833),
    (834, 837),
    (838, 846),
    (847, 858),
    (859, 862),
    (863, 870),
    (871, 873),
    (874, 882)],
   [(883, 887),
    (888, 892),
    (893, 899),
    (900, 910),
    (911, 917),
    (918, 925),
    (926, 932),
    (933, 935),
    (936, 943),
    (944, 945),
    (946, 954),
    (955, 967),
    (968, 969),
    (970, 975),
    (976, 984),
    (985, 988),
    (989, 997),
    (998, 1001),
    (1002, 1003),
    (1004, 1008),
    (1009, 1013),
    (1014, 1015),
    (1016, 1026),
    (1027, 1032),
    (1033, 1038),
    (1039, 1044),
    (1045, 1047),
    (1048, 1053),
    (1054, 1065),
    (1066, 1071),
    (1072, 1077),
    (1078, 1087),
    (1088, 1095),
    (1096, 1111),
    (1112, 1119),
    (1120, 1129)],
   [(1130, 1136),
    (1137, 1144),
    (1145, 1149),
    (1150, 1152),
    (1153, 1159),
    (1160, 1170),
    (1171, 1180),
    (1181, 1183),
    (1184, 1195),
    (1196, 1198),
    (1199, 1203),
    (1204, 1212),
    (1213, 1214),
    (1215, 1219),
    (1220, 1225),
    (1226, 1235),
    (1236, 1242),
    (1243, 1252),
    (1253, 1257),
    (1258, 1266),
    (1267, 1272),
    (1273, 1282),
    (1283, 1290),
    (1291, 1295),
    (1296, 1302),
    (1303, 1312)],
   [(1313, 1318),
    (1319, 1325),
    (1326, 1329),
    (1330, 1337),
    (1338, 1342),
    (1343, 1346),
    (1347, 1350),
    (1351, 1363),
    (1364, 1369),
    (1370, 1372),
    (1373, 1378),
    (1379, 1388),
    (1389, 1390),
    (1391, 1398),
    (1399, 1406),
    (1407, 1416),
    (1417, 1418),
    (1419, 1426),
    (1427, 1429),
    (1430, 1434),
    (1435, 1445),
    (1446, 1448),
    (1449, 1457),
    (1458, 1461),
    (1462, 1467),
    (1468, 1474),
    (1475, 1478),
    (1479, 1488),
    (1489, 1500),
    (1501, 1506),
    (1507, 1513),
    (1514, 1520),
    (1521, 1527),
    (1528, 1536),
    (1537, 1544),
    (1545, 1552),
    (1553, 1558)],
   [(1559, 1569),
    (1570, 1577),
    (1578, 1589),
    (1590, 1594),
    (1595, 1602),
    (1603, 1605),
    (1606, 1613),
    (1614, 1621),
    (1622, 1624),
    (1625, 1635),
    (1636, 1638),
    (1639, 1644),
    (1645, 1652),
    (1653, 1655),
    (1656, 1660),
    (1661, 1664),
    (1665, 1674),
    (1675, 1679),
    (1680, 1683),
    (1684, 1690),
    (1691, 1698),
    (1699, 1706),
    (1707, 1719),
    (1720, 1733),
    (1734, 1742),
    (1743, 1748),
    (1749, 1752),
    (1753, 1761),
    (1762, 1769),
    (1770, 1783),
    (1784, 1792)]]},
 {'translation_id': 7,
  'updated_word_offsets': [[(0, 9),
    (10, 13),
    (14, 21),
    (22, 32),
    (33, 41),
    (42, 43),
    (44, 48),
    (49, 53),
    (54, 55),
    (56, 64),
    (65, 69),
    (70, 77),
    (78, 79),
    (80, 84)],
   [(85, 94),
    (95, 97),
    (98, 110),
    (111, 118),
    (119, 124),
    (125, 127),
    (128, 135),
    (136, 140),
    (141, 148),
    (149, 157),
    (158, 166),
    (167, 169),
    (170, 177),
    (178, 185),
    (186, 191),
    (192, 199),
    (200, 211),
    (212, 223),
    (224, 232),
    (233, 238),
    (239, 244),
    (245, 247),
    (248, 258),
    (259, 270)],
   [(271, 277),
    (278, 282),
    (283, 289),
    (290, 296),
    (297, 305),
    (306, 312),
    (313, 321),
    (322, 332),
    (333, 344),
    (345, 352),
    (353, 355),
    (356, 363),
    (364, 372),
    (373, 377),
    (378, 383),
    (384, 386),
    (387, 397),
    (398, 408),
    (409, 410),
    (411, 423),
    (424, 427),
    (428, 429),
    (430, 436),
    (437, 440),
    (441, 447),
    (448, 456),
    (457, 465)],
   [(466, 470),
    (471, 483),
    (484, 486),
    (487, 492),
    (493, 498),
    (499, 505),
    (506, 511),
    (512, 520),
    (521, 523),
    (524, 532),
    (533, 541),
    (542, 544),
    (545, 551),
    (552, 553),
    (554, 559),
    (560, 567),
    (568, 572),
    (573, 578),
    (579, 587),
    (588, 590),
    (591, 600),
    (601, 609),
    (610, 614),
    (615, 622),
    (623, 631),
    (632, 639),
    (640, 644)],
   [(645, 654),
    (655, 659),
    (660, 668),
    (669, 670),
    (671, 676),
    (677, 678),
    (679, 687),
    (688, 692),
    (693, 699),
    (700, 706),
    (707, 710),
    (711, 716),
    (717, 724),
    (725, 736),
    (737, 745),
    (746, 748),
    (749, 752),
    (753, 758),
    (759, 760),
    (761, 767),
    (768, 774),
    (775, 781),
    (782, 788),
    (789, 791),
    (792, 794),
    (795, 798),
    (799, 802),
    (803, 805),
    (806, 810),
    (811, 816),
    (817, 826),
    (827, 835),
    (836, 843)],
   [(844, 849),
    (850, 853),
    (854, 855),
    (856, 860),
    (861, 870),
    (871, 881),
    (882, 885),
    (886, 891),
    (892, 903),
    (904, 911),
    (912, 913),
    (914, 918),
    (919, 923),
    (924, 932),
    (933, 935),
    (936, 945),
    (946, 953),
    (954, 955),
    (956, 963)],
   [(964, 966),
    (967, 973),
    (974, 975),
    (976, 984),
    (985, 989),
    (990, 996),
    (997, 1010),
    (1011, 1020),
    (1021, 1028),
    (1029, 1031),
    (1032, 1040),
    (1041, 1043),
    (1044, 1046),
    (1047, 1055),
    (1056, 1064),
    (1065, 1068),
    (1069, 1071),
    (1072, 1081),
    (1082, 1089),
    (1090, 1092),
    (1093, 1098),
    (1099, 1108),
    (1109, 1113),
    (1114, 1125),
    (1126, 1128),
    (1129, 1132),
    (1133, 1140),
    (1141, 1143),
    (1144, 1146),
    (1147, 1153),
    (1154, 1158),
    (1159, 1163),
    (1164, 1168),
    (1169, 1172),
    (1173, 1174),
    (1175, 1183),
    (1184, 1192),
    (1193, 1199),
    (1200, 1209),
    (1210, 1218),
    (1219, 1223),
    (1224, 1226),
    (1227, 1233),
    (1234, 1235),
    (1236, 1246),
    (1247, 1255),
    (1256, 1259),
    (1260, 1262),
    (1263, 1265),
    (1266, 1270),
    (1271, 1275),
    (1276, 1280),
    (1281, 1286),
    (1287, 1290),
    (1291, 1292),
    (1293, 1296),
    (1297, 1306),
    (1307, 1309),
    (1310, 1317),
    (1318, 1320),
    (1321, 1323),
    (1324, 1330),
    (1331, 1332),
    (1333, 1342),
    (1343, 1344),
    (1345, 1352),
    (1353, 1355),
    (1356, 1358),
    (1359, 1361),
    (1362, 1369),
    (1370, 1374),
    (1375, 1380)],
   [(1381, 1382),
    (1383, 1389),
    (1390, 1392),
    (1393, 1398),
    (1399, 1405),
    (1406, 1411),
    (1412, 1417),
    (1418, 1425),
    (1426, 1429),
    (1430, 1431),
    (1432, 1435),
    (1436, 1442),
    (1443, 1444),
    (1445, 1448),
    (1449, 1453),
    (1454, 1457),
    (1458, 1466),
    (1467, 1475),
    (1476, 1478),
    (1479, 1486),
    (1487, 1490),
    (1491, 1497),
    (1498, 1504),
    (1505, 1512),
    (1513, 1514),
    (1515, 1522),
    (1523, 1525),
    (1526, 1533),
    (1534, 1537),
    (1538, 1540),
    (1541, 1546),
    (1547, 1558),
    (1559, 1564),
    (1565, 1566),
    (1567, 1576),
    (1577, 1583),
    (1584, 1590),
    (1591, 1600),
    (1601, 1612),
    (1613, 1623),
    (1624, 1625),
    (1626, 1632)]]},
 {'translation_id': 6,
  'updated_word_offsets': [[(0, 3),
    (4, 11),
    (12, 20),
    (21, 25),
    (26, 34),
    (35, 39),
    (40, 48),
    (49, 50),
    (51, 57)],
   [(58, 61),
    (62, 70),
    (71, 81),
    (82, 88),
    (89, 93),
    (94, 103),
    (104, 116),
    (117, 123),
    (124, 128),
    (129, 137),
    (138, 148),
    (149, 150),
    (151, 158)],
   [(159, 167),
    (168, 178),
    (179, 181),
    (182, 188),
    (189, 193),
    (194, 203),
    (204, 208),
    (209, 217),
    (218, 228),
    (229, 231),
    (232, 237),
    (238, 245),
    (246, 247),
    (248, 254),
    (255, 256),
    (257, 261),
    (262, 266),
    (267, 273),
    (274, 287),
    (288, 295),
    (296, 303),
    (304, 307),
    (308, 315),
    (316, 324),
    (325, 327),
    (328, 334),
    (335, 345),
    (346, 350),
    (351, 357),
    (358, 366)],
   [(367, 372),
    (373, 383),
    (384, 389),
    (390, 400),
    (401, 412),
    (413, 422),
    (423, 429),
    (430, 439),
    (440, 444),
    (445, 447),
    (448, 452),
    (453, 462),
    (463, 470),
    (471, 479),
    (480, 490),
    (491, 494),
    (495, 501),
    (502, 508),
    (509, 516),
    (517, 518),
    (519, 525),
    (526, 530),
    (531, 539),
    (540, 549),
    (550, 551),
    (552, 558),
    (559, 570),
    (571, 578),
    (579, 583),
    (584, 589),
    (590, 597),
    (598, 602),
    (603, 609),
    (610, 615)],
   [(616, 624),
    (625, 627),
    (628, 635),
    (636, 639),
    (640, 647),
    (648, 650),
    (651, 661),
    (662, 669),
    (670, 672),
    (673, 679),
    (680, 688),
    (689, 691),
    (692, 698),
    (699, 709),
    (710, 719),
    (720, 721),
    (722, 723),
    (724, 727),
    (728, 737),
    (738, 739),
    (740, 746),
    (747, 753)],
   [(754, 762),
    (763, 768),
    (769, 775),
    (776, 784),
    (785, 793),
    (794, 797),
    (798, 808),
    (809, 811),
    (812, 823),
    (824, 830),
    (831, 839),
    (840, 842),
    (843, 850),
    (851, 853),
    (854, 858),
    (859, 864),
    (865, 869),
    (870, 878),
    (879, 880),
    (881, 891),
    (892, 898),
    (899, 909),
    (910, 912),
    (913, 919),
    (920, 931),
    (932, 937),
    (938, 948),
    (949, 956),
    (957, 958),
    (959, 969),
    (970, 979),
    (980, 990)],
   [(991, 996),
    (997, 1009),
    (1010, 1016),
    (1017, 1021),
    (1022, 1027),
    (1028, 1041),
    (1042, 1048),
    (1049, 1057),
    (1058, 1060),
    (1061, 1066),
    (1067, 1072),
    (1073, 1074),
    (1075, 1077),
    (1078, 1080),
    (1081, 1086),
    (1087, 1094),
    (1095, 1102),
    (1103, 1109),
    (1110, 1118),
    (1119, 1120),
    (1121, 1130),
    (1131, 1136),
    (1137, 1140),
    (1141, 1151),
    (1152, 1154),
    (1155, 1161),
    (1162, 1164),
    (1165, 1168),
    (1169, 1174),
    (1175, 1184),
    (1185, 1189),
    (1190, 1197),
    (1198, 1202)],
   [(1203, 1209),
    (1210, 1214),
    (1215, 1224),
    (1225, 1229),
    (1230, 1242),
    (1243, 1253),
    (1254, 1263),
    (1264, 1274),
    (1275, 1276),
    (1277, 1283),
    (1284, 1285),
    (1286, 1292),
    (1293, 1306),
    (1307, 1314),
    (1315, 1320),
    (1321, 1322),
    (1323, 1330),
    (1331, 1339),
    (1340, 1347),
    (1348, 1353),
    (1354, 1358),
    (1359, 1364),
    (1365, 1374)]]},
 {'translation_id': 19,
  'updated_word_offsets': [[(0, 3),
    (4, 12),
    (13, 15),
    (16, 23),
    (24, 30),
    (31, 38),
    (39, 46),
    (47, 59),
    (60, 67),
    (68, 71),
    (72, 80),
    (81, 88),
    (89, 94)],
   [(95, 98),
    (99, 108),
    (109, 118),
    (119, 126),
    (127, 135),
    (136, 141),
    (142, 149),
    (150, 158),
    (159, 166),
    (167, 168),
    (169, 172),
    (173, 183),
    (184, 192),
    (193, 195),
    (196, 203),
    (204, 211),
    (212, 215),
    (216, 224),
    (225, 230),
    (231, 243),
    (244, 251),
    (252, 258)],
   [(259, 267),
    (268, 275),
    (276, 282),
    (283, 288),
    (289, 290),
    (291, 294),
    (295, 300),
    (301, 309),
    (310, 317),
    (318, 325),
    (326, 330),
    (331, 341),
    (342, 343),
    (344, 351),
    (352, 359),
    (360, 364),
    (365, 369),
    (370, 379)],
   [(380, 385),
    (386, 390),
    (391, 398),
    (399, 406),
    (407, 417),
    (418, 419),
    (420, 425),
    (426, 433),
    (434, 435),
    (436, 438),
    (439, 447),
    (448, 451),
    (452, 460),
    (461, 471),
    (472, 473),
    (474, 486),
    (487, 492),
    (493, 494),
    (495, 503),
    (504, 510),
    (511, 518),
    (519, 527),
    (528, 532),
    (533, 539),
    (540, 549),
    (550, 558),
    (559, 567)],
   [(568, 574),
    (575, 580),
    (581, 588),
    (589, 595),
    (596, 600),
    (601, 606),
    (607, 613),
    (614, 616),
    (617, 622),
    (623, 631),
    (632, 637),
    (638, 646),
    (647, 649),
    (650, 656),
    (657, 663),
    (664, 668),
    (669, 678),
    (679, 687),
    (688, 690),
    (691, 698),
    (699, 703),
    (704, 709),
    (710, 711),
    (712, 718)],
   [(719, 724),
    (725, 731),
    (732, 734),
    (735, 745),
    (746, 750),
    (751, 757),
    (758, 764),
    (765, 766),
    (767, 773),
    (774, 779),
    (780, 792),
    (793, 797),
    (798, 803),
    (804, 805),
    (806, 813),
    (814, 815),
    (816, 822),
    (823, 829),
    (830, 835),
    (836, 841),
    (842, 844),
    (845, 850),
    (851, 856),
    (857, 859),
    (860, 874),
    (875, 880),
    (881, 889),
    (890, 891),
    (892, 893),
    (894, 900),
    (901, 906),
    (907, 912),
    (913, 916),
    (917, 922),
    (923, 936),
    (937, 938),
    (939, 949)],
   [(950, 956),
    (957, 968),
    (969, 977),
    (978, 984),
    (985, 986),
    (987, 993),
    (994, 996),
    (997, 1007),
    (1008, 1019),
    (1020, 1022),
    (1023, 1027),
    (1028, 1030),
    (1031, 1034),
    (1035, 1039),
    (1040, 1042),
    (1043, 1051),
    (1052, 1058),
    (1059, 1066),
    (1067, 1069),
    (1070, 1080),
    (1081, 1085),
    (1086, 1087),
    (1088, 1094),
    (1095, 1100),
    (1101, 1106),
    (1107, 1110),
    (1111, 1114),
    (1115, 1116),
    (1117, 1124),
    (1125, 1131),
    (1132, 1140),
    (1141, 1145),
    (1146, 1152),
    (1153, 1157),
    (1158, 1164),
    (1165, 1170),
    (1171, 1173),
    (1174, 1180)],
   [(1181, 1184),
    (1185, 1190),
    (1191, 1197),
    (1198, 1200),
    (1201, 1208),
    (1209, 1215),
    (1216, 1220),
    (1221, 1229),
    (1230, 1231),
    (1232, 1237),
    (1238, 1239),
    (1240, 1246),
    (1247, 1256),
    (1257, 1258),
    (1259, 1267),
    (1268, 1272),
    (1273, 1278),
    (1279, 1280),
    (1281, 1286),
    (1287, 1288),
    (1289, 1300),
    (1301, 1303),
    (1304, 1311),
    (1312, 1320),
    (1321, 1329),
    (1330, 1332),
    (1333, 1335),
    (1336, 1340),
    (1341, 1344),
    (1345, 1355),
    (1356, 1361),
    (1362, 1363)]]}]

**We can retrieve sentence start and end from the word offset boundaries**

we will need this for sentence alignment between translation and source table

In [31]:
def get_sentence_length_of_abstract_indexes(updated_word_offsets):

    sentences_length_of_abstract_indexes = []
    for index, sentence in enumerate(updated_word_offsets):

        sentences_length_of_abstract_indexes.append((sentence[0][0], sentence[-1][1]))
    return sentences_length_of_abstract_indexes

In [32]:
sentences_length_of_all_abstract_indexes = []
for word_offsets in updated_word_offsets_all_documents:
    offsets = word_offsets['updated_word_offsets']
    translation_id = word_offsets['translation_id']
    sentences_length_of_all_abstract_indexes.append({
        'translation_id':translation_id,
        'updated_sentence_indexes': get_sentence_length_of_abstract_indexes(offsets)
    })

In [33]:
sentences_length_of_all_abstract_indexes[0]

{'translation_id': 3,
 'updated_sentence_indexes': [(0, 227),
  (228, 485),
  (486, 645),
  (646, 882),
  (883, 1129),
  (1130, 1312),
  (1313, 1558),
  (1559, 1792)]}

**convert the updated spans offsets into list of tuples**

In [34]:
updated_spans_offsets_all_documents[0]

{'translation_id': 3,
 'updated_spans_offsets': [[{'text': ['k', 'vyzkoušení', 'a'],
    'startnew': 32,
    'endnew': 46},
   {'text': ['HSBC'], 'startnew': 88, 'endnew': 92},
   {'text': ['vytlačení'], 'startnew': 96, 'endnew': 105},
   {'text': ['z', 'jeho'], 'startnew': 111, 'endnew': 117},
   {'text': ['klíčová', 'priorita'], 'startnew': 166, 'endnew': 182}],
  [{'text': ['jedno'], 'startnew': 235, 'endnew': 240},
   {'text': ['je', 'ze'], 'startnew': 349, 'endnew': 354},
   {'text': ['podstaty'], 'startnew': 359, 'endnew': 367},
   {'text': ['globální'], 'startnew': 426, 'endnew': 434},
   {'text': ['klientského'], 'startnew': 443, 'endnew': 454},
   {'text': ['společnosti'], 'startnew': 468, 'endnew': 479}],
  [{'text': ['uvedla,'], 'startnew': 553, 'endnew': 560},
   {'text': ['iniciativa', '„síťový', 'příjem“'],
    'startnew': 570,
    'endnew': 596},
   {'text': ['přinesla'], 'startnew': 601, 'endnew': 609},
   {'text': ['stovky'], 'startnew': 623, 'endnew': 629}],
  [{'text': ['Pohon'], 'startnew': 646, 'endnew': 651},
   {'text': ['bránit', 'svou'], 'startnew': 686, 'endnew': 697},
   {'text': ['přítomnost'], 'startnew': 707, 'endnew': 717},
   {'text': ['kdy'], 'startnew': 726, 'endnew': 729},
   {'text': ['kde'], 'startnew': 834, 'endnew': 837},
   {'text': ['návratnosti', 'pod'], 'startnew': 847, 'endnew': 862}],
  [{'text': ['do'], 'startnew': 933, 'endnew': 935},
   {'text': ['urovnání'], 'startnew': 976, 'endnew': 984},
   {'text': ['miliardy'], 'startnew': 989, 'endnew': 997},
   {'text': ['kvůli', 'tomu,'], 'startnew': 1033, 'endnew': 1044},
   {'text': ['jednotky.'], 'startnew': 1120, 'endnew': 1129}],
  [{'text': ['zákazníky', '“a', 'společnosti'],
    'startnew': 1171,
    'endnew': 1195},
   {'text': ['navazuje'], 'startnew': 1204, 'endnew': 1212},
   {'text': ['transakcí'], 'startnew': 1243, 'endnew': 1252},
   {'text': ['dříve'], 'startnew': 1267, 'endnew': 1272},
   {'text': ['spojení'], 'startnew': 1283, 'endnew': 1290}],
  [{'text': ['uvolnil'], 'startnew': 1330, 'endnew': 1337},
   {'text': ['zaměstnanců,',
     'kteří',
     'by',
     'mohli',
     'přecházet',
     'z',
     'ručních',
     'kontrol'],
    'startnew': 1351,
    'endnew': 1406},
   {'text': ['do', 'rolí', 'zaměřených'], 'startnew': 1427, 'endnew': 1445},
   {'text': ['klienta,'], 'startnew': 1449, 'endnew': 1457},
   {'text': ['trávit', 'čas', 'pomáháním'], 'startnew': 1468, 'endnew': 1488},
   {'text': ['provozní'], 'startnew': 1528, 'endnew': 1536},
   {'text': ['obchodu'], 'startnew': 1545, 'endnew': 1552}],
  [{'text': ['Společnost'], 'startnew': 1559, 'endnew': 1569},
   {'text': ['společnosti'], 'startnew': 1578, 'endnew': 1589},
   {'text': ['uvedla,'], 'startnew': 1595, 'endnew': 1602},
   {'text': ['okamžik', 'žárovky'], 'startnew': 1606, 'endnew': 1621},
   {'text': ['uvědomuje,'], 'startnew': 1625, 'endnew': 1635},
   {'text': ['přemístěn'], 'startnew': 1665, 'endnew': 1674},
   {'text': ['„zelené',
     'vlajky“',
     'atraktivních',
     'potenciálních',
     'klientů,',
     'spíše',
     'než',
     '„červené',
     'vlajky“',
     'protiprávního',
     'jednání.'],
    'startnew': 1691,
    'endnew': 1792}]]}

In [35]:
def updated_spans_offsets_to_list_of_tupes(spans_per_doc):
    spans_list_of_tuples = []
    for spans in spans_per_doc:
        for span in spans:
            spans_list_of_tuples.append((span['startnew'], span['endnew']))
    return spans_list_of_tuples

In [36]:
#run the above function
updated_spans_list_of_tuples_all_docs = []
for index, updated_spans in enumerate(updated_spans_offsets_all_documents):
    translation_id = updated_spans['translation_id']
    spans = updated_spans['updated_spans_offsets']
    updated_spans_list_of_tuples_all_docs.append({
        'translation_id': translation_id,
        'updated_spans_list_of_tuples': updated_spans_offsets_to_list_of_tupes(spans)
    })

In [37]:
updated_spans_list_of_tuples_all_docs[0]

{'translation_id': 3,
 'updated_spans_list_of_tuples': [(32, 46),
  (88, 92),
  (96, 105),
  (111, 117),
  (166, 182),
  (235, 240),
  (349, 354),
  (359, 367),
  (426, 434),
  (443, 454),
  (468, 479),
  (553, 560),
  (570, 596),
  (601, 609),
  (623, 629),
  (646, 651),
  (686, 697),
  (707, 717),
  (726, 729),
  (834, 837),
  (847, 862),
  (933, 935),
  (976, 984),
  (989, 997),
  (1033, 1044),
  (1120, 1129),
  (1171, 1195),
  (1204, 1212),
  (1243, 1252),
  (1267, 1272),
  (1283, 1290),
  (1330, 1337),
  (1351, 1406),
  (1427, 1445),
  (1449, 1457),
  (1468, 1488),
  (1528, 1536),
  (1545, 1552),
  (1559, 1569),
  (1578, 1589),
  (1595, 1602),
  (1606, 1621),
  (1625, 1635),
  (1665, 1674),
  (1691, 1792)]}

### Now show the final highlightig for four abstracts

get the text and merge them to form the abstracts

In [50]:
first_4_text_list

(3, 7, 6, 19)

In [51]:
all_abstracts_translations_text = []

for translation_id, group in df_en_cz.groupby('Translation_id'):
    group_sorted = group.sort_values('line_id')
    merged_text = ' '.join(group_sorted['translation'].tolist())
    
    all_abstracts_translations_text.append({
        'translation_id': translation_id,
        'translation_text': merged_text
    })
ids_to_keep = (3, 7, 6, 19)

filtered_translations_text = [
    entry for entry in all_abstracts_translations_text
    if entry['translation_id'] in ids_to_keep
]

In [55]:
filtered_translations_text[0]

{'translation_id': 3,
 'translation_text': 'Využití dat a umělé inteligence k vyzkoušení a zvýšení výnosů je součástí širšího tlaku HSBC na vytlačení více z jeho rozsáhlé fyzické sítě a klientských dat, což je klíčová priorita dočasného generálního ředitele Noela Quinna. „Je to jedno z prvních komerčních investic do prevence finanční kriminality a podnikání, které tímto způsobem získáváme, je ze své podstaty nižší riziko a rychlejší vítězství,“ řekl Stuart Nivison, globální vedoucí klientského bankovnictví společnosti HSBC. HSBC se odmítla vyjádřit k tomu, co očekává od nového systému, ale uvedla, že širší iniciativa „síťový příjem“ již přinesla další příjmy stovky milionů dolarů. Pohon je důležitou součástí úsilí banky bránit svou globální přítomnost v době, kdy někteří analytici a investoři říkají, že by měla zmenšovat nebo opouštět trhy, jako jsou Spojené státy, kde dosahuje návratnosti pod náklady na kapitál. HSBC byla nucena investovat stovky milionů dolarů do souladu s finanční kriminalitou v rámci urovnání 1,9 miliardy USD v roce 2012 s americkými úřady kvůli tomu, že banka nezabránila praní peněz drogovými kartely prostřednictvím mexické jednotky. Systém funguje tak, že mapuje jednotlivé zákazníky “a společnosti na sebe navazuje a poté hledá neobvyklé vzorce transakcí nebo odhalení dříve neznámých spojení mezi těmito entitami. Tento systém již uvolnil více než 400 zaměstnanců, kteří by mohli přecházet z ručních kontrol transakcí a záznamů do rolí zaměřených na klienta, kde mohou trávit čas pomáháním zákazníkům, uvedl Adrian Rigby, hlavní provozní ředitel obchodu HSBC. Společnost Nivison společnosti HSBC uvedla, že okamžik žárovky si uvědomuje, že tento nástroj by mohl být přemístěn tak, aby hledal „zelené vlajky“ atraktivních potenciálních klientů, spíše než „červené vlajky“ protiprávního jednání.'}

In [56]:
len(filtered_translations_text[0]['translation_text'])

1792

In [63]:
def create_html_highlights(translation_id, text, offsets):
    
    text_highlight = f"highlight_translation_id_{translation_id}"
    # 1. Store annotations separately (preserves offsets)
    annotations = [{"start": s, "end": e, "text": text[s:e]} for s, e in offsets]

    # 2. Function to generate highlighted HTML
    def generate_html_highlight(text, annotations, color="yellow"):
        """
        Creates HTML with highlighted spans without modifying original text
        Preserves original offsets for future use
        """
        # Sort annotations by start position
        sorted_ann = sorted(annotations, key=lambda x: x["start"])

        html_parts = []
        last_end = 0

        for ann in sorted_ann:
            # Add text before highlight
            html_parts.append(text[last_end:ann["start"]])

            # Add highlighted text
            html_parts.append(f'<span style="background-color: {color};">{ann["text"]}</span>')

            last_end = ann["end"]

        # Add remaining text
        html_parts.append(text[last_end:])

        return "".join(html_parts)

    # 3. Generate and save HTML
    html_output = generate_html_highlight(text, annotations, "green")
    
    with open(f"{text_highlight}.html", "w", encoding="utf-8") as f:
        f.write(f"""<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Highlighted Text</title>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
            span {{ border-radius: 3px; padding: 0 2px; }}
        </style>
    </head>
    <body>
        <pre>{html_output}</pre>
    </body>
    </html>""")

    print(f"Highlighted HTML saved to {text_highlight}.html")
    return html_output

### what is needed to fix
- [ ]1. in the final list of tuples span, there are spans which are less than 4 characters
    1. should i trim it in the final tuple
    
- [ ] 2. there are very large spans - should we omit those.
- [ ] 3. how the randomly span selection (no spans, 4,8,12) happens?

### highlighting with ideal spans:

In [69]:
html_outputs_all_docs = []
for each_text in filtered_translations_text:
    translation_id = each_text["translation_id"]
    text = each_text['translation_text']
    match = next(
    (row for row in updated_spans_list_of_tuples_all_docs if row['translation_id'] == translation_id),
    None
    )
    span_tuples = match['updated_spans_list_of_tuples'] if match else None
    html_outputs_all_docs.append({
        'translation_id': translation_id,
        'html_output': create_html_highlights(translation_id, text, span_tuples)
    })

Highlighted HTML saved to highlight_translation_id_3.html
Highlighted HTML saved to highlight_translation_id_6.html
Highlighted HTML saved to highlight_translation_id_7.html
Highlighted HTML saved to highlight_translation_id_19.html

**now show each html highlight**

In [74]:

for highlight in html_outputs_all_docs:
    print(f"translation_id: {highlight['translation_id']}")
    from IPython.display import HTML
    display(HTML(highlight['html_output']))

translation_id: 3

translation_id: 6

translation_id: 7

translation_id: 19

In [77]:
updated_spans_offsets_all_documents[3]

{'translation_id': 19,
 'updated_spans_offsets': [[{'text': ['vysílají'],
    'startnew': 4,
    'endnew': 12},
   {'text': ['vojáky,'], 'startnew': 31, 'endnew': 38},
   {'text': ['íránské'], 'startnew': 81, 'endnew': 88}],
  [{'text': ['odesílají'], 'startnew': 99, 'endnew': 108},
   {'text': ['jednotek', 'do', 'Saúdské', 'Arábie,'],
    'startnew': 184,
    'endnew': 211},
   {'text': ['odrazily'], 'startnew': 216, 'endnew': 224},
   {'text': ['agresivnější'], 'startnew': 231, 'endnew': 243},
   {'text': ['Íránu.'], 'startnew': 252, 'endnew': 258}],
  [{'text': ['další'], 'startnew': 295, 'endnew': 300},
   {'text': ['připraveny'], 'startnew': 331, 'endnew': 341},
   {'text': ['jít,'], 'startnew': 360, 'endnew': 364}],
  [{'text': ['"Jiné'], 'startnew': 380, 'endnew': 385},
   {'text': ['íránské', 'zneužívání'], 'startnew': 399, 'endnew': 417},
   {'text': ['regionu'], 'startnew': 426, 'endnew': 433},
   {'text': ['hledáme,'], 'startnew': 439, 'endnew': 447},
   {'text': ['přispěli', 'prostředky', 'v', 'mezinárodním', 'úsilí'],
    'startnew': 452,
    'endnew': 492},
   {'text': ['Arábie,"'], 'startnew': 519, 'endnew': 527}],
  [{'text': ['Minulý', 'týden'], 'startnew': 568, 'endnew': 580},
   {'text': ['z'], 'startnew': 710, 'endnew': 711}],
  [{'text': ['uvedl,'], 'startnew': 725, 'endnew': 731},
   {'text': ['násilnějších', 'činů'], 'startnew': 780, 'endnew': 797},
   {'text': ['-'], 'startnew': 814, 'endnew': 815},
   {'text': ['tohoto'], 'startnew': 823, 'endnew': 829},
   {'text': ['na', 'tento', 'měsíc'], 'startnew': 842, 'endnew': 856},
   {'text': ['-'], 'startnew': 890, 'endnew': 891},
   {'text': ['útoky', 'zintenzívnily'], 'startnew': 917, 'endnew': 936},
   {'text': ['odsoudily.'], 'startnew': 939, 'endnew': 949}],
  [{'text': ['reholové'], 'startnew': 969, 'endnew': 977},
   {'text': ['si', 'nárokovali', 'odpovědnost'],
    'startnew': 994,
    'endnew': 1019},
   {'text': ['ropnou', 'továrnu', 'na', 'zpracování', 'ropy'],
    'startnew': 1052,
    'endnew': 1085},
   {'text': ['Irán', 'přímo.'], 'startnew': 1141, 'endnew': 1152},
   {'text': ['odmítl', 'účast'], 'startnew': 1158, 'endnew': 1170},
   {'text': ['útoku.'], 'startnew': 1174, 'endnew': 1180}],
  [{'text': ['"Je'], 'startnew': 1181, 'endnew': 1184},
   {'text': ['zbraně'], 'startnew': 1209, 'endnew': 1215},
   {'text': ['vyrobeny'], 'startnew': 1221, 'endnew': 1229},
   {'text': ['vypuštěny'], 'startnew': 1247, 'endnew': 1256},
   {'text': ['Jemenu,"'], 'startnew': 1259, 'endnew': 1267},
   {'text': ['všechna', 'označení', 'ukazují,'],
    'startnew': 1304,
    'endnew': 1329},
   {'text': ['"'], 'startnew': 1362, 'endnew': 1363}]]}

**end**

In [60]:
from IPython.display import HTML
HTML(html_output)